# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Acceleration import _AccelerationConstant
from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.Energy import _EnergyConstant
from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._constants.Length import _LengthConstant
from quantype._constants.Mass import _MassConstant
from quantype._constants.Momentum import _MomentumConstant
from quantype._constants.Time import _TimeConstant
from quantype._constants.Velocity import _VelocityConstant
from quantype._generated import (
    Acceleration,
    Dimensionless,
    Energy,
    Frequency,
    InverseTime,
    Length,
    Mass,
    Momentum,
    Time,
    Velocity,
)
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import AccelerationKind, DimensionlessKind, Div, FrequencyKind, Mul
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class AccelerationPerFrequency(Quantity[Div[AccelerationKind, FrequencyKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: AccelerationPerFrequency[float, S], other: Time[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def __mul__(
        self, other: Time[V, S] | Time[float, S] | _TimeConstant, /
    ) -> Length[V, S]: ...
    @overload
    def __mul__[W](
        self: AccelerationPerFrequency[float, S], other: Frequency[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __mul__(
        self, other: Frequency[V, S] | Frequency[float, S] | _FrequencyConstant, /
    ) -> Acceleration[V, S]: ...
    @overload
    def __mul__[W](
        self: AccelerationPerFrequency[float, S], other: InverseTime[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __mul__(
        self, other: InverseTime[V, S] | InverseTime[float, S] | _InverseTimeConstant, /
    ) -> Acceleration[V, S]: ...
    @overload
    def __mul__[W](
        self: AccelerationPerFrequency[float, S], other: Mass[W, S], /
    ) -> Momentum[W, S]: ...
    @overload
    def __mul__(
        self, other: Mass[V, S] | Mass[float, S] | _MassConstant, /
    ) -> Momentum[V, S]: ...
    @overload
    def __mul__[W](
        self: AccelerationPerFrequency[float, S], other: Momentum[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def __mul__(
        self, other: Momentum[V, S] | Momentum[float, S] | _MomentumConstant, /
    ) -> Energy[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> AccelerationPerFrequency[V, S]: ...
    @overload
    def __mul__(
        self: AccelerationPerFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AccelerationPerFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: AccelerationPerFrequency[float, S], other: W, /
    ) -> AccelerationPerFrequency[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> AccelerationPerFrequency[V, S]: ...
    @overload
    def __mul__[K, W](
        self: AccelerationPerFrequency[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[AccelerationKind, FrequencyKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[AccelerationKind, FrequencyKind], K], V, S]: ...
    def _rmul_Time_f(self, other: Time[float, S], /) -> Length[V, S]: ...
    @overload
    def _rmul_Time[W](
        self: AccelerationPerFrequency[float, S], other: Time[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def _rmul_Time(self, other: Time[V, S], /) -> Length[V, S]: ...
    def _rmul_Frequency_f(
        self, other: Frequency[float, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    def _rmul_Frequency[W](
        self: AccelerationPerFrequency[float, S], other: Frequency[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def _rmul_Frequency(self, other: Frequency[V, S], /) -> Acceleration[V, S]: ...
    def _rmul_InverseTime_f(
        self, other: InverseTime[float, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    def _rmul_InverseTime[W](
        self: AccelerationPerFrequency[float, S], other: InverseTime[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def _rmul_InverseTime(self, other: InverseTime[V, S], /) -> Acceleration[V, S]: ...
    def _rmul_Mass_f(self, other: Mass[float, S], /) -> Momentum[V, S]: ...
    @overload
    def _rmul_Mass[W](
        self: AccelerationPerFrequency[float, S], other: Mass[W, S], /
    ) -> Momentum[W, S]: ...
    @overload
    def _rmul_Mass(self, other: Mass[V, S], /) -> Momentum[V, S]: ...
    def _rmul_Momentum_f(self, other: Momentum[float, S], /) -> Energy[V, S]: ...
    @overload
    def _rmul_Momentum[W](
        self: AccelerationPerFrequency[float, S], other: Momentum[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def _rmul_Momentum(self, other: Momentum[V, S], /) -> Energy[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: AccelerationPerFrequency[float, S], other: Time[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __truediv__(
        self, other: Time[V, S] | Time[float, S] | _TimeConstant, /
    ) -> Acceleration[V, S]: ...
    @overload
    def __truediv__[W](
        self: AccelerationPerFrequency[float, S], other: Velocity[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: Velocity[V, S] | Velocity[float, S] | _VelocityConstant, /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__[W](
        self: AccelerationPerFrequency[float, S], other: Frequency[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def __truediv__(
        self, other: Frequency[V, S] | Frequency[float, S] | _FrequencyConstant, /
    ) -> Length[V, S]: ...
    @overload
    def __truediv__[W](
        self: AccelerationPerFrequency[float, S], other: InverseTime[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def __truediv__(
        self, other: InverseTime[V, S] | InverseTime[float, S] | _InverseTimeConstant, /
    ) -> Length[V, S]: ...
    @overload
    def __truediv__[W](
        self: AccelerationPerFrequency[float, S], other: Acceleration[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: Acceleration[V, S] | Acceleration[float, S] | _AccelerationConstant,
        /,
    ) -> Time[V, S]: ...
    @overload
    def __truediv__[W](
        self: AccelerationPerFrequency[float, S],
        other: AccelerationPerFrequency[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: AccelerationPerFrequency[V, S]
        | AccelerationPerFrequency[float, S]
        | _AccelerationPerFrequencyConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> AccelerationPerFrequency[V, S]: ...
    @overload
    def __truediv__(
        self: AccelerationPerFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AccelerationPerFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: AccelerationPerFrequency[float, S], other: W, /
    ) -> AccelerationPerFrequency[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> AccelerationPerFrequency[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: AccelerationPerFrequency[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[AccelerationKind, FrequencyKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[AccelerationKind, FrequencyKind], K], V, S]: ...
    def _rtruediv_Length_f(self, other: Length[float, S], /) -> Time[V, S]: ...
    @overload
    def _rtruediv_Length[W](
        self: AccelerationPerFrequency[float, S], other: Length[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def _rtruediv_Length(self, other: Length[V, S], /) -> Time[V, S]: ...
    def _rtruediv_Velocity_f(
        self, other: Velocity[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def _rtruediv_Velocity[W](
        self: AccelerationPerFrequency[float, S], other: Velocity[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def _rtruediv_Velocity(self, other: Velocity[V, S], /) -> Dimensionless[V, S]: ...
    def _rtruediv_Energy_f(self, other: Energy[float, S], /) -> Momentum[V, S]: ...
    @overload
    def _rtruediv_Energy[W](
        self: AccelerationPerFrequency[float, S], other: Energy[W, S], /
    ) -> Momentum[W, S]: ...
    @overload
    def _rtruediv_Energy(self, other: Energy[V, S], /) -> Momentum[V, S]: ...
    def _rtruediv_Momentum_f(self, other: Momentum[float, S], /) -> Mass[V, S]: ...
    @overload
    def _rtruediv_Momentum[W](
        self: AccelerationPerFrequency[float, S], other: Momentum[W, S], /
    ) -> Mass[W, S]: ...
    @overload
    def _rtruediv_Momentum(self, other: Momentum[V, S], /) -> Mass[V, S]: ...
    def _rtruediv_Acceleration_f(
        self, other: Acceleration[float, S], /
    ) -> Frequency[V, S]: ...
    @overload
    def _rtruediv_Acceleration[W](
        self: AccelerationPerFrequency[float, S], other: Acceleration[W, S], /
    ) -> Frequency[W, S]: ...
    @overload
    def _rtruediv_Acceleration(
        self, other: Acceleration[V, S], /
    ) -> Frequency[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: AccelerationPerFrequency[float, S], other: Time[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def __matmul__(self, other: Time[V, S] | Time[float, S], /) -> Length[V, S]: ...
    @overload
    def __matmul__[W](
        self: AccelerationPerFrequency[float, S], other: Frequency[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __matmul__(
        self, other: Frequency[V, S] | Frequency[float, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    def __matmul__[W](
        self: AccelerationPerFrequency[float, S], other: InverseTime[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __matmul__(
        self, other: InverseTime[V, S] | InverseTime[float, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    def __matmul__[W](
        self: AccelerationPerFrequency[float, S], other: Mass[W, S], /
    ) -> Momentum[W, S]: ...
    @overload
    def __matmul__(self, other: Mass[V, S] | Mass[float, S], /) -> Momentum[V, S]: ...
    @overload
    def __matmul__[W](
        self: AccelerationPerFrequency[float, S], other: Momentum[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def __matmul__(
        self, other: Momentum[V, S] | Momentum[float, S], /
    ) -> Energy[V, S]: ...
    @overload
    def __matmul__(
        self: AccelerationPerFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AccelerationPerFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: AccelerationPerFrequency[float, S], other: W, /
    ) -> AccelerationPerFrequency[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> AccelerationPerFrequency[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: AccelerationPerFrequency[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[AccelerationKind, FrequencyKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[AccelerationKind, FrequencyKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> AccelerationPerFrequency[V, S]: ...
    @overload
    def __rmul__(
        self: AccelerationPerFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AccelerationPerFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: AccelerationPerFrequency[float, S], other: W, /
    ) -> AccelerationPerFrequency[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> AccelerationPerFrequency[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: AccelerationPerFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AccelerationPerFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: AccelerationPerFrequency[float, S], other: W, /
    ) -> AccelerationPerFrequency[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> AccelerationPerFrequency[V, S]: ...
    @override
    def item(self) -> AccelerationPerFrequency[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[AccelerationKind, FrequencyKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: AccelerationPerFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[AccelerationKind, FrequencyKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: AccelerationPerFrequency[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[AccelerationKind, FrequencyKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[AccelerationKind, FrequencyKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: AccelerationPerFrequency[float, S],
        other: Quantity[Div[AccelerationKind, FrequencyKind], W, S],
        /,
    ) -> AccelerationPerFrequency[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[AccelerationKind, FrequencyKind], V, S]
        | Quantity[Div[AccelerationKind, FrequencyKind], float, S],
        /,
    ) -> AccelerationPerFrequency[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: AccelerationPerFrequency[float, S],
        other: Quantity[Div[AccelerationKind, FrequencyKind], W, S],
        /,
    ) -> AccelerationPerFrequency[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[AccelerationKind, FrequencyKind], V, S]
        | Quantity[Div[AccelerationKind, FrequencyKind], float, S],
        /,
    ) -> AccelerationPerFrequency[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> AccelerationPerFrequency[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> AccelerationPerFrequency[W, S]: ...

class _AccelerationPerFrequencyConstant(Constant[Div[AccelerationKind, FrequencyKind]]):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> AccelerationPerFrequency[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[AccelerationKind, FrequencyKind]]
    ) -> AccelerationPerFrequency[float]: ...
    @overload
    @override
    def __mul__(self, other: _TimeConstant, /) -> _LengthConstant: ...
    @overload
    def __mul__(self, other: _FrequencyConstant, /) -> _AccelerationConstant: ...
    @overload
    def __mul__(self, other: _InverseTimeConstant, /) -> _AccelerationConstant: ...
    @overload
    def __mul__(self, other: _MassConstant, /) -> _MomentumConstant: ...
    @overload
    def __mul__(self, other: _MomentumConstant, /) -> _EnergyConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[AccelerationKind, FrequencyKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AccelerationPerFrequencyConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Time[W, T], /) -> Length[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: Frequency[W, T], /
    ) -> Acceleration[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: InverseTime[W, T], /
    ) -> Acceleration[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Mass[W, T], /) -> Momentum[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Momentum[W, T], /) -> Energy[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[AccelerationKind, FrequencyKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(self, other: _TimeConstant, /) -> _AccelerationConstant: ...
    @overload
    def __truediv__(self, other: _VelocityConstant, /) -> _DimensionlessConstant: ...
    @overload
    def __truediv__(self, other: _FrequencyConstant, /) -> _LengthConstant: ...
    @overload
    def __truediv__(self, other: _InverseTimeConstant, /) -> _LengthConstant: ...
    @overload
    def __truediv__(self, other: _AccelerationConstant, /) -> _TimeConstant: ...
    @overload
    def __truediv__(
        self, other: _AccelerationPerFrequencyConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[AccelerationKind, FrequencyKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AccelerationPerFrequencyConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Time[W, T], /
    ) -> Acceleration[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Velocity[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Frequency[W, T], /
    ) -> Length[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: InverseTime[W, T], /
    ) -> Length[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Acceleration[W, T], /
    ) -> Time[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: AccelerationPerFrequency[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[AccelerationKind, FrequencyKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AccelerationPerFrequencyConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[AccelerationKind, FrequencyKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[AccelerationKind, FrequencyKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[AccelerationKind, FrequencyKind]], W, T]: ...
    def _rmul_Time_f[T: UnitSystem](
        self, other: Time[float, T], /
    ) -> Length[float, T]: ...
    def _rmul_Time[W, T: UnitSystem](self, other: Time[W, T], /) -> Length[W, T]: ...
    def _cmul_Time(self, other: _TimeConstant, /) -> _LengthConstant: ...
    def _rmul_Frequency_f[T: UnitSystem](
        self, other: Frequency[float, T], /
    ) -> Acceleration[float, T]: ...
    def _rmul_Frequency[W, T: UnitSystem](
        self, other: Frequency[W, T], /
    ) -> Acceleration[W, T]: ...
    def _cmul_Frequency(
        self, other: _FrequencyConstant, /
    ) -> _AccelerationConstant: ...
    def _rmul_InverseTime_f[T: UnitSystem](
        self, other: InverseTime[float, T], /
    ) -> Acceleration[float, T]: ...
    def _rmul_InverseTime[W, T: UnitSystem](
        self, other: InverseTime[W, T], /
    ) -> Acceleration[W, T]: ...
    def _cmul_InverseTime(
        self, other: _InverseTimeConstant, /
    ) -> _AccelerationConstant: ...
    def _rmul_Mass_f[T: UnitSystem](
        self, other: Mass[float, T], /
    ) -> Momentum[float, T]: ...
    def _rmul_Mass[W, T: UnitSystem](self, other: Mass[W, T], /) -> Momentum[W, T]: ...
    def _cmul_Mass(self, other: _MassConstant, /) -> _MomentumConstant: ...
    def _rmul_Momentum_f[T: UnitSystem](
        self, other: Momentum[float, T], /
    ) -> Energy[float, T]: ...
    def _rmul_Momentum[W, T: UnitSystem](
        self, other: Momentum[W, T], /
    ) -> Energy[W, T]: ...
    def _cmul_Momentum(self, other: _MomentumConstant, /) -> _EnergyConstant: ...
    def _rtruediv_Length_f[T: UnitSystem](
        self, other: Length[float, T], /
    ) -> Time[float, T]: ...
    def _rtruediv_Length[W, T: UnitSystem](
        self, other: Length[W, T], /
    ) -> Time[W, T]: ...
    def _ctruediv_Length(self, other: _LengthConstant, /) -> _TimeConstant: ...
    def _rtruediv_Velocity_f[T: UnitSystem](
        self, other: Velocity[float, T], /
    ) -> Dimensionless[float, T]: ...
    def _rtruediv_Velocity[W, T: UnitSystem](
        self, other: Velocity[W, T], /
    ) -> Dimensionless[W, T]: ...
    def _ctruediv_Velocity(
        self, other: _VelocityConstant, /
    ) -> _DimensionlessConstant: ...
    def _rtruediv_Energy_f[T: UnitSystem](
        self, other: Energy[float, T], /
    ) -> Momentum[float, T]: ...
    def _rtruediv_Energy[W, T: UnitSystem](
        self, other: Energy[W, T], /
    ) -> Momentum[W, T]: ...
    def _ctruediv_Energy(self, other: _EnergyConstant, /) -> _MomentumConstant: ...
    def _rtruediv_Momentum_f[T: UnitSystem](
        self, other: Momentum[float, T], /
    ) -> Mass[float, T]: ...
    def _rtruediv_Momentum[W, T: UnitSystem](
        self, other: Momentum[W, T], /
    ) -> Mass[W, T]: ...
    def _ctruediv_Momentum(self, other: _MomentumConstant, /) -> _MassConstant: ...
    def _rtruediv_Acceleration_f[T: UnitSystem](
        self, other: Acceleration[float, T], /
    ) -> Frequency[float, T]: ...
    def _rtruediv_Acceleration[W, T: UnitSystem](
        self, other: Acceleration[W, T], /
    ) -> Frequency[W, T]: ...
    def _ctruediv_Acceleration(
        self, other: _AccelerationConstant, /
    ) -> _FrequencyConstant: ...
