# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Acceleration import _AccelerationConstant
from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.DipoleMoment import _DipoleMomentConstant
from quantype._generated import Acceleration, Dimensionless, DipoleMoment
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import (
    AccelerationKind,
    DimensionlessKind,
    DipoleMomentKind,
    Div,
    Mul,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class AccelerationPerDipoleMoment(
    Quantity[Div[AccelerationKind, DipoleMomentKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: AccelerationPerDipoleMoment[float, S], other: DipoleMoment[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __mul__(
        self,
        other: DipoleMoment[V, S] | DipoleMoment[float, S] | _DipoleMomentConstant,
        /,
    ) -> Acceleration[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> AccelerationPerDipoleMoment[V, S]: ...
    @overload
    def __mul__(
        self: AccelerationPerDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> AccelerationPerDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: AccelerationPerDipoleMoment[float, S], other: W, /
    ) -> AccelerationPerDipoleMoment[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> AccelerationPerDipoleMoment[V, S]: ...
    @overload
    def __mul__[K, W](
        self: AccelerationPerDipoleMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[AccelerationKind, DipoleMomentKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[AccelerationKind, DipoleMomentKind], K], V, S]: ...
    def _rmul_DipoleMoment_f(
        self, other: DipoleMoment[float, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    def _rmul_DipoleMoment[W](
        self: AccelerationPerDipoleMoment[float, S], other: DipoleMoment[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def _rmul_DipoleMoment(
        self, other: DipoleMoment[V, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: AccelerationPerDipoleMoment[float, S],
        other: AccelerationPerDipoleMoment[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: AccelerationPerDipoleMoment[V, S]
        | AccelerationPerDipoleMoment[float, S]
        | _AccelerationPerDipoleMomentConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> AccelerationPerDipoleMoment[V, S]: ...
    @overload
    def __truediv__(
        self: AccelerationPerDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> AccelerationPerDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: AccelerationPerDipoleMoment[float, S], other: W, /
    ) -> AccelerationPerDipoleMoment[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> AccelerationPerDipoleMoment[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: AccelerationPerDipoleMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[AccelerationKind, DipoleMomentKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[AccelerationKind, DipoleMomentKind], K], V, S]: ...
    def _rtruediv_Acceleration_f(
        self, other: Acceleration[float, S], /
    ) -> DipoleMoment[V, S]: ...
    @overload
    def _rtruediv_Acceleration[W](
        self: AccelerationPerDipoleMoment[float, S], other: Acceleration[W, S], /
    ) -> DipoleMoment[W, S]: ...
    @overload
    def _rtruediv_Acceleration(
        self, other: Acceleration[V, S], /
    ) -> DipoleMoment[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: AccelerationPerDipoleMoment[float, S], other: DipoleMoment[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __matmul__(
        self, other: DipoleMoment[V, S] | DipoleMoment[float, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    def __matmul__(
        self: AccelerationPerDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> AccelerationPerDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: AccelerationPerDipoleMoment[float, S], other: W, /
    ) -> AccelerationPerDipoleMoment[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> AccelerationPerDipoleMoment[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: AccelerationPerDipoleMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[AccelerationKind, DipoleMomentKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[AccelerationKind, DipoleMomentKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> AccelerationPerDipoleMoment[V, S]: ...
    @overload
    def __rmul__(
        self: AccelerationPerDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> AccelerationPerDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: AccelerationPerDipoleMoment[float, S], other: W, /
    ) -> AccelerationPerDipoleMoment[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> AccelerationPerDipoleMoment[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: AccelerationPerDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> AccelerationPerDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: AccelerationPerDipoleMoment[float, S], other: W, /
    ) -> AccelerationPerDipoleMoment[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> AccelerationPerDipoleMoment[V, S]: ...
    @override
    def item(self) -> AccelerationPerDipoleMoment[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[AccelerationKind, DipoleMomentKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: AccelerationPerDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[AccelerationKind, DipoleMomentKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: AccelerationPerDipoleMoment[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[AccelerationKind, DipoleMomentKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[AccelerationKind, DipoleMomentKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: AccelerationPerDipoleMoment[float, S],
        other: Quantity[Div[AccelerationKind, DipoleMomentKind], W, S],
        /,
    ) -> AccelerationPerDipoleMoment[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[AccelerationKind, DipoleMomentKind], V, S]
        | Quantity[Div[AccelerationKind, DipoleMomentKind], float, S],
        /,
    ) -> AccelerationPerDipoleMoment[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: AccelerationPerDipoleMoment[float, S],
        other: Quantity[Div[AccelerationKind, DipoleMomentKind], W, S],
        /,
    ) -> AccelerationPerDipoleMoment[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[AccelerationKind, DipoleMomentKind], V, S]
        | Quantity[Div[AccelerationKind, DipoleMomentKind], float, S],
        /,
    ) -> AccelerationPerDipoleMoment[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> AccelerationPerDipoleMoment[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> AccelerationPerDipoleMoment[W, S]: ...

class _AccelerationPerDipoleMomentConstant(
    Constant[Div[AccelerationKind, DipoleMomentKind]]
):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> AccelerationPerDipoleMoment[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[AccelerationKind, DipoleMomentKind]]
    ) -> AccelerationPerDipoleMoment[float]: ...
    @overload
    @override
    def __mul__(self, other: _DipoleMomentConstant, /) -> _AccelerationConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[AccelerationKind, DipoleMomentKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AccelerationPerDipoleMomentConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: DipoleMoment[W, T], /
    ) -> Acceleration[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[AccelerationKind, DipoleMomentKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _AccelerationPerDipoleMomentConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[AccelerationKind, DipoleMomentKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AccelerationPerDipoleMomentConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: AccelerationPerDipoleMoment[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[AccelerationKind, DipoleMomentKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AccelerationPerDipoleMomentConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[AccelerationKind, DipoleMomentKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[AccelerationKind, DipoleMomentKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[AccelerationKind, DipoleMomentKind]], W, T]: ...
    def _rmul_DipoleMoment_f[T: UnitSystem](
        self, other: DipoleMoment[float, T], /
    ) -> Acceleration[float, T]: ...
    def _rmul_DipoleMoment[W, T: UnitSystem](
        self, other: DipoleMoment[W, T], /
    ) -> Acceleration[W, T]: ...
    def _cmul_DipoleMoment(
        self, other: _DipoleMomentConstant, /
    ) -> _AccelerationConstant: ...
    def _rtruediv_Acceleration_f[T: UnitSystem](
        self, other: Acceleration[float, T], /
    ) -> DipoleMoment[float, T]: ...
    def _rtruediv_Acceleration[W, T: UnitSystem](
        self, other: Acceleration[W, T], /
    ) -> DipoleMoment[W, T]: ...
    def _ctruediv_Acceleration(
        self, other: _AccelerationConstant, /
    ) -> _DipoleMomentConstant: ...
