# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._constants.Pressure import _PressureConstant
from quantype._constants.Time import _TimeConstant
from quantype._constants.Volume import _VolumeConstant
from quantype._generated import (
    Action,
    Dimensionless,
    EnergyDensity,
    Frequency,
    InverseTime,
    Pressure,
    Time,
    Volume,
)
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import ActionKind, DimensionlessKind, Div, Mul, VolumeKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class ActionPerVolume(Quantity[Div[ActionKind, VolumeKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: ActionPerVolume[float, S], other: Volume[W, S], /
    ) -> Action[W, S]: ...
    @overload
    def __mul__(
        self, other: Volume[V, S] | Volume[float, S] | _VolumeConstant, /
    ) -> Action[V, S]: ...
    @overload
    def __mul__[W](
        self: ActionPerVolume[float, S], other: Frequency[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __mul__(
        self, other: Frequency[V, S] | Frequency[float, S] | _FrequencyConstant, /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __mul__[W](
        self: ActionPerVolume[float, S], other: InverseTime[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __mul__(
        self, other: InverseTime[V, S] | InverseTime[float, S] | _InverseTimeConstant, /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> ActionPerVolume[V, S]: ...
    @overload
    def __mul__(
        self: ActionPerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ActionPerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: ActionPerVolume[float, S], other: W, /
    ) -> ActionPerVolume[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> ActionPerVolume[V, S]: ...
    @overload
    def __mul__[K, W](
        self: ActionPerVolume[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ActionKind, VolumeKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ActionKind, VolumeKind], K], V, S]: ...
    def _rmul_Volume_f(self, other: Volume[float, S], /) -> Action[V, S]: ...
    @overload
    def _rmul_Volume[W](
        self: ActionPerVolume[float, S], other: Volume[W, S], /
    ) -> Action[W, S]: ...
    @overload
    def _rmul_Volume(self, other: Volume[V, S], /) -> Action[V, S]: ...
    def _rmul_Frequency_f(
        self, other: Frequency[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def _rmul_Frequency[W](
        self: ActionPerVolume[float, S], other: Frequency[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def _rmul_Frequency(self, other: Frequency[V, S], /) -> EnergyDensity[V, S]: ...
    def _rmul_InverseTime_f(
        self, other: InverseTime[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def _rmul_InverseTime[W](
        self: ActionPerVolume[float, S], other: InverseTime[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def _rmul_InverseTime(self, other: InverseTime[V, S], /) -> EnergyDensity[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: ActionPerVolume[float, S], other: Time[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __truediv__(
        self, other: Time[V, S] | Time[float, S] | _TimeConstant, /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __truediv__[W](
        self: ActionPerVolume[float, S], other: Pressure[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def __truediv__(
        self, other: Pressure[V, S] | Pressure[float, S] | _PressureConstant, /
    ) -> Time[V, S]: ...
    @overload
    def __truediv__[W](
        self: ActionPerVolume[float, S], other: ActionPerVolume[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: ActionPerVolume[V, S] | ActionPerVolume[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> ActionPerVolume[V, S]: ...
    @overload
    def __truediv__(
        self: ActionPerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ActionPerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: ActionPerVolume[float, S], other: W, /
    ) -> ActionPerVolume[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> ActionPerVolume[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: ActionPerVolume[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[ActionKind, VolumeKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[ActionKind, VolumeKind], K], V, S]: ...
    def _rtruediv_Pressure_f(
        self, other: Pressure[float, S], /
    ) -> InverseTime[V, S]: ...
    @overload
    def _rtruediv_Pressure[W](
        self: ActionPerVolume[float, S], other: Pressure[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def _rtruediv_Pressure(self, other: Pressure[V, S], /) -> InverseTime[V, S]: ...
    def _rtruediv_Action_f(self, other: Action[float, S], /) -> Volume[V, S]: ...
    @overload
    def _rtruediv_Action[W](
        self: ActionPerVolume[float, S], other: Action[W, S], /
    ) -> Volume[W, S]: ...
    @overload
    def _rtruediv_Action(self, other: Action[V, S], /) -> Volume[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: ActionPerVolume[float, S], other: Volume[W, S], /
    ) -> Action[W, S]: ...
    @overload
    def __matmul__(self, other: Volume[V, S] | Volume[float, S], /) -> Action[V, S]: ...
    @overload
    def __matmul__[W](
        self: ActionPerVolume[float, S], other: Frequency[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __matmul__(
        self, other: Frequency[V, S] | Frequency[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __matmul__[W](
        self: ActionPerVolume[float, S], other: InverseTime[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __matmul__(
        self, other: InverseTime[V, S] | InverseTime[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __matmul__(
        self: ActionPerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ActionPerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: ActionPerVolume[float, S], other: W, /
    ) -> ActionPerVolume[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> ActionPerVolume[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: ActionPerVolume[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ActionKind, VolumeKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ActionKind, VolumeKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> ActionPerVolume[V, S]: ...
    @overload
    def __rmul__(
        self: ActionPerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ActionPerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: ActionPerVolume[float, S], other: W, /
    ) -> ActionPerVolume[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> ActionPerVolume[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: ActionPerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ActionPerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: ActionPerVolume[float, S], other: W, /
    ) -> ActionPerVolume[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> ActionPerVolume[V, S]: ...
    @override
    def item(self) -> ActionPerVolume[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[ActionKind, VolumeKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: ActionPerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[ActionKind, VolumeKind]], npt.NDArray[np.float64], S
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: ActionPerVolume[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[ActionKind, VolumeKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[ActionKind, VolumeKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: ActionPerVolume[float, S],
        other: Quantity[Div[ActionKind, VolumeKind], W, S],
        /,
    ) -> ActionPerVolume[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[ActionKind, VolumeKind], V, S]
        | Quantity[Div[ActionKind, VolumeKind], float, S],
        /,
    ) -> ActionPerVolume[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: ActionPerVolume[float, S],
        other: Quantity[Div[ActionKind, VolumeKind], W, S],
        /,
    ) -> ActionPerVolume[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[ActionKind, VolumeKind], V, S]
        | Quantity[Div[ActionKind, VolumeKind], float, S],
        /,
    ) -> ActionPerVolume[V, S]: ...
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> ActionPerVolume[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> ActionPerVolume[W, S]: ...
