# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Area import _AreaConstant
from quantype._constants.AtomCount import _AtomCountConstant
from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.EnergyPerAtom import _EnergyPerAtomConstant
from quantype._constants.ForceConstant import _ForceConstantConstant
from quantype._generated import (
    Area,
    AtomCount,
    Dimensionless,
    EnergyPerAtom,
    ForceConstant,
)
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import AreaKind, DimensionlessKind, Div, EnergyPerAtomKind, Mul
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class AreaPerEnergyPerAtom(Quantity[Div[AreaKind, EnergyPerAtomKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: AreaPerEnergyPerAtom[float, S], other: EnergyPerAtom[W, S], /
    ) -> Area[W, S]: ...
    @overload
    def __mul__(
        self,
        other: EnergyPerAtom[V, S] | EnergyPerAtom[float, S] | _EnergyPerAtomConstant,
        /,
    ) -> Area[V, S]: ...
    @overload
    def __mul__[W](
        self: AreaPerEnergyPerAtom[float, S], other: ForceConstant[W, S], /
    ) -> AtomCount[W, S]: ...
    @overload
    def __mul__(
        self,
        other: ForceConstant[V, S] | ForceConstant[float, S] | _ForceConstantConstant,
        /,
    ) -> AtomCount[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> AreaPerEnergyPerAtom[V, S]: ...
    @overload
    def __mul__(
        self: AreaPerEnergyPerAtom[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AreaPerEnergyPerAtom[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: AreaPerEnergyPerAtom[float, S], other: W, /
    ) -> AreaPerEnergyPerAtom[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> AreaPerEnergyPerAtom[V, S]: ...
    @overload
    def __mul__[K, W](
        self: AreaPerEnergyPerAtom[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[AreaKind, EnergyPerAtomKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[AreaKind, EnergyPerAtomKind], K], V, S]: ...
    def _rmul_EnergyPerAtom_f(
        self, other: EnergyPerAtom[float, S], /
    ) -> Area[V, S]: ...
    @overload
    def _rmul_EnergyPerAtom[W](
        self: AreaPerEnergyPerAtom[float, S], other: EnergyPerAtom[W, S], /
    ) -> Area[W, S]: ...
    @overload
    def _rmul_EnergyPerAtom(self, other: EnergyPerAtom[V, S], /) -> Area[V, S]: ...
    def _rmul_ForceConstant_f(
        self, other: ForceConstant[float, S], /
    ) -> AtomCount[V, S]: ...
    @overload
    def _rmul_ForceConstant[W](
        self: AreaPerEnergyPerAtom[float, S], other: ForceConstant[W, S], /
    ) -> AtomCount[W, S]: ...
    @overload
    def _rmul_ForceConstant(self, other: ForceConstant[V, S], /) -> AtomCount[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: AreaPerEnergyPerAtom[float, S], other: AreaPerEnergyPerAtom[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: AreaPerEnergyPerAtom[V, S]
        | AreaPerEnergyPerAtom[float, S]
        | _AreaPerEnergyPerAtomConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> AreaPerEnergyPerAtom[V, S]: ...
    @overload
    def __truediv__(
        self: AreaPerEnergyPerAtom[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AreaPerEnergyPerAtom[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: AreaPerEnergyPerAtom[float, S], other: W, /
    ) -> AreaPerEnergyPerAtom[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> AreaPerEnergyPerAtom[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: AreaPerEnergyPerAtom[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[AreaKind, EnergyPerAtomKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[AreaKind, EnergyPerAtomKind], K], V, S]: ...
    def _rtruediv_Area_f(self, other: Area[float, S], /) -> EnergyPerAtom[V, S]: ...
    @overload
    def _rtruediv_Area[W](
        self: AreaPerEnergyPerAtom[float, S], other: Area[W, S], /
    ) -> EnergyPerAtom[W, S]: ...
    @overload
    def _rtruediv_Area(self, other: Area[V, S], /) -> EnergyPerAtom[V, S]: ...
    def _rtruediv_AtomCount_f(
        self, other: AtomCount[float, S], /
    ) -> ForceConstant[V, S]: ...
    @overload
    def _rtruediv_AtomCount[W](
        self: AreaPerEnergyPerAtom[float, S], other: AtomCount[W, S], /
    ) -> ForceConstant[W, S]: ...
    @overload
    def _rtruediv_AtomCount(self, other: AtomCount[V, S], /) -> ForceConstant[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: AreaPerEnergyPerAtom[float, S], other: EnergyPerAtom[W, S], /
    ) -> Area[W, S]: ...
    @overload
    def __matmul__(
        self, other: EnergyPerAtom[V, S] | EnergyPerAtom[float, S], /
    ) -> Area[V, S]: ...
    @overload
    def __matmul__[W](
        self: AreaPerEnergyPerAtom[float, S], other: ForceConstant[W, S], /
    ) -> AtomCount[W, S]: ...
    @overload
    def __matmul__(
        self, other: ForceConstant[V, S] | ForceConstant[float, S], /
    ) -> AtomCount[V, S]: ...
    @overload
    def __matmul__(
        self: AreaPerEnergyPerAtom[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AreaPerEnergyPerAtom[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: AreaPerEnergyPerAtom[float, S], other: W, /
    ) -> AreaPerEnergyPerAtom[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> AreaPerEnergyPerAtom[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: AreaPerEnergyPerAtom[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[AreaKind, EnergyPerAtomKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[AreaKind, EnergyPerAtomKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> AreaPerEnergyPerAtom[V, S]: ...
    @overload
    def __rmul__(
        self: AreaPerEnergyPerAtom[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AreaPerEnergyPerAtom[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: AreaPerEnergyPerAtom[float, S], other: W, /
    ) -> AreaPerEnergyPerAtom[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> AreaPerEnergyPerAtom[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: AreaPerEnergyPerAtom[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> AreaPerEnergyPerAtom[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: AreaPerEnergyPerAtom[float, S], other: W, /
    ) -> AreaPerEnergyPerAtom[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> AreaPerEnergyPerAtom[V, S]: ...
    @override
    def item(self) -> AreaPerEnergyPerAtom[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[AreaKind, EnergyPerAtomKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: AreaPerEnergyPerAtom[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[AreaKind, EnergyPerAtomKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: AreaPerEnergyPerAtom[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[AreaKind, EnergyPerAtomKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[AreaKind, EnergyPerAtomKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: AreaPerEnergyPerAtom[float, S],
        other: Quantity[Div[AreaKind, EnergyPerAtomKind], W, S],
        /,
    ) -> AreaPerEnergyPerAtom[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[AreaKind, EnergyPerAtomKind], V, S]
        | Quantity[Div[AreaKind, EnergyPerAtomKind], float, S],
        /,
    ) -> AreaPerEnergyPerAtom[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: AreaPerEnergyPerAtom[float, S],
        other: Quantity[Div[AreaKind, EnergyPerAtomKind], W, S],
        /,
    ) -> AreaPerEnergyPerAtom[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[AreaKind, EnergyPerAtomKind], V, S]
        | Quantity[Div[AreaKind, EnergyPerAtomKind], float, S],
        /,
    ) -> AreaPerEnergyPerAtom[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> AreaPerEnergyPerAtom[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> AreaPerEnergyPerAtom[W, S]: ...

class _AreaPerEnergyPerAtomConstant(Constant[Div[AreaKind, EnergyPerAtomKind]]):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> AreaPerEnergyPerAtom[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[AreaKind, EnergyPerAtomKind]]
    ) -> AreaPerEnergyPerAtom[float]: ...
    @overload
    @override
    def __mul__(self, other: _EnergyPerAtomConstant, /) -> _AreaConstant: ...
    @overload
    def __mul__(self, other: _ForceConstantConstant, /) -> _AtomCountConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[AreaKind, EnergyPerAtomKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AreaPerEnergyPerAtomConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: EnergyPerAtom[W, T], /
    ) -> Area[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: ForceConstant[W, T], /
    ) -> AtomCount[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[AreaKind, EnergyPerAtomKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _AreaPerEnergyPerAtomConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[AreaKind, EnergyPerAtomKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AreaPerEnergyPerAtomConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: AreaPerEnergyPerAtom[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[AreaKind, EnergyPerAtomKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _AreaPerEnergyPerAtomConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[AreaKind, EnergyPerAtomKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[AreaKind, EnergyPerAtomKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[AreaKind, EnergyPerAtomKind]], W, T]: ...
    def _rmul_EnergyPerAtom_f[T: UnitSystem](
        self, other: EnergyPerAtom[float, T], /
    ) -> Area[float, T]: ...
    def _rmul_EnergyPerAtom[W, T: UnitSystem](
        self, other: EnergyPerAtom[W, T], /
    ) -> Area[W, T]: ...
    def _cmul_EnergyPerAtom(
        self, other: _EnergyPerAtomConstant, /
    ) -> _AreaConstant: ...
    def _rmul_ForceConstant_f[T: UnitSystem](
        self, other: ForceConstant[float, T], /
    ) -> AtomCount[float, T]: ...
    def _rmul_ForceConstant[W, T: UnitSystem](
        self, other: ForceConstant[W, T], /
    ) -> AtomCount[W, T]: ...
    def _cmul_ForceConstant(
        self, other: _ForceConstantConstant, /
    ) -> _AtomCountConstant: ...
    def _rtruediv_Area_f[T: UnitSystem](
        self, other: Area[float, T], /
    ) -> EnergyPerAtom[float, T]: ...
    def _rtruediv_Area[W, T: UnitSystem](
        self, other: Area[W, T], /
    ) -> EnergyPerAtom[W, T]: ...
    def _ctruediv_Area(self, other: _AreaConstant, /) -> _EnergyPerAtomConstant: ...
    def _rtruediv_AtomCount_f[T: UnitSystem](
        self, other: AtomCount[float, T], /
    ) -> ForceConstant[float, T]: ...
    def _rtruediv_AtomCount[W, T: UnitSystem](
        self, other: AtomCount[W, T], /
    ) -> ForceConstant[W, T]: ...
    def _ctruediv_AtomCount(
        self, other: _AtomCountConstant, /
    ) -> _ForceConstantConstant: ...
