# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Charge import _ChargeConstant
from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._constants.Time import _TimeConstant
from quantype._generated import Charge, Dimensionless, Frequency, InverseTime, Time
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import ChargeKind, DimensionlessKind, Div, Mul, TimeKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class ChargePerTime(Quantity[Div[ChargeKind, TimeKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: ChargePerTime[float, S], other: Time[W, S], /
    ) -> Charge[W, S]: ...
    @overload
    def __mul__(
        self, other: Time[V, S] | Time[float, S] | _TimeConstant, /
    ) -> Charge[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> ChargePerTime[V, S]: ...
    @overload
    def __mul__(
        self: ChargePerTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: ChargePerTime[float, S], other: W, /
    ) -> ChargePerTime[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> ChargePerTime[V, S]: ...
    @overload
    def __mul__[K, W](
        self: ChargePerTime[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ChargeKind, TimeKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ChargeKind, TimeKind], K], V, S]: ...
    def _rmul_Time_f(self, other: Time[float, S], /) -> Charge[V, S]: ...
    @overload
    def _rmul_Time[W](
        self: ChargePerTime[float, S], other: Time[W, S], /
    ) -> Charge[W, S]: ...
    @overload
    def _rmul_Time(self, other: Time[V, S], /) -> Charge[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: ChargePerTime[float, S], other: Frequency[W, S], /
    ) -> Charge[W, S]: ...
    @overload
    def __truediv__(
        self, other: Frequency[V, S] | Frequency[float, S] | _FrequencyConstant, /
    ) -> Charge[V, S]: ...
    @overload
    def __truediv__[W](
        self: ChargePerTime[float, S], other: InverseTime[W, S], /
    ) -> Charge[W, S]: ...
    @overload
    def __truediv__(
        self, other: InverseTime[V, S] | InverseTime[float, S] | _InverseTimeConstant, /
    ) -> Charge[V, S]: ...
    @overload
    def __truediv__[W](
        self: ChargePerTime[float, S], other: Charge[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def __truediv__(
        self, other: Charge[V, S] | Charge[float, S] | _ChargeConstant, /
    ) -> InverseTime[V, S]: ...
    @overload
    def __truediv__[W](
        self: ChargePerTime[float, S], other: ChargePerTime[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ChargePerTime[V, S] | ChargePerTime[float, S] | _ChargePerTimeConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> ChargePerTime[V, S]: ...
    @overload
    def __truediv__(
        self: ChargePerTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: ChargePerTime[float, S], other: W, /
    ) -> ChargePerTime[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> ChargePerTime[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: ChargePerTime[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[ChargeKind, TimeKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[ChargeKind, TimeKind], K], V, S]: ...
    def _rtruediv_Charge_f(self, other: Charge[float, S], /) -> Time[V, S]: ...
    @overload
    def _rtruediv_Charge[W](
        self: ChargePerTime[float, S], other: Charge[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def _rtruediv_Charge(self, other: Charge[V, S], /) -> Time[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: ChargePerTime[float, S], other: Time[W, S], /
    ) -> Charge[W, S]: ...
    @overload
    def __matmul__(self, other: Time[V, S] | Time[float, S], /) -> Charge[V, S]: ...
    @overload
    def __matmul__(
        self: ChargePerTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: ChargePerTime[float, S], other: W, /
    ) -> ChargePerTime[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> ChargePerTime[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: ChargePerTime[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ChargeKind, TimeKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ChargeKind, TimeKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> ChargePerTime[V, S]: ...
    @overload
    def __rmul__(
        self: ChargePerTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: ChargePerTime[float, S], other: W, /
    ) -> ChargePerTime[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> ChargePerTime[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: ChargePerTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: ChargePerTime[float, S], other: W, /
    ) -> ChargePerTime[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> ChargePerTime[V, S]: ...
    @override
    def item(self) -> ChargePerTime[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[ChargeKind, TimeKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: ChargePerTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[ChargeKind, TimeKind]], npt.NDArray[np.float64], S
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: ChargePerTime[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[ChargeKind, TimeKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[ChargeKind, TimeKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: ChargePerTime[float, S],
        other: Quantity[Div[ChargeKind, TimeKind], W, S],
        /,
    ) -> ChargePerTime[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[ChargeKind, TimeKind], V, S]
        | Quantity[Div[ChargeKind, TimeKind], float, S],
        /,
    ) -> ChargePerTime[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: ChargePerTime[float, S],
        other: Quantity[Div[ChargeKind, TimeKind], W, S],
        /,
    ) -> ChargePerTime[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[ChargeKind, TimeKind], V, S]
        | Quantity[Div[ChargeKind, TimeKind], float, S],
        /,
    ) -> ChargePerTime[V, S]: ...
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> ChargePerTime[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> ChargePerTime[W, S]: ...

class _ChargePerTimeConstant(Constant[Div[ChargeKind, TimeKind]]):
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> ChargePerTime[float, T]: ...
    @override
    def to(self, unit: Unit[Div[ChargeKind, TimeKind]]) -> ChargePerTime[float]: ...
    @overload
    @override
    def __mul__(self, other: _TimeConstant, /) -> _ChargeConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[ChargeKind, TimeKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ChargePerTimeConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Time[W, T], /) -> Charge[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[ChargeKind, TimeKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(self, other: _FrequencyConstant, /) -> _ChargeConstant: ...
    @overload
    def __truediv__(self, other: _InverseTimeConstant, /) -> _ChargeConstant: ...
    @overload
    def __truediv__(self, other: _ChargeConstant, /) -> _InverseTimeConstant: ...
    @overload
    def __truediv__(
        self, other: _ChargePerTimeConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[ChargeKind, TimeKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ChargePerTimeConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Frequency[W, T], /
    ) -> Charge[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: InverseTime[W, T], /
    ) -> Charge[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Charge[W, T], /
    ) -> InverseTime[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: ChargePerTime[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[ChargeKind, TimeKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ChargePerTimeConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[ChargeKind, TimeKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[ChargeKind, TimeKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[ChargeKind, TimeKind]], W, T]: ...
    def _rmul_Time_f[T: UnitSystem](
        self, other: Time[float, T], /
    ) -> Charge[float, T]: ...
    def _rmul_Time[W, T: UnitSystem](self, other: Time[W, T], /) -> Charge[W, T]: ...
    def _cmul_Time(self, other: _TimeConstant, /) -> _ChargeConstant: ...
    def _rtruediv_Charge_f[T: UnitSystem](
        self, other: Charge[float, T], /
    ) -> Time[float, T]: ...
    def _rtruediv_Charge[W, T: UnitSystem](
        self, other: Charge[W, T], /
    ) -> Time[W, T]: ...
    def _ctruediv_Charge(self, other: _ChargeConstant, /) -> _TimeConstant: ...
