# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.ElectricPotential import _ElectricPotentialConstant
from quantype._constants.Volume import _VolumeConstant
from quantype._generated import (
    Charge,
    Dimensionless,
    ElectricPotential,
    EnergyDensity,
    Pressure,
    Volume,
)
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import ChargeKind, DimensionlessKind, Div, Mul, VolumeKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class ChargePerVolume(Quantity[Div[ChargeKind, VolumeKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: ChargePerVolume[float, S], other: Volume[W, S], /
    ) -> Charge[W, S]: ...
    @overload
    def __mul__(
        self, other: Volume[V, S] | Volume[float, S] | _VolumeConstant, /
    ) -> Charge[V, S]: ...
    @overload
    def __mul__[W](
        self: ChargePerVolume[float, S], other: ElectricPotential[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __mul__(
        self,
        other: ElectricPotential[V, S]
        | ElectricPotential[float, S]
        | _ElectricPotentialConstant,
        /,
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> ChargePerVolume[V, S]: ...
    @overload
    def __mul__(
        self: ChargePerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: ChargePerVolume[float, S], other: W, /
    ) -> ChargePerVolume[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> ChargePerVolume[V, S]: ...
    @overload
    def __mul__[K, W](
        self: ChargePerVolume[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ChargeKind, VolumeKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ChargeKind, VolumeKind], K], V, S]: ...
    def _rmul_Volume_f(self, other: Volume[float, S], /) -> Charge[V, S]: ...
    @overload
    def _rmul_Volume[W](
        self: ChargePerVolume[float, S], other: Volume[W, S], /
    ) -> Charge[W, S]: ...
    @overload
    def _rmul_Volume(self, other: Volume[V, S], /) -> Charge[V, S]: ...
    def _rmul_ElectricPotential_f(
        self, other: ElectricPotential[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def _rmul_ElectricPotential[W](
        self: ChargePerVolume[float, S], other: ElectricPotential[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def _rmul_ElectricPotential(
        self, other: ElectricPotential[V, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: ChargePerVolume[float, S], other: ChargePerVolume[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: ChargePerVolume[V, S] | ChargePerVolume[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> ChargePerVolume[V, S]: ...
    @overload
    def __truediv__(
        self: ChargePerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: ChargePerVolume[float, S], other: W, /
    ) -> ChargePerVolume[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> ChargePerVolume[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: ChargePerVolume[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[ChargeKind, VolumeKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[ChargeKind, VolumeKind], K], V, S]: ...
    def _rtruediv_Pressure_f(
        self, other: Pressure[float, S], /
    ) -> ElectricPotential[V, S]: ...
    @overload
    def _rtruediv_Pressure[W](
        self: ChargePerVolume[float, S], other: Pressure[W, S], /
    ) -> ElectricPotential[W, S]: ...
    @overload
    def _rtruediv_Pressure(
        self, other: Pressure[V, S], /
    ) -> ElectricPotential[V, S]: ...
    def _rtruediv_Charge_f(self, other: Charge[float, S], /) -> Volume[V, S]: ...
    @overload
    def _rtruediv_Charge[W](
        self: ChargePerVolume[float, S], other: Charge[W, S], /
    ) -> Volume[W, S]: ...
    @overload
    def _rtruediv_Charge(self, other: Charge[V, S], /) -> Volume[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: ChargePerVolume[float, S], other: Volume[W, S], /
    ) -> Charge[W, S]: ...
    @overload
    def __matmul__(self, other: Volume[V, S] | Volume[float, S], /) -> Charge[V, S]: ...
    @overload
    def __matmul__[W](
        self: ChargePerVolume[float, S], other: ElectricPotential[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __matmul__(
        self, other: ElectricPotential[V, S] | ElectricPotential[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __matmul__(
        self: ChargePerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: ChargePerVolume[float, S], other: W, /
    ) -> ChargePerVolume[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> ChargePerVolume[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: ChargePerVolume[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ChargeKind, VolumeKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ChargeKind, VolumeKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> ChargePerVolume[V, S]: ...
    @overload
    def __rmul__(
        self: ChargePerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: ChargePerVolume[float, S], other: W, /
    ) -> ChargePerVolume[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> ChargePerVolume[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: ChargePerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ChargePerVolume[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: ChargePerVolume[float, S], other: W, /
    ) -> ChargePerVolume[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> ChargePerVolume[V, S]: ...
    @override
    def item(self) -> ChargePerVolume[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[ChargeKind, VolumeKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: ChargePerVolume[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[ChargeKind, VolumeKind]], npt.NDArray[np.float64], S
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: ChargePerVolume[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[ChargeKind, VolumeKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[ChargeKind, VolumeKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: ChargePerVolume[float, S],
        other: Quantity[Div[ChargeKind, VolumeKind], W, S],
        /,
    ) -> ChargePerVolume[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[ChargeKind, VolumeKind], V, S]
        | Quantity[Div[ChargeKind, VolumeKind], float, S],
        /,
    ) -> ChargePerVolume[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: ChargePerVolume[float, S],
        other: Quantity[Div[ChargeKind, VolumeKind], W, S],
        /,
    ) -> ChargePerVolume[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[ChargeKind, VolumeKind], V, S]
        | Quantity[Div[ChargeKind, VolumeKind], float, S],
        /,
    ) -> ChargePerVolume[V, S]: ...
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> ChargePerVolume[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> ChargePerVolume[W, S]: ...
