# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.ElectricField import _ElectricFieldConstant
from quantype._constants.TemperatureRate import _TemperatureRateConstant
from quantype._generated import Dimensionless, ElectricField, TemperatureRate
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    ElectricFieldKind,
    Mul,
    TemperatureRateKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class ElectricFieldPerTemperatureRate(
    Quantity[Div[ElectricFieldKind, TemperatureRateKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: ElectricFieldPerTemperatureRate[float, S], other: TemperatureRate[W, S], /
    ) -> ElectricField[W, S]: ...
    @overload
    def __mul__(
        self,
        other: TemperatureRate[V, S]
        | TemperatureRate[float, S]
        | _TemperatureRateConstant,
        /,
    ) -> ElectricField[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @overload
    def __mul__(
        self: ElectricFieldPerTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> ElectricFieldPerTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: ElectricFieldPerTemperatureRate[float, S], other: W, /
    ) -> ElectricFieldPerTemperatureRate[W, S]: ...
    @overload
    def __mul__(
        self, other: _Numerical, /
    ) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @overload
    def __mul__[K, W](
        self: ElectricFieldPerTemperatureRate[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ElectricFieldKind, TemperatureRateKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ElectricFieldKind, TemperatureRateKind], K], V, S]: ...
    def _rmul_TemperatureRate_f(
        self, other: TemperatureRate[float, S], /
    ) -> ElectricField[V, S]: ...
    @overload
    def _rmul_TemperatureRate[W](
        self: ElectricFieldPerTemperatureRate[float, S], other: TemperatureRate[W, S], /
    ) -> ElectricField[W, S]: ...
    @overload
    def _rmul_TemperatureRate(
        self, other: TemperatureRate[V, S], /
    ) -> ElectricField[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: ElectricFieldPerTemperatureRate[float, S],
        other: ElectricFieldPerTemperatureRate[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ElectricFieldPerTemperatureRate[V, S]
        | ElectricFieldPerTemperatureRate[float, S]
        | _ElectricFieldPerTemperatureRateConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(
        self, other: _Scalar, /
    ) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @overload
    def __truediv__(
        self: ElectricFieldPerTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> ElectricFieldPerTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: ElectricFieldPerTemperatureRate[float, S], other: W, /
    ) -> ElectricFieldPerTemperatureRate[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: ElectricFieldPerTemperatureRate[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[ElectricFieldKind, TemperatureRateKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[ElectricFieldKind, TemperatureRateKind], K], V, S]: ...
    def _rtruediv_ElectricField_f(
        self, other: ElectricField[float, S], /
    ) -> TemperatureRate[V, S]: ...
    @overload
    def _rtruediv_ElectricField[W](
        self: ElectricFieldPerTemperatureRate[float, S], other: ElectricField[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def _rtruediv_ElectricField(
        self, other: ElectricField[V, S], /
    ) -> TemperatureRate[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: ElectricFieldPerTemperatureRate[float, S], other: TemperatureRate[W, S], /
    ) -> ElectricField[W, S]: ...
    @overload
    def __matmul__(
        self, other: TemperatureRate[V, S] | TemperatureRate[float, S], /
    ) -> ElectricField[V, S]: ...
    @overload
    def __matmul__(
        self: ElectricFieldPerTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> ElectricFieldPerTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: ElectricFieldPerTemperatureRate[float, S], other: W, /
    ) -> ElectricFieldPerTemperatureRate[W, S]: ...
    @overload
    def __matmul__(
        self, other: _Numerical, /
    ) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: ElectricFieldPerTemperatureRate[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ElectricFieldKind, TemperatureRateKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ElectricFieldKind, TemperatureRateKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @overload
    def __rmul__(
        self: ElectricFieldPerTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> ElectricFieldPerTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: ElectricFieldPerTemperatureRate[float, S], other: W, /
    ) -> ElectricFieldPerTemperatureRate[W, S]: ...
    @overload
    def __rmul__(
        self, other: _Numerical, /
    ) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: ElectricFieldPerTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> ElectricFieldPerTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: ElectricFieldPerTemperatureRate[float, S], other: W, /
    ) -> ElectricFieldPerTemperatureRate[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @override
    def item(self) -> ElectricFieldPerTemperatureRate[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[ElectricFieldKind, TemperatureRateKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: ElectricFieldPerTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[ElectricFieldKind, TemperatureRateKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: ElectricFieldPerTemperatureRate[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[ElectricFieldKind, TemperatureRateKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[ElectricFieldKind, TemperatureRateKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: ElectricFieldPerTemperatureRate[float, S],
        other: Quantity[Div[ElectricFieldKind, TemperatureRateKind], W, S],
        /,
    ) -> ElectricFieldPerTemperatureRate[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[ElectricFieldKind, TemperatureRateKind], V, S]
        | Quantity[Div[ElectricFieldKind, TemperatureRateKind], float, S],
        /,
    ) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: ElectricFieldPerTemperatureRate[float, S],
        other: Quantity[Div[ElectricFieldKind, TemperatureRateKind], W, S],
        /,
    ) -> ElectricFieldPerTemperatureRate[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[ElectricFieldKind, TemperatureRateKind], V, S]
        | Quantity[Div[ElectricFieldKind, TemperatureRateKind], float, S],
        /,
    ) -> ElectricFieldPerTemperatureRate[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> ElectricFieldPerTemperatureRate[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> ElectricFieldPerTemperatureRate[W, S]: ...

class _ElectricFieldPerTemperatureRateConstant(
    Constant[Div[ElectricFieldKind, TemperatureRateKind]]
):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> ElectricFieldPerTemperatureRate[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[ElectricFieldKind, TemperatureRateKind]]
    ) -> ElectricFieldPerTemperatureRate[float]: ...
    @overload
    @override
    def __mul__(self, other: _TemperatureRateConstant, /) -> _ElectricFieldConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[ElectricFieldKind, TemperatureRateKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ElectricFieldPerTemperatureRateConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: TemperatureRate[W, T], /
    ) -> ElectricField[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[ElectricFieldKind, TemperatureRateKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _ElectricFieldPerTemperatureRateConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[ElectricFieldKind, TemperatureRateKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ElectricFieldPerTemperatureRateConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: ElectricFieldPerTemperatureRate[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[ElectricFieldKind, TemperatureRateKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ElectricFieldPerTemperatureRateConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[ElectricFieldKind, TemperatureRateKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[
        Div[DimensionlessKind, Div[ElectricFieldKind, TemperatureRateKind]]
    ]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[ElectricFieldKind, TemperatureRateKind]], W, T]: ...
    def _rmul_TemperatureRate_f[T: UnitSystem](
        self, other: TemperatureRate[float, T], /
    ) -> ElectricField[float, T]: ...
    def _rmul_TemperatureRate[W, T: UnitSystem](
        self, other: TemperatureRate[W, T], /
    ) -> ElectricField[W, T]: ...
    def _cmul_TemperatureRate(
        self, other: _TemperatureRateConstant, /
    ) -> _ElectricFieldConstant: ...
    def _rtruediv_ElectricField_f[T: UnitSystem](
        self, other: ElectricField[float, T], /
    ) -> TemperatureRate[float, T]: ...
    def _rtruediv_ElectricField[W, T: UnitSystem](
        self, other: ElectricField[W, T], /
    ) -> TemperatureRate[W, T]: ...
    def _ctruediv_ElectricField(
        self, other: _ElectricFieldConstant, /
    ) -> _TemperatureRateConstant: ...
