# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.AtomCount import _AtomCountConstant
from quantype._constants.ElectronCount import _ElectronCountConstant
from quantype._constants.ElectronDensity import _ElectronDensityConstant
from quantype._constants.ParticleDensity import _ParticleDensityConstant
from quantype._generated import (
    AtomCount,
    Dimensionless,
    ElectronCount,
    ElectronDensity,
    ParticleDensity,
)
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    AtomCountKind,
    DimensionlessKind,
    Div,
    ElectronDensityKind,
    Mul,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class ElectronDensityAtomCount(Quantity[Mul[ElectronDensityKind, AtomCountKind], V, S]):
    @overload
    @override
    def __mul__(self, other: _Scalar, /) -> ElectronDensityAtomCount[V, S]: ...
    @overload
    def __mul__(
        self: ElectronDensityAtomCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ElectronDensityAtomCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: ElectronDensityAtomCount[float, S], other: W, /
    ) -> ElectronDensityAtomCount[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> ElectronDensityAtomCount[V, S]: ...
    @overload
    def __mul__[K, W](
        self: ElectronDensityAtomCount[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[ElectronDensityKind, AtomCountKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[ElectronDensityKind, AtomCountKind], K], V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: ElectronDensityAtomCount[float, S], other: ParticleDensity[W, S], /
    ) -> ElectronCount[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ParticleDensity[V, S]
        | ParticleDensity[float, S]
        | _ParticleDensityConstant,
        /,
    ) -> ElectronCount[V, S]: ...
    @overload
    def __truediv__[W](
        self: ElectronDensityAtomCount[float, S], other: ElectronDensity[W, S], /
    ) -> AtomCount[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ElectronDensity[V, S]
        | ElectronDensity[float, S]
        | _ElectronDensityConstant,
        /,
    ) -> AtomCount[V, S]: ...
    @overload
    def __truediv__[W](
        self: ElectronDensityAtomCount[float, S], other: AtomCount[W, S], /
    ) -> ElectronDensity[W, S]: ...
    @overload
    def __truediv__(
        self, other: AtomCount[V, S] | AtomCount[float, S] | _AtomCountConstant, /
    ) -> ElectronDensity[V, S]: ...
    @overload
    def __truediv__[W](
        self: ElectronDensityAtomCount[float, S], other: ElectronCount[W, S], /
    ) -> ParticleDensity[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ElectronCount[V, S] | ElectronCount[float, S] | _ElectronCountConstant,
        /,
    ) -> ParticleDensity[V, S]: ...
    @overload
    def __truediv__[W](
        self: ElectronDensityAtomCount[float, S],
        other: ElectronDensityAtomCount[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ElectronDensityAtomCount[V, S] | ElectronDensityAtomCount[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> ElectronDensityAtomCount[V, S]: ...
    @overload
    def __truediv__(
        self: ElectronDensityAtomCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ElectronDensityAtomCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: ElectronDensityAtomCount[float, S], other: W, /
    ) -> ElectronDensityAtomCount[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> ElectronDensityAtomCount[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: ElectronDensityAtomCount[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[ElectronDensityKind, AtomCountKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[ElectronDensityKind, AtomCountKind], K], V, S]: ...
    @overload
    @override
    def __matmul__(
        self: ElectronDensityAtomCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ElectronDensityAtomCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: ElectronDensityAtomCount[float, S], other: W, /
    ) -> ElectronDensityAtomCount[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> ElectronDensityAtomCount[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: ElectronDensityAtomCount[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[ElectronDensityKind, AtomCountKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[ElectronDensityKind, AtomCountKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> ElectronDensityAtomCount[V, S]: ...
    @overload
    def __rmul__(
        self: ElectronDensityAtomCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ElectronDensityAtomCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: ElectronDensityAtomCount[float, S], other: W, /
    ) -> ElectronDensityAtomCount[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> ElectronDensityAtomCount[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: ElectronDensityAtomCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ElectronDensityAtomCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: ElectronDensityAtomCount[float, S], other: W, /
    ) -> ElectronDensityAtomCount[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> ElectronDensityAtomCount[V, S]: ...
    @override
    def item(self) -> ElectronDensityAtomCount[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[ElectronDensityKind, AtomCountKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: ElectronDensityAtomCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[ElectronDensityKind, AtomCountKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: ElectronDensityAtomCount[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[ElectronDensityKind, AtomCountKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[ElectronDensityKind, AtomCountKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: ElectronDensityAtomCount[float, S],
        other: Quantity[Mul[ElectronDensityKind, AtomCountKind], W, S],
        /,
    ) -> ElectronDensityAtomCount[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[ElectronDensityKind, AtomCountKind], V, S]
        | Quantity[Mul[ElectronDensityKind, AtomCountKind], float, S],
        /,
    ) -> ElectronDensityAtomCount[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: ElectronDensityAtomCount[float, S],
        other: Quantity[Mul[ElectronDensityKind, AtomCountKind], W, S],
        /,
    ) -> ElectronDensityAtomCount[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[ElectronDensityKind, AtomCountKind], V, S]
        | Quantity[Mul[ElectronDensityKind, AtomCountKind], float, S],
        /,
    ) -> ElectronDensityAtomCount[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> ElectronDensityAtomCount[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> ElectronDensityAtomCount[W, S]: ...
