# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.AtomCount import _AtomCountConstant
from quantype._constants.Energy import _EnergyConstant
from quantype._generated import AtomCount, Dimensionless, Energy, EnergyPerAtom
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, EnergyKind, EnergyPerAtomKind, Mul
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class EnergyPerAtomPerEnergy(Quantity[Div[EnergyPerAtomKind, EnergyKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: EnergyPerAtomPerEnergy[float, S], other: Energy[W, S], /
    ) -> EnergyPerAtom[W, S]: ...
    @overload
    def __mul__(
        self, other: Energy[V, S] | Energy[float, S] | _EnergyConstant, /
    ) -> EnergyPerAtom[V, S]: ...
    @overload
    def __mul__[W](
        self: EnergyPerAtomPerEnergy[float, S], other: AtomCount[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __mul__(
        self, other: AtomCount[V, S] | AtomCount[float, S] | _AtomCountConstant, /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> EnergyPerAtomPerEnergy[V, S]: ...
    @overload
    def __mul__(
        self: EnergyPerAtomPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> EnergyPerAtomPerEnergy[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: EnergyPerAtomPerEnergy[float, S], other: W, /
    ) -> EnergyPerAtomPerEnergy[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> EnergyPerAtomPerEnergy[V, S]: ...
    @overload
    def __mul__[K, W](
        self: EnergyPerAtomPerEnergy[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[EnergyPerAtomKind, EnergyKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[EnergyPerAtomKind, EnergyKind], K], V, S]: ...
    def _rmul_Energy_f(self, other: Energy[float, S], /) -> EnergyPerAtom[V, S]: ...
    @overload
    def _rmul_Energy[W](
        self: EnergyPerAtomPerEnergy[float, S], other: Energy[W, S], /
    ) -> EnergyPerAtom[W, S]: ...
    @overload
    def _rmul_Energy(self, other: Energy[V, S], /) -> EnergyPerAtom[V, S]: ...
    def _rmul_AtomCount_f(
        self, other: AtomCount[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def _rmul_AtomCount[W](
        self: EnergyPerAtomPerEnergy[float, S], other: AtomCount[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def _rmul_AtomCount(self, other: AtomCount[V, S], /) -> Dimensionless[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: EnergyPerAtomPerEnergy[float, S], other: EnergyPerAtomPerEnergy[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: EnergyPerAtomPerEnergy[V, S] | EnergyPerAtomPerEnergy[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> EnergyPerAtomPerEnergy[V, S]: ...
    @overload
    def __truediv__(
        self: EnergyPerAtomPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> EnergyPerAtomPerEnergy[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: EnergyPerAtomPerEnergy[float, S], other: W, /
    ) -> EnergyPerAtomPerEnergy[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> EnergyPerAtomPerEnergy[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: EnergyPerAtomPerEnergy[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[EnergyPerAtomKind, EnergyKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[EnergyPerAtomKind, EnergyKind], K], V, S]: ...
    def _rtruediv_EnergyPerAtom_f(
        self, other: EnergyPerAtom[float, S], /
    ) -> Energy[V, S]: ...
    @overload
    def _rtruediv_EnergyPerAtom[W](
        self: EnergyPerAtomPerEnergy[float, S], other: EnergyPerAtom[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def _rtruediv_EnergyPerAtom(
        self, other: EnergyPerAtom[V, S], /
    ) -> Energy[V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> EnergyPerAtomPerEnergy[V, S]: ...
    @overload
    def __rmul__(
        self: EnergyPerAtomPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> EnergyPerAtomPerEnergy[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: EnergyPerAtomPerEnergy[float, S], other: W, /
    ) -> EnergyPerAtomPerEnergy[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> EnergyPerAtomPerEnergy[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[EnergyPerAtomKind, EnergyKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: EnergyPerAtomPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[EnergyPerAtomKind, EnergyKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: EnergyPerAtomPerEnergy[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[EnergyPerAtomKind, EnergyKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[EnergyPerAtomKind, EnergyKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: EnergyPerAtomPerEnergy[float, S],
        other: Quantity[Div[EnergyPerAtomKind, EnergyKind], W, S],
        /,
    ) -> EnergyPerAtomPerEnergy[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[EnergyPerAtomKind, EnergyKind], V, S]
        | Quantity[Div[EnergyPerAtomKind, EnergyKind], float, S],
        /,
    ) -> EnergyPerAtomPerEnergy[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: EnergyPerAtomPerEnergy[float, S],
        other: Quantity[Div[EnergyPerAtomKind, EnergyKind], W, S],
        /,
    ) -> EnergyPerAtomPerEnergy[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[EnergyPerAtomKind, EnergyKind], V, S]
        | Quantity[Div[EnergyPerAtomKind, EnergyKind], float, S],
        /,
    ) -> EnergyPerAtomPerEnergy[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyPerAtomPerEnergy[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> EnergyPerAtomPerEnergy[W, S]: ...
