# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.DipoleMoment import _DipoleMomentConstant
from quantype._constants.EnergyDensity import _EnergyDensityConstant
from quantype._generated import Dimensionless, DipoleMoment, EnergyDensity
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    DipoleMomentKind,
    Div,
    EnergyDensityKind,
    Mul,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class EnergyDensityDipoleMoment(
    Quantity[Mul[EnergyDensityKind, DipoleMomentKind], V, S]
):
    @overload
    @override
    def __mul__(self, other: _Scalar, /) -> EnergyDensityDipoleMoment[V, S]: ...
    @overload
    def __mul__(
        self: EnergyDensityDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: EnergyDensityDipoleMoment[float, S], other: W, /
    ) -> EnergyDensityDipoleMoment[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> EnergyDensityDipoleMoment[V, S]: ...
    @overload
    def __mul__[K, W](
        self: EnergyDensityDipoleMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, DipoleMomentKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, DipoleMomentKind], K], V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: EnergyDensityDipoleMoment[float, S], other: EnergyDensity[W, S], /
    ) -> DipoleMoment[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyDensity[V, S] | EnergyDensity[float, S] | _EnergyDensityConstant,
        /,
    ) -> DipoleMoment[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyDensityDipoleMoment[float, S], other: DipoleMoment[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: DipoleMoment[V, S] | DipoleMoment[float, S] | _DipoleMomentConstant,
        /,
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyDensityDipoleMoment[float, S],
        other: EnergyDensityDipoleMoment[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyDensityDipoleMoment[V, S] | EnergyDensityDipoleMoment[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> EnergyDensityDipoleMoment[V, S]: ...
    @overload
    def __truediv__(
        self: EnergyDensityDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: EnergyDensityDipoleMoment[float, S], other: W, /
    ) -> EnergyDensityDipoleMoment[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> EnergyDensityDipoleMoment[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: EnergyDensityDipoleMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[EnergyDensityKind, DipoleMomentKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[EnergyDensityKind, DipoleMomentKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> EnergyDensityDipoleMoment[V, S]: ...
    @overload
    def __rmul__(
        self: EnergyDensityDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: EnergyDensityDipoleMoment[float, S], other: W, /
    ) -> EnergyDensityDipoleMoment[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> EnergyDensityDipoleMoment[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, DipoleMomentKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: EnergyDensityDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, DipoleMomentKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: EnergyDensityDipoleMoment[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, DipoleMomentKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, DipoleMomentKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: EnergyDensityDipoleMoment[float, S],
        other: Quantity[Mul[EnergyDensityKind, DipoleMomentKind], W, S],
        /,
    ) -> EnergyDensityDipoleMoment[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[EnergyDensityKind, DipoleMomentKind], V, S]
        | Quantity[Mul[EnergyDensityKind, DipoleMomentKind], float, S],
        /,
    ) -> EnergyDensityDipoleMoment[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: EnergyDensityDipoleMoment[float, S],
        other: Quantity[Mul[EnergyDensityKind, DipoleMomentKind], W, S],
        /,
    ) -> EnergyDensityDipoleMoment[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[EnergyDensityKind, DipoleMomentKind], V, S]
        | Quantity[Mul[EnergyDensityKind, DipoleMomentKind], float, S],
        /,
    ) -> EnergyDensityDipoleMoment[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyDensityDipoleMoment[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> EnergyDensityDipoleMoment[W, S]: ...
