# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.ElectronDensity import _ElectronDensityConstant
from quantype._constants.EnergyDensity import _EnergyDensityConstant
from quantype._generated import Dimensionless, ElectronDensity, EnergyDensity
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    ElectronDensityKind,
    EnergyDensityKind,
    Mul,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class EnergyDensityElectronDensity(
    Quantity[Mul[EnergyDensityKind, ElectronDensityKind], V, S]
):
    @overload
    @override
    def __mul__(self, other: _Scalar, /) -> EnergyDensityElectronDensity[V, S]: ...
    @overload
    def __mul__(
        self: EnergyDensityElectronDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityElectronDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: EnergyDensityElectronDensity[float, S], other: W, /
    ) -> EnergyDensityElectronDensity[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> EnergyDensityElectronDensity[V, S]: ...
    @overload
    def __mul__[K, W](
        self: EnergyDensityElectronDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, ElectronDensityKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, ElectronDensityKind], K], V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: EnergyDensityElectronDensity[float, S], other: EnergyDensity[W, S], /
    ) -> ElectronDensity[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyDensity[V, S] | EnergyDensity[float, S] | _EnergyDensityConstant,
        /,
    ) -> ElectronDensity[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyDensityElectronDensity[float, S], other: ElectronDensity[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ElectronDensity[V, S]
        | ElectronDensity[float, S]
        | _ElectronDensityConstant,
        /,
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyDensityElectronDensity[float, S],
        other: EnergyDensityElectronDensity[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyDensityElectronDensity[V, S]
        | EnergyDensityElectronDensity[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> EnergyDensityElectronDensity[V, S]: ...
    @overload
    def __truediv__(
        self: EnergyDensityElectronDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityElectronDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: EnergyDensityElectronDensity[float, S], other: W, /
    ) -> EnergyDensityElectronDensity[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> EnergyDensityElectronDensity[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: EnergyDensityElectronDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[EnergyDensityKind, ElectronDensityKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[EnergyDensityKind, ElectronDensityKind], K], V, S]: ...
    @overload
    @override
    def __matmul__(
        self: EnergyDensityElectronDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityElectronDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: EnergyDensityElectronDensity[float, S], other: W, /
    ) -> EnergyDensityElectronDensity[W, S]: ...
    @overload
    def __matmul__(
        self, other: _Numerical, /
    ) -> EnergyDensityElectronDensity[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: EnergyDensityElectronDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, ElectronDensityKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, ElectronDensityKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> EnergyDensityElectronDensity[V, S]: ...
    @overload
    def __rmul__(
        self: EnergyDensityElectronDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityElectronDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: EnergyDensityElectronDensity[float, S], other: W, /
    ) -> EnergyDensityElectronDensity[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> EnergyDensityElectronDensity[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: EnergyDensityElectronDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityElectronDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: EnergyDensityElectronDensity[float, S], other: W, /
    ) -> EnergyDensityElectronDensity[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> EnergyDensityElectronDensity[V, S]: ...
    @override
    def item(self) -> EnergyDensityElectronDensity[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, ElectronDensityKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: EnergyDensityElectronDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, ElectronDensityKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: EnergyDensityElectronDensity[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, ElectronDensityKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, ElectronDensityKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: EnergyDensityElectronDensity[float, S],
        other: Quantity[Mul[EnergyDensityKind, ElectronDensityKind], W, S],
        /,
    ) -> EnergyDensityElectronDensity[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[EnergyDensityKind, ElectronDensityKind], V, S]
        | Quantity[Mul[EnergyDensityKind, ElectronDensityKind], float, S],
        /,
    ) -> EnergyDensityElectronDensity[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: EnergyDensityElectronDensity[float, S],
        other: Quantity[Mul[EnergyDensityKind, ElectronDensityKind], W, S],
        /,
    ) -> EnergyDensityElectronDensity[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[EnergyDensityKind, ElectronDensityKind], V, S]
        | Quantity[Mul[EnergyDensityKind, ElectronDensityKind], float, S],
        /,
    ) -> EnergyDensityElectronDensity[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyDensityElectronDensity[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> EnergyDensityElectronDensity[W, S]: ...
