# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.Energy import _EnergyConstant
from quantype._constants.EnergyPerAtom import _EnergyPerAtomConstant
from quantype._constants.ParticleDensity import _ParticleDensityConstant
from quantype._constants.Volume import _VolumeConstant
from quantype._generated import (
    Dimensionless,
    Energy,
    EnergyPerAtom,
    ParticleDensity,
    Volume,
)
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    EnergyPerAtomKind,
    Mul,
    ParticleDensityKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class EnergyPerAtomParticleDensity(
    Quantity[Mul[EnergyPerAtomKind, ParticleDensityKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: EnergyPerAtomParticleDensity[float, S], other: Volume[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def __mul__(
        self, other: Volume[V, S] | Volume[float, S] | _VolumeConstant, /
    ) -> Energy[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> EnergyPerAtomParticleDensity[V, S]: ...
    @overload
    def __mul__(
        self: EnergyPerAtomParticleDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerAtomParticleDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: EnergyPerAtomParticleDensity[float, S], other: W, /
    ) -> EnergyPerAtomParticleDensity[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> EnergyPerAtomParticleDensity[V, S]: ...
    @overload
    def __mul__[K, W](
        self: EnergyPerAtomParticleDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyPerAtomKind, ParticleDensityKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyPerAtomKind, ParticleDensityKind], K], V, S]: ...
    def _rmul_Volume_f(self, other: Volume[float, S], /) -> Energy[V, S]: ...
    @overload
    def _rmul_Volume[W](
        self: EnergyPerAtomParticleDensity[float, S], other: Volume[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def _rmul_Volume(self, other: Volume[V, S], /) -> Energy[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: EnergyPerAtomParticleDensity[float, S], other: EnergyPerAtom[W, S], /
    ) -> ParticleDensity[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyPerAtom[V, S] | EnergyPerAtom[float, S] | _EnergyPerAtomConstant,
        /,
    ) -> ParticleDensity[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyPerAtomParticleDensity[float, S], other: ParticleDensity[W, S], /
    ) -> EnergyPerAtom[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ParticleDensity[V, S]
        | ParticleDensity[float, S]
        | _ParticleDensityConstant,
        /,
    ) -> EnergyPerAtom[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyPerAtomParticleDensity[float, S],
        other: EnergyPerAtomParticleDensity[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyPerAtomParticleDensity[V, S]
        | EnergyPerAtomParticleDensity[float, S]
        | _EnergyPerAtomParticleDensityConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> EnergyPerAtomParticleDensity[V, S]: ...
    @overload
    def __truediv__(
        self: EnergyPerAtomParticleDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerAtomParticleDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: EnergyPerAtomParticleDensity[float, S], other: W, /
    ) -> EnergyPerAtomParticleDensity[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> EnergyPerAtomParticleDensity[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: EnergyPerAtomParticleDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[EnergyPerAtomKind, ParticleDensityKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[EnergyPerAtomKind, ParticleDensityKind], K], V, S]: ...
    def _rtruediv_Energy_f(self, other: Energy[float, S], /) -> Volume[V, S]: ...
    @overload
    def _rtruediv_Energy[W](
        self: EnergyPerAtomParticleDensity[float, S], other: Energy[W, S], /
    ) -> Volume[W, S]: ...
    @overload
    def _rtruediv_Energy(self, other: Energy[V, S], /) -> Volume[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: EnergyPerAtomParticleDensity[float, S], other: Volume[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def __matmul__(self, other: Volume[V, S] | Volume[float, S], /) -> Energy[V, S]: ...
    @overload
    def __matmul__(
        self: EnergyPerAtomParticleDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerAtomParticleDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: EnergyPerAtomParticleDensity[float, S], other: W, /
    ) -> EnergyPerAtomParticleDensity[W, S]: ...
    @overload
    def __matmul__(
        self, other: _Numerical, /
    ) -> EnergyPerAtomParticleDensity[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: EnergyPerAtomParticleDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyPerAtomKind, ParticleDensityKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyPerAtomKind, ParticleDensityKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> EnergyPerAtomParticleDensity[V, S]: ...
    @overload
    def __rmul__(
        self: EnergyPerAtomParticleDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerAtomParticleDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: EnergyPerAtomParticleDensity[float, S], other: W, /
    ) -> EnergyPerAtomParticleDensity[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> EnergyPerAtomParticleDensity[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: EnergyPerAtomParticleDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerAtomParticleDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: EnergyPerAtomParticleDensity[float, S], other: W, /
    ) -> EnergyPerAtomParticleDensity[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> EnergyPerAtomParticleDensity[V, S]: ...
    @override
    def item(self) -> EnergyPerAtomParticleDensity[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyPerAtomKind, ParticleDensityKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: EnergyPerAtomParticleDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyPerAtomKind, ParticleDensityKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: EnergyPerAtomParticleDensity[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyPerAtomKind, ParticleDensityKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyPerAtomKind, ParticleDensityKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: EnergyPerAtomParticleDensity[float, S],
        other: Quantity[Mul[EnergyPerAtomKind, ParticleDensityKind], W, S],
        /,
    ) -> EnergyPerAtomParticleDensity[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[EnergyPerAtomKind, ParticleDensityKind], V, S]
        | Quantity[Mul[EnergyPerAtomKind, ParticleDensityKind], float, S],
        /,
    ) -> EnergyPerAtomParticleDensity[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: EnergyPerAtomParticleDensity[float, S],
        other: Quantity[Mul[EnergyPerAtomKind, ParticleDensityKind], W, S],
        /,
    ) -> EnergyPerAtomParticleDensity[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[EnergyPerAtomKind, ParticleDensityKind], V, S]
        | Quantity[Mul[EnergyPerAtomKind, ParticleDensityKind], float, S],
        /,
    ) -> EnergyPerAtomParticleDensity[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyPerAtomParticleDensity[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> EnergyPerAtomParticleDensity[W, S]: ...

class _EnergyPerAtomParticleDensityConstant(
    Constant[Mul[EnergyPerAtomKind, ParticleDensityKind]]
):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyPerAtomParticleDensity[float, T]: ...
    @override
    def to(
        self, unit: Unit[Mul[EnergyPerAtomKind, ParticleDensityKind]]
    ) -> EnergyPerAtomParticleDensity[float]: ...
    @overload
    @override
    def __mul__(self, other: _VolumeConstant, /) -> _EnergyConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Mul[EnergyPerAtomKind, ParticleDensityKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyPerAtomParticleDensityConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Volume[W, T], /) -> Energy[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Mul[EnergyPerAtomKind, ParticleDensityKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _EnergyPerAtomConstant, /
    ) -> _ParticleDensityConstant: ...
    @overload
    def __truediv__(
        self, other: _ParticleDensityConstant, /
    ) -> _EnergyPerAtomConstant: ...
    @overload
    def __truediv__(
        self, other: _EnergyPerAtomParticleDensityConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Mul[EnergyPerAtomKind, ParticleDensityKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyPerAtomParticleDensityConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: EnergyPerAtom[W, T], /
    ) -> ParticleDensity[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: ParticleDensity[W, T], /
    ) -> EnergyPerAtom[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: EnergyPerAtomParticleDensity[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Mul[EnergyPerAtomKind, ParticleDensityKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyPerAtomParticleDensityConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Mul[EnergyPerAtomKind, ParticleDensityKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[
        Div[DimensionlessKind, Mul[EnergyPerAtomKind, ParticleDensityKind]]
    ]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Mul[EnergyPerAtomKind, ParticleDensityKind]], W, T]: ...
    def _rmul_Volume_f[T: UnitSystem](
        self, other: Volume[float, T], /
    ) -> Energy[float, T]: ...
    def _rmul_Volume[W, T: UnitSystem](
        self, other: Volume[W, T], /
    ) -> Energy[W, T]: ...
    def _cmul_Volume(self, other: _VolumeConstant, /) -> _EnergyConstant: ...
    def _rtruediv_Energy_f[T: UnitSystem](
        self, other: Energy[float, T], /
    ) -> Volume[float, T]: ...
    def _rtruediv_Energy[W, T: UnitSystem](
        self, other: Energy[W, T], /
    ) -> Volume[W, T]: ...
    def _ctruediv_Energy(self, other: _EnergyConstant, /) -> _VolumeConstant: ...
