# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Velocity import _VelocityConstant
from quantype._generated import Dimensionless, EnergyPerVolume, Velocity
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    EnergyPerVolumeKind,
    Mul,
    VelocityKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class EnergyPerVolumePerVelocity(
    Quantity[Div[EnergyPerVolumeKind, VelocityKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: EnergyPerVolumePerVelocity[float, S], other: Velocity[W, S], /
    ) -> EnergyPerVolume[W, S]: ...
    @overload
    def __mul__(
        self, other: Velocity[V, S] | Velocity[float, S] | _VelocityConstant, /
    ) -> EnergyPerVolume[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> EnergyPerVolumePerVelocity[V, S]: ...
    @overload
    def __mul__(
        self: EnergyPerVolumePerVelocity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerVolumePerVelocity[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: EnergyPerVolumePerVelocity[float, S], other: W, /
    ) -> EnergyPerVolumePerVelocity[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> EnergyPerVolumePerVelocity[V, S]: ...
    @overload
    def __mul__[K, W](
        self: EnergyPerVolumePerVelocity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[EnergyPerVolumeKind, VelocityKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[EnergyPerVolumeKind, VelocityKind], K], V, S]: ...
    def _rmul_Velocity_f(
        self, other: Velocity[float, S], /
    ) -> EnergyPerVolume[V, S]: ...
    @overload
    def _rmul_Velocity[W](
        self: EnergyPerVolumePerVelocity[float, S], other: Velocity[W, S], /
    ) -> EnergyPerVolume[W, S]: ...
    @overload
    def _rmul_Velocity(self, other: Velocity[V, S], /) -> EnergyPerVolume[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: EnergyPerVolumePerVelocity[float, S],
        other: EnergyPerVolumePerVelocity[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyPerVolumePerVelocity[V, S] | EnergyPerVolumePerVelocity[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> EnergyPerVolumePerVelocity[V, S]: ...
    @overload
    def __truediv__(
        self: EnergyPerVolumePerVelocity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerVolumePerVelocity[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: EnergyPerVolumePerVelocity[float, S], other: W, /
    ) -> EnergyPerVolumePerVelocity[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> EnergyPerVolumePerVelocity[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: EnergyPerVolumePerVelocity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[EnergyPerVolumeKind, VelocityKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[EnergyPerVolumeKind, VelocityKind], K], V, S]: ...
    def _rtruediv_EnergyPerVolume_f(
        self, other: EnergyPerVolume[float, S], /
    ) -> Velocity[V, S]: ...
    @overload
    def _rtruediv_EnergyPerVolume[W](
        self: EnergyPerVolumePerVelocity[float, S], other: EnergyPerVolume[W, S], /
    ) -> Velocity[W, S]: ...
    @overload
    def _rtruediv_EnergyPerVolume(
        self, other: EnergyPerVolume[V, S], /
    ) -> Velocity[V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> EnergyPerVolumePerVelocity[V, S]: ...
    @overload
    def __rmul__(
        self: EnergyPerVolumePerVelocity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerVolumePerVelocity[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: EnergyPerVolumePerVelocity[float, S], other: W, /
    ) -> EnergyPerVolumePerVelocity[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> EnergyPerVolumePerVelocity[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[EnergyPerVolumeKind, VelocityKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: EnergyPerVolumePerVelocity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[EnergyPerVolumeKind, VelocityKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: EnergyPerVolumePerVelocity[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[EnergyPerVolumeKind, VelocityKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[EnergyPerVolumeKind, VelocityKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: EnergyPerVolumePerVelocity[float, S],
        other: Quantity[Div[EnergyPerVolumeKind, VelocityKind], W, S],
        /,
    ) -> EnergyPerVolumePerVelocity[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[EnergyPerVolumeKind, VelocityKind], V, S]
        | Quantity[Div[EnergyPerVolumeKind, VelocityKind], float, S],
        /,
    ) -> EnergyPerVolumePerVelocity[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: EnergyPerVolumePerVelocity[float, S],
        other: Quantity[Div[EnergyPerVolumeKind, VelocityKind], W, S],
        /,
    ) -> EnergyPerVolumePerVelocity[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[EnergyPerVolumeKind, VelocityKind], V, S]
        | Quantity[Div[EnergyPerVolumeKind, VelocityKind], float, S],
        /,
    ) -> EnergyPerVolumePerVelocity[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyPerVolumePerVelocity[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> EnergyPerVolumePerVelocity[W, S]: ...
