# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.ElectricPotential import _ElectricPotentialConstant
from quantype._constants.EnergyPerVolume import _EnergyPerVolumeConstant
from quantype._generated import Dimensionless, ElectricPotential, EnergyPerVolume
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    ElectricPotentialKind,
    EnergyPerVolumeKind,
    Mul,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class EnergyPerVolumeElectricPotential(
    Quantity[Mul[EnergyPerVolumeKind, ElectricPotentialKind], V, S]
):
    @overload
    @override
    def __mul__(self, other: _Scalar, /) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @overload
    def __mul__(
        self: EnergyPerVolumeElectricPotential[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerVolumeElectricPotential[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: EnergyPerVolumeElectricPotential[float, S], other: W, /
    ) -> EnergyPerVolumeElectricPotential[W, S]: ...
    @overload
    def __mul__(
        self, other: _Numerical, /
    ) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @overload
    def __mul__[K, W](
        self: EnergyPerVolumeElectricPotential[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyPerVolumeKind, ElectricPotentialKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyPerVolumeKind, ElectricPotentialKind], K], V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: EnergyPerVolumeElectricPotential[float, S],
        other: EnergyPerVolume[W, S],
        /,
    ) -> ElectricPotential[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyPerVolume[V, S]
        | EnergyPerVolume[float, S]
        | _EnergyPerVolumeConstant,
        /,
    ) -> ElectricPotential[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyPerVolumeElectricPotential[float, S],
        other: ElectricPotential[W, S],
        /,
    ) -> EnergyPerVolume[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ElectricPotential[V, S]
        | ElectricPotential[float, S]
        | _ElectricPotentialConstant,
        /,
    ) -> EnergyPerVolume[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyPerVolumeElectricPotential[float, S],
        other: EnergyPerVolumeElectricPotential[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyPerVolumeElectricPotential[V, S]
        | EnergyPerVolumeElectricPotential[float, S]
        | _EnergyPerVolumeElectricPotentialConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(
        self, other: _Scalar, /
    ) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @overload
    def __truediv__(
        self: EnergyPerVolumeElectricPotential[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerVolumeElectricPotential[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: EnergyPerVolumeElectricPotential[float, S], other: W, /
    ) -> EnergyPerVolumeElectricPotential[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: EnergyPerVolumeElectricPotential[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[EnergyPerVolumeKind, ElectricPotentialKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[EnergyPerVolumeKind, ElectricPotentialKind], K], V, S]: ...
    @overload
    @override
    def __matmul__(
        self: EnergyPerVolumeElectricPotential[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerVolumeElectricPotential[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: EnergyPerVolumeElectricPotential[float, S], other: W, /
    ) -> EnergyPerVolumeElectricPotential[W, S]: ...
    @overload
    def __matmul__(
        self, other: _Numerical, /
    ) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: EnergyPerVolumeElectricPotential[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyPerVolumeKind, ElectricPotentialKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyPerVolumeKind, ElectricPotentialKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @overload
    def __rmul__(
        self: EnergyPerVolumeElectricPotential[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerVolumeElectricPotential[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: EnergyPerVolumeElectricPotential[float, S], other: W, /
    ) -> EnergyPerVolumeElectricPotential[W, S]: ...
    @overload
    def __rmul__(
        self, other: _Numerical, /
    ) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: EnergyPerVolumeElectricPotential[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyPerVolumeElectricPotential[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: EnergyPerVolumeElectricPotential[float, S], other: W, /
    ) -> EnergyPerVolumeElectricPotential[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @override
    def item(self) -> EnergyPerVolumeElectricPotential[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyPerVolumeKind, ElectricPotentialKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: EnergyPerVolumeElectricPotential[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyPerVolumeKind, ElectricPotentialKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: EnergyPerVolumeElectricPotential[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyPerVolumeKind, ElectricPotentialKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyPerVolumeKind, ElectricPotentialKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: EnergyPerVolumeElectricPotential[float, S],
        other: Quantity[Mul[EnergyPerVolumeKind, ElectricPotentialKind], W, S],
        /,
    ) -> EnergyPerVolumeElectricPotential[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[EnergyPerVolumeKind, ElectricPotentialKind], V, S]
        | Quantity[Mul[EnergyPerVolumeKind, ElectricPotentialKind], float, S],
        /,
    ) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: EnergyPerVolumeElectricPotential[float, S],
        other: Quantity[Mul[EnergyPerVolumeKind, ElectricPotentialKind], W, S],
        /,
    ) -> EnergyPerVolumeElectricPotential[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[EnergyPerVolumeKind, ElectricPotentialKind], V, S]
        | Quantity[Mul[EnergyPerVolumeKind, ElectricPotentialKind], float, S],
        /,
    ) -> EnergyPerVolumeElectricPotential[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyPerVolumeElectricPotential[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> EnergyPerVolumeElectricPotential[W, S]: ...

class _EnergyPerVolumeElectricPotentialConstant(
    Constant[Mul[EnergyPerVolumeKind, ElectricPotentialKind]]
):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyPerVolumeElectricPotential[float, T]: ...
    @override
    def to(
        self, unit: Unit[Mul[EnergyPerVolumeKind, ElectricPotentialKind]]
    ) -> EnergyPerVolumeElectricPotential[float]: ...
    @overload
    @override
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Mul[EnergyPerVolumeKind, ElectricPotentialKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyPerVolumeElectricPotentialConstant: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Mul[EnergyPerVolumeKind, ElectricPotentialKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _EnergyPerVolumeConstant, /
    ) -> _ElectricPotentialConstant: ...
    @overload
    def __truediv__(
        self, other: _ElectricPotentialConstant, /
    ) -> _EnergyPerVolumeConstant: ...
    @overload
    def __truediv__(
        self, other: _EnergyPerVolumeElectricPotentialConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Mul[EnergyPerVolumeKind, ElectricPotentialKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyPerVolumeElectricPotentialConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: EnergyPerVolume[W, T], /
    ) -> ElectricPotential[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: ElectricPotential[W, T], /
    ) -> EnergyPerVolume[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: EnergyPerVolumeElectricPotential[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Mul[EnergyPerVolumeKind, ElectricPotentialKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyPerVolumeElectricPotentialConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Mul[EnergyPerVolumeKind, ElectricPotentialKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[
        Div[DimensionlessKind, Mul[EnergyPerVolumeKind, ElectricPotentialKind]]
    ]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Mul[EnergyPerVolumeKind, ElectricPotentialKind]], W, T]: ...
