# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.EnergyDensity import _EnergyDensityConstant
from quantype._constants.TemperatureRate import _TemperatureRateConstant
from quantype._generated import Dimensionless, EnergyDensity, TemperatureRate
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    EnergyDensityKind,
    Mul,
    TemperatureRateKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class EnergyDensityTemperatureRate(
    Quantity[Mul[EnergyDensityKind, TemperatureRateKind], V, S]
):
    @overload
    @override
    def __mul__(self, other: _Scalar, /) -> EnergyDensityTemperatureRate[V, S]: ...
    @overload
    def __mul__(
        self: EnergyDensityTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: EnergyDensityTemperatureRate[float, S], other: W, /
    ) -> EnergyDensityTemperatureRate[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> EnergyDensityTemperatureRate[V, S]: ...
    @overload
    def __mul__[K, W](
        self: EnergyDensityTemperatureRate[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, TemperatureRateKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, TemperatureRateKind], K], V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: EnergyDensityTemperatureRate[float, S], other: EnergyDensity[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyDensity[V, S] | EnergyDensity[float, S] | _EnergyDensityConstant,
        /,
    ) -> TemperatureRate[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyDensityTemperatureRate[float, S], other: TemperatureRate[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: TemperatureRate[V, S]
        | TemperatureRate[float, S]
        | _TemperatureRateConstant,
        /,
    ) -> EnergyDensity[V, S]: ...
    @overload
    def __truediv__[W](
        self: EnergyDensityTemperatureRate[float, S],
        other: EnergyDensityTemperatureRate[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: EnergyDensityTemperatureRate[V, S]
        | EnergyDensityTemperatureRate[float, S]
        | _EnergyDensityTemperatureRateConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> EnergyDensityTemperatureRate[V, S]: ...
    @overload
    def __truediv__(
        self: EnergyDensityTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: EnergyDensityTemperatureRate[float, S], other: W, /
    ) -> EnergyDensityTemperatureRate[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> EnergyDensityTemperatureRate[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: EnergyDensityTemperatureRate[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[EnergyDensityKind, TemperatureRateKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[EnergyDensityKind, TemperatureRateKind], K], V, S]: ...
    @overload
    @override
    def __matmul__(
        self: EnergyDensityTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: EnergyDensityTemperatureRate[float, S], other: W, /
    ) -> EnergyDensityTemperatureRate[W, S]: ...
    @overload
    def __matmul__(
        self, other: _Numerical, /
    ) -> EnergyDensityTemperatureRate[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: EnergyDensityTemperatureRate[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, TemperatureRateKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, TemperatureRateKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> EnergyDensityTemperatureRate[V, S]: ...
    @overload
    def __rmul__(
        self: EnergyDensityTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: EnergyDensityTemperatureRate[float, S], other: W, /
    ) -> EnergyDensityTemperatureRate[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> EnergyDensityTemperatureRate[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: EnergyDensityTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> EnergyDensityTemperatureRate[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: EnergyDensityTemperatureRate[float, S], other: W, /
    ) -> EnergyDensityTemperatureRate[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> EnergyDensityTemperatureRate[V, S]: ...
    @override
    def item(self) -> EnergyDensityTemperatureRate[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, TemperatureRateKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: EnergyDensityTemperatureRate[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, TemperatureRateKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: EnergyDensityTemperatureRate[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, TemperatureRateKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[EnergyDensityKind, TemperatureRateKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: EnergyDensityTemperatureRate[float, S],
        other: Quantity[Mul[EnergyDensityKind, TemperatureRateKind], W, S],
        /,
    ) -> EnergyDensityTemperatureRate[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[EnergyDensityKind, TemperatureRateKind], V, S]
        | Quantity[Mul[EnergyDensityKind, TemperatureRateKind], float, S],
        /,
    ) -> EnergyDensityTemperatureRate[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: EnergyDensityTemperatureRate[float, S],
        other: Quantity[Mul[EnergyDensityKind, TemperatureRateKind], W, S],
        /,
    ) -> EnergyDensityTemperatureRate[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[EnergyDensityKind, TemperatureRateKind], V, S]
        | Quantity[Mul[EnergyDensityKind, TemperatureRateKind], float, S],
        /,
    ) -> EnergyDensityTemperatureRate[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyDensityTemperatureRate[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> EnergyDensityTemperatureRate[W, S]: ...

class _EnergyDensityTemperatureRateConstant(
    Constant[Mul[EnergyDensityKind, TemperatureRateKind]]
):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> EnergyDensityTemperatureRate[float, T]: ...
    @override
    def to(
        self, unit: Unit[Mul[EnergyDensityKind, TemperatureRateKind]]
    ) -> EnergyDensityTemperatureRate[float]: ...
    @overload
    @override
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Mul[EnergyDensityKind, TemperatureRateKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyDensityTemperatureRateConstant: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Mul[EnergyDensityKind, TemperatureRateKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _EnergyDensityConstant, /
    ) -> _TemperatureRateConstant: ...
    @overload
    def __truediv__(
        self, other: _TemperatureRateConstant, /
    ) -> _EnergyDensityConstant: ...
    @overload
    def __truediv__(
        self, other: _EnergyDensityTemperatureRateConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Mul[EnergyDensityKind, TemperatureRateKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyDensityTemperatureRateConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: EnergyDensity[W, T], /
    ) -> TemperatureRate[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: TemperatureRate[W, T], /
    ) -> EnergyDensity[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: EnergyDensityTemperatureRate[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Mul[EnergyDensityKind, TemperatureRateKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _EnergyDensityTemperatureRateConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Mul[EnergyDensityKind, TemperatureRateKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[
        Div[DimensionlessKind, Mul[EnergyDensityKind, TemperatureRateKind]]
    ]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Mul[EnergyDensityKind, TemperatureRateKind]], W, T]: ...
