# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Length import _LengthConstant
from quantype._constants.Temperature import _TemperatureConstant
from quantype._generated import Dimensionless, Entropy, Force, Length, Temperature
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, ForceKind, Mul, TemperatureKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class ForcePerTemperature(Quantity[Div[ForceKind, TemperatureKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: ForcePerTemperature[float, S], other: Length[W, S], /
    ) -> Entropy[W, S]: ...
    @overload
    def __mul__(
        self, other: Length[V, S] | Length[float, S] | _LengthConstant, /
    ) -> Entropy[V, S]: ...
    @overload
    def __mul__[W](
        self: ForcePerTemperature[float, S], other: Temperature[W, S], /
    ) -> Force[W, S]: ...
    @overload
    def __mul__(
        self, other: Temperature[V, S] | Temperature[float, S] | _TemperatureConstant, /
    ) -> Force[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> ForcePerTemperature[V, S]: ...
    @overload
    def __mul__(
        self: ForcePerTemperature[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForcePerTemperature[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: ForcePerTemperature[float, S], other: W, /
    ) -> ForcePerTemperature[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> ForcePerTemperature[V, S]: ...
    @overload
    def __mul__[K, W](
        self: ForcePerTemperature[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[ForceKind, TemperatureKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[ForceKind, TemperatureKind], K], V, S]: ...
    def _rmul_Length_f(self, other: Length[float, S], /) -> Entropy[V, S]: ...
    @overload
    def _rmul_Length[W](
        self: ForcePerTemperature[float, S], other: Length[W, S], /
    ) -> Entropy[W, S]: ...
    @overload
    def _rmul_Length(self, other: Length[V, S], /) -> Entropy[V, S]: ...
    def _rmul_Temperature_f(self, other: Temperature[float, S], /) -> Force[V, S]: ...
    @overload
    def _rmul_Temperature[W](
        self: ForcePerTemperature[float, S], other: Temperature[W, S], /
    ) -> Force[W, S]: ...
    @overload
    def _rmul_Temperature(self, other: Temperature[V, S], /) -> Force[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: ForcePerTemperature[float, S], other: ForcePerTemperature[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: ForcePerTemperature[V, S] | ForcePerTemperature[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> ForcePerTemperature[V, S]: ...
    @overload
    def __truediv__(
        self: ForcePerTemperature[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForcePerTemperature[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: ForcePerTemperature[float, S], other: W, /
    ) -> ForcePerTemperature[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> ForcePerTemperature[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: ForcePerTemperature[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[ForceKind, TemperatureKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[ForceKind, TemperatureKind], K], V, S]: ...
    def _rtruediv_Force_f(self, other: Force[float, S], /) -> Temperature[V, S]: ...
    @overload
    def _rtruediv_Force[W](
        self: ForcePerTemperature[float, S], other: Force[W, S], /
    ) -> Temperature[W, S]: ...
    @overload
    def _rtruediv_Force(self, other: Force[V, S], /) -> Temperature[V, S]: ...
    def _rtruediv_Entropy_f(self, other: Entropy[float, S], /) -> Length[V, S]: ...
    @overload
    def _rtruediv_Entropy[W](
        self: ForcePerTemperature[float, S], other: Entropy[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def _rtruediv_Entropy(self, other: Entropy[V, S], /) -> Length[V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> ForcePerTemperature[V, S]: ...
    @overload
    def __rmul__(
        self: ForcePerTemperature[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForcePerTemperature[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: ForcePerTemperature[float, S], other: W, /
    ) -> ForcePerTemperature[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> ForcePerTemperature[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[ForceKind, TemperatureKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: ForcePerTemperature[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[ForceKind, TemperatureKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: ForcePerTemperature[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[ForceKind, TemperatureKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[ForceKind, TemperatureKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: ForcePerTemperature[float, S],
        other: Quantity[Div[ForceKind, TemperatureKind], W, S],
        /,
    ) -> ForcePerTemperature[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[ForceKind, TemperatureKind], V, S]
        | Quantity[Div[ForceKind, TemperatureKind], float, S],
        /,
    ) -> ForcePerTemperature[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: ForcePerTemperature[float, S],
        other: Quantity[Div[ForceKind, TemperatureKind], W, S],
        /,
    ) -> ForcePerTemperature[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[ForceKind, TemperatureKind], V, S]
        | Quantity[Div[ForceKind, TemperatureKind], float, S],
        /,
    ) -> ForcePerTemperature[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> ForcePerTemperature[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> ForcePerTemperature[W, S]: ...
