# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
from typing import Any, Literal, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.ForceConstant import _ForceConstantConstant
from quantype._generated import Dimensionless, ForceConstant
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, ForceConstantKind, Mul, Pow
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class ForceConstantSquared(Quantity[Pow[ForceConstantKind, Literal[2]], V, S]):
    @overload
    @override
    def __mul__(self, other: _Scalar, /) -> ForceConstantSquared[V, S]: ...
    @overload
    def __mul__(
        self: ForceConstantSquared[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceConstantSquared[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: ForceConstantSquared[float, S], other: W, /
    ) -> ForceConstantSquared[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> ForceConstantSquared[V, S]: ...
    @overload
    def __mul__[K, W](
        self: ForceConstantSquared[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Pow[ForceConstantKind, Literal[2]], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Pow[ForceConstantKind, Literal[2]], K], V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: ForceConstantSquared[float, S], other: ForceConstant[W, S], /
    ) -> ForceConstant[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ForceConstant[V, S] | ForceConstant[float, S] | _ForceConstantConstant,
        /,
    ) -> ForceConstant[V, S]: ...
    @overload
    def __truediv__[W](
        self: ForceConstantSquared[float, S], other: ForceConstantSquared[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: ForceConstantSquared[V, S] | ForceConstantSquared[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> ForceConstantSquared[V, S]: ...
    @overload
    def __truediv__(
        self: ForceConstantSquared[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceConstantSquared[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: ForceConstantSquared[float, S], other: W, /
    ) -> ForceConstantSquared[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> ForceConstantSquared[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: ForceConstantSquared[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Pow[ForceConstantKind, Literal[2]], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Pow[ForceConstantKind, Literal[2]], K], V, S]: ...
    @overload
    @override
    def __matmul__(
        self: ForceConstantSquared[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceConstantSquared[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: ForceConstantSquared[float, S], other: W, /
    ) -> ForceConstantSquared[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> ForceConstantSquared[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: ForceConstantSquared[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Pow[ForceConstantKind, Literal[2]], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Pow[ForceConstantKind, Literal[2]], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> ForceConstantSquared[V, S]: ...
    @overload
    def __rmul__(
        self: ForceConstantSquared[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceConstantSquared[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: ForceConstantSquared[float, S], other: W, /
    ) -> ForceConstantSquared[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> ForceConstantSquared[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: ForceConstantSquared[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceConstantSquared[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: ForceConstantSquared[float, S], other: W, /
    ) -> ForceConstantSquared[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> ForceConstantSquared[V, S]: ...
    @override
    def item(self) -> ForceConstantSquared[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Pow[ForceConstantKind, Literal[2]]], V, S]: ...
    @overload
    def __rtruediv__(
        self: ForceConstantSquared[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Pow[ForceConstantKind, Literal[2]]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: ForceConstantSquared[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Pow[ForceConstantKind, Literal[2]]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Pow[ForceConstantKind, Literal[2]]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: ForceConstantSquared[float, S],
        other: Quantity[Pow[ForceConstantKind, Literal[2]], W, S],
        /,
    ) -> ForceConstantSquared[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Pow[ForceConstantKind, Literal[2]], V, S]
        | Quantity[Pow[ForceConstantKind, Literal[2]], float, S],
        /,
    ) -> ForceConstantSquared[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: ForceConstantSquared[float, S],
        other: Quantity[Pow[ForceConstantKind, Literal[2]], W, S],
        /,
    ) -> ForceConstantSquared[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Pow[ForceConstantKind, Literal[2]], V, S]
        | Quantity[Pow[ForceConstantKind, Literal[2]], float, S],
        /,
    ) -> ForceConstantSquared[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> ForceConstantSquared[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> ForceConstantSquared[W, S]: ...
