# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.Force import _ForceConstant
from quantype._constants.ForceConstant import _ForceConstantConstant
from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._constants.Time import _TimeConstant
from quantype._constants.Velocity import _VelocityConstant
from quantype._generated import (
    Dimensionless,
    Force,
    ForceConstant,
    Frequency,
    InverseTime,
    Time,
    Velocity,
)
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import DimensionlessKind, Div, ForceKind, FrequencyKind, Mul
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class ForceFrequency(Quantity[Mul[ForceKind, FrequencyKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: ForceFrequency[float, S], other: Time[W, S], /
    ) -> Force[W, S]: ...
    @overload
    def __mul__(
        self, other: Time[V, S] | Time[float, S] | _TimeConstant, /
    ) -> Force[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> ForceFrequency[V, S]: ...
    @overload
    def __mul__(
        self: ForceFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: ForceFrequency[float, S], other: W, /
    ) -> ForceFrequency[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> ForceFrequency[V, S]: ...
    @overload
    def __mul__[K, W](
        self: ForceFrequency[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[ForceKind, FrequencyKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[ForceKind, FrequencyKind], K], V, S]: ...
    def _rmul_Time_f(self, other: Time[float, S], /) -> Force[V, S]: ...
    @overload
    def _rmul_Time[W](
        self: ForceFrequency[float, S], other: Time[W, S], /
    ) -> Force[W, S]: ...
    @overload
    def _rmul_Time(self, other: Time[V, S], /) -> Force[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: ForceFrequency[float, S], other: Velocity[W, S], /
    ) -> ForceConstant[W, S]: ...
    @overload
    def __truediv__(
        self, other: Velocity[V, S] | Velocity[float, S] | _VelocityConstant, /
    ) -> ForceConstant[V, S]: ...
    @overload
    def __truediv__[W](
        self: ForceFrequency[float, S], other: Force[W, S], /
    ) -> Frequency[W, S]: ...
    @overload
    def __truediv__(
        self, other: Force[V, S] | Force[float, S] | _ForceConstant, /
    ) -> Frequency[V, S]: ...
    @overload
    def __truediv__[W](
        self: ForceFrequency[float, S], other: ForceConstant[W, S], /
    ) -> Velocity[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ForceConstant[V, S] | ForceConstant[float, S] | _ForceConstantConstant,
        /,
    ) -> Velocity[V, S]: ...
    @overload
    def __truediv__[W](
        self: ForceFrequency[float, S], other: Frequency[W, S], /
    ) -> Force[W, S]: ...
    @overload
    def __truediv__(
        self, other: Frequency[V, S] | Frequency[float, S] | _FrequencyConstant, /
    ) -> Force[V, S]: ...
    @overload
    def __truediv__[W](
        self: ForceFrequency[float, S], other: InverseTime[W, S], /
    ) -> Force[W, S]: ...
    @overload
    def __truediv__(
        self, other: InverseTime[V, S] | InverseTime[float, S] | _InverseTimeConstant, /
    ) -> Force[V, S]: ...
    @overload
    def __truediv__[W](
        self: ForceFrequency[float, S], other: ForceFrequency[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ForceFrequency[V, S]
        | ForceFrequency[float, S]
        | _ForceFrequencyConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> ForceFrequency[V, S]: ...
    @overload
    def __truediv__(
        self: ForceFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: ForceFrequency[float, S], other: W, /
    ) -> ForceFrequency[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> ForceFrequency[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: ForceFrequency[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[ForceKind, FrequencyKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[ForceKind, FrequencyKind], K], V, S]: ...
    def _rtruediv_Force_f(self, other: Force[float, S], /) -> Time[V, S]: ...
    @overload
    def _rtruediv_Force[W](
        self: ForceFrequency[float, S], other: Force[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def _rtruediv_Force(self, other: Force[V, S], /) -> Time[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: ForceFrequency[float, S], other: Time[W, S], /
    ) -> Force[W, S]: ...
    @overload
    def __matmul__(self, other: Time[V, S] | Time[float, S], /) -> Force[V, S]: ...
    @overload
    def __matmul__(
        self: ForceFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: ForceFrequency[float, S], other: W, /
    ) -> ForceFrequency[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> ForceFrequency[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: ForceFrequency[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[ForceKind, FrequencyKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[ForceKind, FrequencyKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> ForceFrequency[V, S]: ...
    @overload
    def __rmul__(
        self: ForceFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: ForceFrequency[float, S], other: W, /
    ) -> ForceFrequency[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> ForceFrequency[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: ForceFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> ForceFrequency[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: ForceFrequency[float, S], other: W, /
    ) -> ForceFrequency[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> ForceFrequency[V, S]: ...
    @override
    def item(self) -> ForceFrequency[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Mul[ForceKind, FrequencyKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: ForceFrequency[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[ForceKind, FrequencyKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: ForceFrequency[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Mul[ForceKind, FrequencyKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Mul[ForceKind, FrequencyKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: ForceFrequency[float, S],
        other: Quantity[Mul[ForceKind, FrequencyKind], W, S],
        /,
    ) -> ForceFrequency[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[ForceKind, FrequencyKind], V, S]
        | Quantity[Mul[ForceKind, FrequencyKind], float, S],
        /,
    ) -> ForceFrequency[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: ForceFrequency[float, S],
        other: Quantity[Mul[ForceKind, FrequencyKind], W, S],
        /,
    ) -> ForceFrequency[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[ForceKind, FrequencyKind], V, S]
        | Quantity[Mul[ForceKind, FrequencyKind], float, S],
        /,
    ) -> ForceFrequency[V, S]: ...
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> ForceFrequency[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> ForceFrequency[W, S]: ...

class _ForceFrequencyConstant(Constant[Mul[ForceKind, FrequencyKind]]):
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> ForceFrequency[float, T]: ...
    @override
    def to(
        self, unit: Unit[Mul[ForceKind, FrequencyKind]]
    ) -> ForceFrequency[float]: ...
    @overload
    @override
    def __mul__(self, other: _TimeConstant, /) -> _ForceConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Mul[ForceKind, FrequencyKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ForceFrequencyConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Time[W, T], /) -> Force[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Mul[ForceKind, FrequencyKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(self, other: _VelocityConstant, /) -> _ForceConstantConstant: ...
    @overload
    def __truediv__(self, other: _ForceConstant, /) -> _FrequencyConstant: ...
    @overload
    def __truediv__(self, other: _ForceConstantConstant, /) -> _VelocityConstant: ...
    @overload
    def __truediv__(self, other: _FrequencyConstant, /) -> _ForceConstant: ...
    @overload
    def __truediv__(self, other: _InverseTimeConstant, /) -> _ForceConstant: ...
    @overload
    def __truediv__(
        self, other: _ForceFrequencyConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Mul[ForceKind, FrequencyKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ForceFrequencyConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Velocity[W, T], /
    ) -> ForceConstant[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Force[W, T], /
    ) -> Frequency[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: ForceConstant[W, T], /
    ) -> Velocity[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: Frequency[W, T], /
    ) -> Force[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: InverseTime[W, T], /
    ) -> Force[W, T]: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: ForceFrequency[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Mul[ForceKind, FrequencyKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _ForceFrequencyConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Mul[ForceKind, FrequencyKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Mul[ForceKind, FrequencyKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Mul[ForceKind, FrequencyKind]], W, T]: ...
    def _rmul_Time_f[T: UnitSystem](
        self, other: Time[float, T], /
    ) -> Force[float, T]: ...
    def _rmul_Time[W, T: UnitSystem](self, other: Time[W, T], /) -> Force[W, T]: ...
    def _cmul_Time(self, other: _TimeConstant, /) -> _ForceConstant: ...
    def _rtruediv_Force_f[T: UnitSystem](
        self, other: Force[float, T], /
    ) -> Time[float, T]: ...
    def _rtruediv_Force[W, T: UnitSystem](
        self, other: Force[W, T], /
    ) -> Time[W, T]: ...
    def _ctruediv_Force(self, other: _ForceConstant, /) -> _TimeConstant: ...
