# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.EnergyDensity import _EnergyDensityConstant
from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._generated import Dimensionless, EnergyDensity, Frequency, InverseTime
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import DimensionlessKind, Div, EnergyDensityKind, FrequencyKind, Mul
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class FrequencyPerEnergyDensity(Quantity[Div[FrequencyKind, EnergyDensityKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: FrequencyPerEnergyDensity[float, S], other: EnergyDensity[W, S], /
    ) -> Frequency[W, S]: ...
    @overload
    def __mul__(
        self,
        other: EnergyDensity[V, S] | EnergyDensity[float, S] | _EnergyDensityConstant,
        /,
    ) -> Frequency[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> FrequencyPerEnergyDensity[V, S]: ...
    @overload
    def __mul__(
        self: FrequencyPerEnergyDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> FrequencyPerEnergyDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: FrequencyPerEnergyDensity[float, S], other: W, /
    ) -> FrequencyPerEnergyDensity[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> FrequencyPerEnergyDensity[V, S]: ...
    @overload
    def __mul__[K, W](
        self: FrequencyPerEnergyDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[FrequencyKind, EnergyDensityKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[FrequencyKind, EnergyDensityKind], K], V, S]: ...
    def _rmul_EnergyDensity_f(
        self, other: EnergyDensity[float, S], /
    ) -> Frequency[V, S]: ...
    @overload
    def _rmul_EnergyDensity[W](
        self: FrequencyPerEnergyDensity[float, S], other: EnergyDensity[W, S], /
    ) -> Frequency[W, S]: ...
    @overload
    def _rmul_EnergyDensity(self, other: EnergyDensity[V, S], /) -> Frequency[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: FrequencyPerEnergyDensity[float, S],
        other: FrequencyPerEnergyDensity[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: FrequencyPerEnergyDensity[V, S]
        | FrequencyPerEnergyDensity[float, S]
        | _FrequencyPerEnergyDensityConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> FrequencyPerEnergyDensity[V, S]: ...
    @overload
    def __truediv__(
        self: FrequencyPerEnergyDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> FrequencyPerEnergyDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: FrequencyPerEnergyDensity[float, S], other: W, /
    ) -> FrequencyPerEnergyDensity[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> FrequencyPerEnergyDensity[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: FrequencyPerEnergyDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[FrequencyKind, EnergyDensityKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[FrequencyKind, EnergyDensityKind], K], V, S]: ...
    def _rtruediv_Frequency_f(
        self, other: Frequency[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def _rtruediv_Frequency[W](
        self: FrequencyPerEnergyDensity[float, S], other: Frequency[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def _rtruediv_Frequency(self, other: Frequency[V, S], /) -> EnergyDensity[V, S]: ...
    def _rtruediv_InverseTime_f(
        self, other: InverseTime[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def _rtruediv_InverseTime[W](
        self: FrequencyPerEnergyDensity[float, S], other: InverseTime[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def _rtruediv_InverseTime(
        self, other: InverseTime[V, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: FrequencyPerEnergyDensity[float, S], other: EnergyDensity[W, S], /
    ) -> Frequency[W, S]: ...
    @overload
    def __matmul__(
        self, other: EnergyDensity[V, S] | EnergyDensity[float, S], /
    ) -> Frequency[V, S]: ...
    @overload
    def __matmul__(
        self: FrequencyPerEnergyDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> FrequencyPerEnergyDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: FrequencyPerEnergyDensity[float, S], other: W, /
    ) -> FrequencyPerEnergyDensity[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> FrequencyPerEnergyDensity[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: FrequencyPerEnergyDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[FrequencyKind, EnergyDensityKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[FrequencyKind, EnergyDensityKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> FrequencyPerEnergyDensity[V, S]: ...
    @overload
    def __rmul__(
        self: FrequencyPerEnergyDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> FrequencyPerEnergyDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: FrequencyPerEnergyDensity[float, S], other: W, /
    ) -> FrequencyPerEnergyDensity[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> FrequencyPerEnergyDensity[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: FrequencyPerEnergyDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> FrequencyPerEnergyDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: FrequencyPerEnergyDensity[float, S], other: W, /
    ) -> FrequencyPerEnergyDensity[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> FrequencyPerEnergyDensity[V, S]: ...
    @override
    def item(self) -> FrequencyPerEnergyDensity[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[FrequencyKind, EnergyDensityKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: FrequencyPerEnergyDensity[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[FrequencyKind, EnergyDensityKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: FrequencyPerEnergyDensity[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[FrequencyKind, EnergyDensityKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[FrequencyKind, EnergyDensityKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: FrequencyPerEnergyDensity[float, S],
        other: Quantity[Div[FrequencyKind, EnergyDensityKind], W, S],
        /,
    ) -> FrequencyPerEnergyDensity[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[FrequencyKind, EnergyDensityKind], V, S]
        | Quantity[Div[FrequencyKind, EnergyDensityKind], float, S],
        /,
    ) -> FrequencyPerEnergyDensity[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: FrequencyPerEnergyDensity[float, S],
        other: Quantity[Div[FrequencyKind, EnergyDensityKind], W, S],
        /,
    ) -> FrequencyPerEnergyDensity[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[FrequencyKind, EnergyDensityKind], V, S]
        | Quantity[Div[FrequencyKind, EnergyDensityKind], float, S],
        /,
    ) -> FrequencyPerEnergyDensity[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> FrequencyPerEnergyDensity[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> FrequencyPerEnergyDensity[W, S]: ...

class _FrequencyPerEnergyDensityConstant(
    Constant[Div[FrequencyKind, EnergyDensityKind]]
):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> FrequencyPerEnergyDensity[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[FrequencyKind, EnergyDensityKind]]
    ) -> FrequencyPerEnergyDensity[float]: ...
    @overload
    @override
    def __mul__(self, other: _EnergyDensityConstant, /) -> _FrequencyConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[FrequencyKind, EnergyDensityKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _FrequencyPerEnergyDensityConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: EnergyDensity[W, T], /
    ) -> Frequency[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[FrequencyKind, EnergyDensityKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _FrequencyPerEnergyDensityConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[FrequencyKind, EnergyDensityKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _FrequencyPerEnergyDensityConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: FrequencyPerEnergyDensity[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[FrequencyKind, EnergyDensityKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _FrequencyPerEnergyDensityConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[FrequencyKind, EnergyDensityKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[FrequencyKind, EnergyDensityKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[FrequencyKind, EnergyDensityKind]], W, T]: ...
    def _rmul_EnergyDensity_f[T: UnitSystem](
        self, other: EnergyDensity[float, T], /
    ) -> Frequency[float, T]: ...
    def _rmul_EnergyDensity[W, T: UnitSystem](
        self, other: EnergyDensity[W, T], /
    ) -> Frequency[W, T]: ...
    def _cmul_EnergyDensity(
        self, other: _EnergyDensityConstant, /
    ) -> _FrequencyConstant: ...
    def _rtruediv_Frequency_f[T: UnitSystem](
        self, other: Frequency[float, T], /
    ) -> EnergyDensity[float, T]: ...
    def _rtruediv_Frequency[W, T: UnitSystem](
        self, other: Frequency[W, T], /
    ) -> EnergyDensity[W, T]: ...
    def _ctruediv_Frequency(
        self, other: _FrequencyConstant, /
    ) -> _EnergyDensityConstant: ...
    def _rtruediv_InverseTime_f[T: UnitSystem](
        self, other: InverseTime[float, T], /
    ) -> EnergyDensity[float, T]: ...
    def _rtruediv_InverseTime[W, T: UnitSystem](
        self, other: InverseTime[W, T], /
    ) -> EnergyDensity[W, T]: ...
    def _ctruediv_InverseTime(
        self, other: _InverseTimeConstant, /
    ) -> _EnergyDensityConstant: ...
