# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.MagneticMoment import _MagneticMomentConstant
from quantype._generated import Dimensionless, Frequency, InverseTime, MagneticMoment
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    InverseTimeKind,
    MagneticMomentKind,
    Mul,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class InverseTimePerMagneticMoment(
    Quantity[Div[InverseTimeKind, MagneticMomentKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: InverseTimePerMagneticMoment[float, S], other: MagneticMoment[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def __mul__(
        self,
        other: MagneticMoment[V, S]
        | MagneticMoment[float, S]
        | _MagneticMomentConstant,
        /,
    ) -> InverseTime[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> InverseTimePerMagneticMoment[V, S]: ...
    @overload
    def __mul__(
        self: InverseTimePerMagneticMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> InverseTimePerMagneticMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: InverseTimePerMagneticMoment[float, S], other: W, /
    ) -> InverseTimePerMagneticMoment[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> InverseTimePerMagneticMoment[V, S]: ...
    @overload
    def __mul__[K, W](
        self: InverseTimePerMagneticMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[InverseTimeKind, MagneticMomentKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[InverseTimeKind, MagneticMomentKind], K], V, S]: ...
    def _rmul_MagneticMoment_f(
        self, other: MagneticMoment[float, S], /
    ) -> InverseTime[V, S]: ...
    @overload
    def _rmul_MagneticMoment[W](
        self: InverseTimePerMagneticMoment[float, S], other: MagneticMoment[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def _rmul_MagneticMoment(
        self, other: MagneticMoment[V, S], /
    ) -> InverseTime[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: InverseTimePerMagneticMoment[float, S],
        other: InverseTimePerMagneticMoment[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: InverseTimePerMagneticMoment[V, S]
        | InverseTimePerMagneticMoment[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> InverseTimePerMagneticMoment[V, S]: ...
    @overload
    def __truediv__(
        self: InverseTimePerMagneticMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> InverseTimePerMagneticMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: InverseTimePerMagneticMoment[float, S], other: W, /
    ) -> InverseTimePerMagneticMoment[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> InverseTimePerMagneticMoment[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: InverseTimePerMagneticMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[InverseTimeKind, MagneticMomentKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[InverseTimeKind, MagneticMomentKind], K], V, S]: ...
    def _rtruediv_Frequency_f(
        self, other: Frequency[float, S], /
    ) -> MagneticMoment[V, S]: ...
    @overload
    def _rtruediv_Frequency[W](
        self: InverseTimePerMagneticMoment[float, S], other: Frequency[W, S], /
    ) -> MagneticMoment[W, S]: ...
    @overload
    def _rtruediv_Frequency(
        self, other: Frequency[V, S], /
    ) -> MagneticMoment[V, S]: ...
    def _rtruediv_InverseTime_f(
        self, other: InverseTime[float, S], /
    ) -> MagneticMoment[V, S]: ...
    @overload
    def _rtruediv_InverseTime[W](
        self: InverseTimePerMagneticMoment[float, S], other: InverseTime[W, S], /
    ) -> MagneticMoment[W, S]: ...
    @overload
    def _rtruediv_InverseTime(
        self, other: InverseTime[V, S], /
    ) -> MagneticMoment[V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> InverseTimePerMagneticMoment[V, S]: ...
    @overload
    def __rmul__(
        self: InverseTimePerMagneticMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> InverseTimePerMagneticMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: InverseTimePerMagneticMoment[float, S], other: W, /
    ) -> InverseTimePerMagneticMoment[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> InverseTimePerMagneticMoment[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[InverseTimeKind, MagneticMomentKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: InverseTimePerMagneticMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[InverseTimeKind, MagneticMomentKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: InverseTimePerMagneticMoment[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[InverseTimeKind, MagneticMomentKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[InverseTimeKind, MagneticMomentKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: InverseTimePerMagneticMoment[float, S],
        other: Quantity[Div[InverseTimeKind, MagneticMomentKind], W, S],
        /,
    ) -> InverseTimePerMagneticMoment[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[InverseTimeKind, MagneticMomentKind], V, S]
        | Quantity[Div[InverseTimeKind, MagneticMomentKind], float, S],
        /,
    ) -> InverseTimePerMagneticMoment[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: InverseTimePerMagneticMoment[float, S],
        other: Quantity[Div[InverseTimeKind, MagneticMomentKind], W, S],
        /,
    ) -> InverseTimePerMagneticMoment[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[InverseTimeKind, MagneticMomentKind], V, S]
        | Quantity[Div[InverseTimeKind, MagneticMomentKind], float, S],
        /,
    ) -> InverseTimePerMagneticMoment[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> InverseTimePerMagneticMoment[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> InverseTimePerMagneticMoment[W, S]: ...
