# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Acceleration import _AccelerationConstant
from quantype._constants.Action import _ActionConstant
from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.Energy import _EnergyConstant
from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._constants.Momentum import _MomentumConstant
from quantype._constants.Velocity import _VelocityConstant
from quantype._generated import (
    Acceleration,
    Action,
    Dimensionless,
    Energy,
    Frequency,
    InverseTime,
    Momentum,
    Velocity,
)
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import DimensionlessKind, Div, InverseTimeKind, MomentumKind, Mul
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class InverseTimePerMomentum(Quantity[Div[InverseTimeKind, MomentumKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: InverseTimePerMomentum[float, S], other: Energy[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __mul__(
        self, other: Energy[V, S] | Energy[float, S] | _EnergyConstant, /
    ) -> Acceleration[V, S]: ...
    @overload
    def __mul__[W](
        self: InverseTimePerMomentum[float, S], other: Momentum[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def __mul__(
        self, other: Momentum[V, S] | Momentum[float, S] | _MomentumConstant, /
    ) -> InverseTime[V, S]: ...
    @overload
    def __mul__[W](
        self: InverseTimePerMomentum[float, S], other: Action[W, S], /
    ) -> Velocity[W, S]: ...
    @overload
    def __mul__(
        self, other: Action[V, S] | Action[float, S] | _ActionConstant, /
    ) -> Velocity[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> InverseTimePerMomentum[V, S]: ...
    @overload
    def __mul__(
        self: InverseTimePerMomentum[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> InverseTimePerMomentum[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: InverseTimePerMomentum[float, S], other: W, /
    ) -> InverseTimePerMomentum[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> InverseTimePerMomentum[V, S]: ...
    @overload
    def __mul__[K, W](
        self: InverseTimePerMomentum[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[InverseTimeKind, MomentumKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[InverseTimeKind, MomentumKind], K], V, S]: ...
    def _rmul_Energy_f(self, other: Energy[float, S], /) -> Acceleration[V, S]: ...
    @overload
    def _rmul_Energy[W](
        self: InverseTimePerMomentum[float, S], other: Energy[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def _rmul_Energy(self, other: Energy[V, S], /) -> Acceleration[V, S]: ...
    def _rmul_Momentum_f(self, other: Momentum[float, S], /) -> InverseTime[V, S]: ...
    @overload
    def _rmul_Momentum[W](
        self: InverseTimePerMomentum[float, S], other: Momentum[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def _rmul_Momentum(self, other: Momentum[V, S], /) -> InverseTime[V, S]: ...
    def _rmul_Action_f(self, other: Action[float, S], /) -> Velocity[V, S]: ...
    @overload
    def _rmul_Action[W](
        self: InverseTimePerMomentum[float, S], other: Action[W, S], /
    ) -> Velocity[W, S]: ...
    @overload
    def _rmul_Action(self, other: Action[V, S], /) -> Velocity[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: InverseTimePerMomentum[float, S], other: InverseTimePerMomentum[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: InverseTimePerMomentum[V, S]
        | InverseTimePerMomentum[float, S]
        | _InverseTimePerMomentumConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> InverseTimePerMomentum[V, S]: ...
    @overload
    def __truediv__(
        self: InverseTimePerMomentum[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> InverseTimePerMomentum[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: InverseTimePerMomentum[float, S], other: W, /
    ) -> InverseTimePerMomentum[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> InverseTimePerMomentum[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: InverseTimePerMomentum[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[InverseTimeKind, MomentumKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[InverseTimeKind, MomentumKind], K], V, S]: ...
    def _rtruediv_Velocity_f(self, other: Velocity[float, S], /) -> Action[V, S]: ...
    @overload
    def _rtruediv_Velocity[W](
        self: InverseTimePerMomentum[float, S], other: Velocity[W, S], /
    ) -> Action[W, S]: ...
    @overload
    def _rtruediv_Velocity(self, other: Velocity[V, S], /) -> Action[V, S]: ...
    def _rtruediv_Frequency_f(
        self, other: Frequency[float, S], /
    ) -> Momentum[V, S]: ...
    @overload
    def _rtruediv_Frequency[W](
        self: InverseTimePerMomentum[float, S], other: Frequency[W, S], /
    ) -> Momentum[W, S]: ...
    @overload
    def _rtruediv_Frequency(self, other: Frequency[V, S], /) -> Momentum[V, S]: ...
    def _rtruediv_InverseTime_f(
        self, other: InverseTime[float, S], /
    ) -> Momentum[V, S]: ...
    @overload
    def _rtruediv_InverseTime[W](
        self: InverseTimePerMomentum[float, S], other: InverseTime[W, S], /
    ) -> Momentum[W, S]: ...
    @overload
    def _rtruediv_InverseTime(self, other: InverseTime[V, S], /) -> Momentum[V, S]: ...
    def _rtruediv_Acceleration_f(
        self, other: Acceleration[float, S], /
    ) -> Energy[V, S]: ...
    @overload
    def _rtruediv_Acceleration[W](
        self: InverseTimePerMomentum[float, S], other: Acceleration[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def _rtruediv_Acceleration(self, other: Acceleration[V, S], /) -> Energy[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: InverseTimePerMomentum[float, S], other: Energy[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def __matmul__(
        self, other: Energy[V, S] | Energy[float, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    def __matmul__[W](
        self: InverseTimePerMomentum[float, S], other: Momentum[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def __matmul__(
        self, other: Momentum[V, S] | Momentum[float, S], /
    ) -> InverseTime[V, S]: ...
    @overload
    def __matmul__[W](
        self: InverseTimePerMomentum[float, S], other: Action[W, S], /
    ) -> Velocity[W, S]: ...
    @overload
    def __matmul__(
        self, other: Action[V, S] | Action[float, S], /
    ) -> Velocity[V, S]: ...
    @overload
    def __matmul__(
        self: InverseTimePerMomentum[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> InverseTimePerMomentum[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: InverseTimePerMomentum[float, S], other: W, /
    ) -> InverseTimePerMomentum[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> InverseTimePerMomentum[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: InverseTimePerMomentum[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[InverseTimeKind, MomentumKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[InverseTimeKind, MomentumKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> InverseTimePerMomentum[V, S]: ...
    @overload
    def __rmul__(
        self: InverseTimePerMomentum[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> InverseTimePerMomentum[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: InverseTimePerMomentum[float, S], other: W, /
    ) -> InverseTimePerMomentum[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> InverseTimePerMomentum[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: InverseTimePerMomentum[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> InverseTimePerMomentum[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: InverseTimePerMomentum[float, S], other: W, /
    ) -> InverseTimePerMomentum[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> InverseTimePerMomentum[V, S]: ...
    @override
    def item(self) -> InverseTimePerMomentum[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[InverseTimeKind, MomentumKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: InverseTimePerMomentum[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[InverseTimeKind, MomentumKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: InverseTimePerMomentum[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[InverseTimeKind, MomentumKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[InverseTimeKind, MomentumKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: InverseTimePerMomentum[float, S],
        other: Quantity[Div[InverseTimeKind, MomentumKind], W, S],
        /,
    ) -> InverseTimePerMomentum[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[InverseTimeKind, MomentumKind], V, S]
        | Quantity[Div[InverseTimeKind, MomentumKind], float, S],
        /,
    ) -> InverseTimePerMomentum[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: InverseTimePerMomentum[float, S],
        other: Quantity[Div[InverseTimeKind, MomentumKind], W, S],
        /,
    ) -> InverseTimePerMomentum[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[InverseTimeKind, MomentumKind], V, S]
        | Quantity[Div[InverseTimeKind, MomentumKind], float, S],
        /,
    ) -> InverseTimePerMomentum[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> InverseTimePerMomentum[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> InverseTimePerMomentum[W, S]: ...

class _InverseTimePerMomentumConstant(Constant[Div[InverseTimeKind, MomentumKind]]):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> InverseTimePerMomentum[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[InverseTimeKind, MomentumKind]]
    ) -> InverseTimePerMomentum[float]: ...
    @overload
    @override
    def __mul__(self, other: _EnergyConstant, /) -> _AccelerationConstant: ...
    @overload
    def __mul__(self, other: _MomentumConstant, /) -> _InverseTimeConstant: ...
    @overload
    def __mul__(self, other: _ActionConstant, /) -> _VelocityConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[InverseTimeKind, MomentumKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _InverseTimePerMomentumConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: Energy[W, T], /
    ) -> Acceleration[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: Momentum[W, T], /
    ) -> InverseTime[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Action[W, T], /) -> Velocity[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[InverseTimeKind, MomentumKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _InverseTimePerMomentumConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[InverseTimeKind, MomentumKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _InverseTimePerMomentumConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: InverseTimePerMomentum[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[InverseTimeKind, MomentumKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _InverseTimePerMomentumConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[InverseTimeKind, MomentumKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[InverseTimeKind, MomentumKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[InverseTimeKind, MomentumKind]], W, T]: ...
    def _rmul_Energy_f[T: UnitSystem](
        self, other: Energy[float, T], /
    ) -> Acceleration[float, T]: ...
    def _rmul_Energy[W, T: UnitSystem](
        self, other: Energy[W, T], /
    ) -> Acceleration[W, T]: ...
    def _cmul_Energy(self, other: _EnergyConstant, /) -> _AccelerationConstant: ...
    def _rmul_Momentum_f[T: UnitSystem](
        self, other: Momentum[float, T], /
    ) -> InverseTime[float, T]: ...
    def _rmul_Momentum[W, T: UnitSystem](
        self, other: Momentum[W, T], /
    ) -> InverseTime[W, T]: ...
    def _cmul_Momentum(self, other: _MomentumConstant, /) -> _InverseTimeConstant: ...
    def _rmul_Action_f[T: UnitSystem](
        self, other: Action[float, T], /
    ) -> Velocity[float, T]: ...
    def _rmul_Action[W, T: UnitSystem](
        self, other: Action[W, T], /
    ) -> Velocity[W, T]: ...
    def _cmul_Action(self, other: _ActionConstant, /) -> _VelocityConstant: ...
    def _rtruediv_Velocity_f[T: UnitSystem](
        self, other: Velocity[float, T], /
    ) -> Action[float, T]: ...
    def _rtruediv_Velocity[W, T: UnitSystem](
        self, other: Velocity[W, T], /
    ) -> Action[W, T]: ...
    def _ctruediv_Velocity(self, other: _VelocityConstant, /) -> _ActionConstant: ...
    def _rtruediv_Frequency_f[T: UnitSystem](
        self, other: Frequency[float, T], /
    ) -> Momentum[float, T]: ...
    def _rtruediv_Frequency[W, T: UnitSystem](
        self, other: Frequency[W, T], /
    ) -> Momentum[W, T]: ...
    def _ctruediv_Frequency(
        self, other: _FrequencyConstant, /
    ) -> _MomentumConstant: ...
    def _rtruediv_InverseTime_f[T: UnitSystem](
        self, other: InverseTime[float, T], /
    ) -> Momentum[float, T]: ...
    def _rtruediv_InverseTime[W, T: UnitSystem](
        self, other: InverseTime[W, T], /
    ) -> Momentum[W, T]: ...
    def _ctruediv_InverseTime(
        self, other: _InverseTimeConstant, /
    ) -> _MomentumConstant: ...
    def _rtruediv_Acceleration_f[T: UnitSystem](
        self, other: Acceleration[float, T], /
    ) -> Energy[float, T]: ...
    def _rtruediv_Acceleration[W, T: UnitSystem](
        self, other: Acceleration[W, T], /
    ) -> Energy[W, T]: ...
    def _ctruediv_Acceleration(
        self, other: _AccelerationConstant, /
    ) -> _EnergyConstant: ...
