# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.DipoleMoment import _DipoleMomentConstant
from quantype._constants.MagneticMoment import _MagneticMomentConstant
from quantype._generated import Dimensionless, DipoleMoment, MagneticMoment
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    DipoleMomentKind,
    Div,
    MagneticMomentKind,
    Mul,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class MagneticMomentDipoleMoment(
    Quantity[Mul[MagneticMomentKind, DipoleMomentKind], V, S]
):
    @overload
    @override
    def __mul__(self, other: _Scalar, /) -> MagneticMomentDipoleMoment[V, S]: ...
    @overload
    def __mul__(
        self: MagneticMomentDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> MagneticMomentDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: MagneticMomentDipoleMoment[float, S], other: W, /
    ) -> MagneticMomentDipoleMoment[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> MagneticMomentDipoleMoment[V, S]: ...
    @overload
    def __mul__[K, W](
        self: MagneticMomentDipoleMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[MagneticMomentKind, DipoleMomentKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[MagneticMomentKind, DipoleMomentKind], K], V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: MagneticMomentDipoleMoment[float, S], other: MagneticMoment[W, S], /
    ) -> DipoleMoment[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: MagneticMoment[V, S]
        | MagneticMoment[float, S]
        | _MagneticMomentConstant,
        /,
    ) -> DipoleMoment[V, S]: ...
    @overload
    def __truediv__[W](
        self: MagneticMomentDipoleMoment[float, S], other: DipoleMoment[W, S], /
    ) -> MagneticMoment[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: DipoleMoment[V, S] | DipoleMoment[float, S] | _DipoleMomentConstant,
        /,
    ) -> MagneticMoment[V, S]: ...
    @overload
    def __truediv__[W](
        self: MagneticMomentDipoleMoment[float, S],
        other: MagneticMomentDipoleMoment[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: MagneticMomentDipoleMoment[V, S] | MagneticMomentDipoleMoment[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> MagneticMomentDipoleMoment[V, S]: ...
    @overload
    def __truediv__(
        self: MagneticMomentDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> MagneticMomentDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: MagneticMomentDipoleMoment[float, S], other: W, /
    ) -> MagneticMomentDipoleMoment[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> MagneticMomentDipoleMoment[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: MagneticMomentDipoleMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[MagneticMomentKind, DipoleMomentKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[MagneticMomentKind, DipoleMomentKind], K], V, S]: ...
    @overload
    @override
    def __matmul__(
        self: MagneticMomentDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> MagneticMomentDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: MagneticMomentDipoleMoment[float, S], other: W, /
    ) -> MagneticMomentDipoleMoment[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> MagneticMomentDipoleMoment[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: MagneticMomentDipoleMoment[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[MagneticMomentKind, DipoleMomentKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[MagneticMomentKind, DipoleMomentKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> MagneticMomentDipoleMoment[V, S]: ...
    @overload
    def __rmul__(
        self: MagneticMomentDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> MagneticMomentDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: MagneticMomentDipoleMoment[float, S], other: W, /
    ) -> MagneticMomentDipoleMoment[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> MagneticMomentDipoleMoment[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: MagneticMomentDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> MagneticMomentDipoleMoment[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: MagneticMomentDipoleMoment[float, S], other: W, /
    ) -> MagneticMomentDipoleMoment[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> MagneticMomentDipoleMoment[V, S]: ...
    @override
    def item(self) -> MagneticMomentDipoleMoment[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[MagneticMomentKind, DipoleMomentKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: MagneticMomentDipoleMoment[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Mul[MagneticMomentKind, DipoleMomentKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: MagneticMomentDipoleMoment[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[MagneticMomentKind, DipoleMomentKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[MagneticMomentKind, DipoleMomentKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: MagneticMomentDipoleMoment[float, S],
        other: Quantity[Mul[MagneticMomentKind, DipoleMomentKind], W, S],
        /,
    ) -> MagneticMomentDipoleMoment[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[MagneticMomentKind, DipoleMomentKind], V, S]
        | Quantity[Mul[MagneticMomentKind, DipoleMomentKind], float, S],
        /,
    ) -> MagneticMomentDipoleMoment[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: MagneticMomentDipoleMoment[float, S],
        other: Quantity[Mul[MagneticMomentKind, DipoleMomentKind], W, S],
        /,
    ) -> MagneticMomentDipoleMoment[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[MagneticMomentKind, DipoleMomentKind], V, S]
        | Quantity[Mul[MagneticMomentKind, DipoleMomentKind], float, S],
        /,
    ) -> MagneticMomentDipoleMoment[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> MagneticMomentDipoleMoment[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> MagneticMomentDipoleMoment[W, S]: ...
