# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.Energy import _EnergyConstant
from quantype._constants.EnergyDensity import _EnergyDensityConstant
from quantype._constants.MagneticMoment import _MagneticMomentConstant
from quantype._constants.Magnetization import _MagnetizationConstant
from quantype._constants.Pressure import _PressureConstant
from quantype._generated import (
    Dimensionless,
    Energy,
    EnergyDensity,
    MagneticMoment,
    Magnetization,
    Pressure,
)
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import DimensionlessKind, Div, EnergyKind, MagneticMomentKind, Mul
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class MagneticMomentPerEnergy(Quantity[Div[MagneticMomentKind, EnergyKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: MagneticMomentPerEnergy[float, S], other: Energy[W, S], /
    ) -> MagneticMoment[W, S]: ...
    @overload
    def __mul__(
        self, other: Energy[V, S] | Energy[float, S] | _EnergyConstant, /
    ) -> MagneticMoment[V, S]: ...
    @overload
    def __mul__[W](
        self: MagneticMomentPerEnergy[float, S], other: Pressure[W, S], /
    ) -> Magnetization[W, S]: ...
    @overload
    def __mul__(
        self, other: Pressure[V, S] | Pressure[float, S] | _PressureConstant, /
    ) -> Magnetization[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> MagneticMomentPerEnergy[V, S]: ...
    @overload
    def __mul__(
        self: MagneticMomentPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> MagneticMomentPerEnergy[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: MagneticMomentPerEnergy[float, S], other: W, /
    ) -> MagneticMomentPerEnergy[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> MagneticMomentPerEnergy[V, S]: ...
    @overload
    def __mul__[K, W](
        self: MagneticMomentPerEnergy[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[MagneticMomentKind, EnergyKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[MagneticMomentKind, EnergyKind], K], V, S]: ...
    def _rmul_Energy_f(self, other: Energy[float, S], /) -> MagneticMoment[V, S]: ...
    @overload
    def _rmul_Energy[W](
        self: MagneticMomentPerEnergy[float, S], other: Energy[W, S], /
    ) -> MagneticMoment[W, S]: ...
    @overload
    def _rmul_Energy(self, other: Energy[V, S], /) -> MagneticMoment[V, S]: ...
    def _rmul_Pressure_f(self, other: Pressure[float, S], /) -> Magnetization[V, S]: ...
    @overload
    def _rmul_Pressure[W](
        self: MagneticMomentPerEnergy[float, S], other: Pressure[W, S], /
    ) -> Magnetization[W, S]: ...
    @overload
    def _rmul_Pressure(self, other: Pressure[V, S], /) -> Magnetization[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: MagneticMomentPerEnergy[float, S], other: MagneticMomentPerEnergy[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: MagneticMomentPerEnergy[V, S]
        | MagneticMomentPerEnergy[float, S]
        | _MagneticMomentPerEnergyConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> MagneticMomentPerEnergy[V, S]: ...
    @overload
    def __truediv__(
        self: MagneticMomentPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> MagneticMomentPerEnergy[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: MagneticMomentPerEnergy[float, S], other: W, /
    ) -> MagneticMomentPerEnergy[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> MagneticMomentPerEnergy[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: MagneticMomentPerEnergy[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[MagneticMomentKind, EnergyKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[MagneticMomentKind, EnergyKind], K], V, S]: ...
    def _rtruediv_MagneticMoment_f(
        self, other: MagneticMoment[float, S], /
    ) -> Energy[V, S]: ...
    @overload
    def _rtruediv_MagneticMoment[W](
        self: MagneticMomentPerEnergy[float, S], other: MagneticMoment[W, S], /
    ) -> Energy[W, S]: ...
    @overload
    def _rtruediv_MagneticMoment(
        self, other: MagneticMoment[V, S], /
    ) -> Energy[V, S]: ...
    def _rtruediv_Magnetization_f(
        self, other: Magnetization[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def _rtruediv_Magnetization[W](
        self: MagneticMomentPerEnergy[float, S], other: Magnetization[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def _rtruediv_Magnetization(
        self, other: Magnetization[V, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: MagneticMomentPerEnergy[float, S], other: Energy[W, S], /
    ) -> MagneticMoment[W, S]: ...
    @overload
    def __matmul__(
        self, other: Energy[V, S] | Energy[float, S], /
    ) -> MagneticMoment[V, S]: ...
    @overload
    def __matmul__[W](
        self: MagneticMomentPerEnergy[float, S], other: Pressure[W, S], /
    ) -> Magnetization[W, S]: ...
    @overload
    def __matmul__(
        self, other: Pressure[V, S] | Pressure[float, S], /
    ) -> Magnetization[V, S]: ...
    @overload
    def __matmul__(
        self: MagneticMomentPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> MagneticMomentPerEnergy[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: MagneticMomentPerEnergy[float, S], other: W, /
    ) -> MagneticMomentPerEnergy[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> MagneticMomentPerEnergy[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: MagneticMomentPerEnergy[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[MagneticMomentKind, EnergyKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[MagneticMomentKind, EnergyKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> MagneticMomentPerEnergy[V, S]: ...
    @overload
    def __rmul__(
        self: MagneticMomentPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> MagneticMomentPerEnergy[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: MagneticMomentPerEnergy[float, S], other: W, /
    ) -> MagneticMomentPerEnergy[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> MagneticMomentPerEnergy[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: MagneticMomentPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> MagneticMomentPerEnergy[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: MagneticMomentPerEnergy[float, S], other: W, /
    ) -> MagneticMomentPerEnergy[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> MagneticMomentPerEnergy[V, S]: ...
    @override
    def item(self) -> MagneticMomentPerEnergy[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[MagneticMomentKind, EnergyKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: MagneticMomentPerEnergy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[MagneticMomentKind, EnergyKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: MagneticMomentPerEnergy[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[MagneticMomentKind, EnergyKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[MagneticMomentKind, EnergyKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: MagneticMomentPerEnergy[float, S],
        other: Quantity[Div[MagneticMomentKind, EnergyKind], W, S],
        /,
    ) -> MagneticMomentPerEnergy[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[MagneticMomentKind, EnergyKind], V, S]
        | Quantity[Div[MagneticMomentKind, EnergyKind], float, S],
        /,
    ) -> MagneticMomentPerEnergy[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: MagneticMomentPerEnergy[float, S],
        other: Quantity[Div[MagneticMomentKind, EnergyKind], W, S],
        /,
    ) -> MagneticMomentPerEnergy[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[MagneticMomentKind, EnergyKind], V, S]
        | Quantity[Div[MagneticMomentKind, EnergyKind], float, S],
        /,
    ) -> MagneticMomentPerEnergy[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> MagneticMomentPerEnergy[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> MagneticMomentPerEnergy[W, S]: ...

class _MagneticMomentPerEnergyConstant(Constant[Div[MagneticMomentKind, EnergyKind]]):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> MagneticMomentPerEnergy[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[MagneticMomentKind, EnergyKind]]
    ) -> MagneticMomentPerEnergy[float]: ...
    @overload
    @override
    def __mul__(self, other: _EnergyConstant, /) -> _MagneticMomentConstant: ...
    @overload
    def __mul__(self, other: _PressureConstant, /) -> _MagnetizationConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[MagneticMomentKind, EnergyKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _MagneticMomentPerEnergyConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: Energy[W, T], /
    ) -> MagneticMoment[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: Pressure[W, T], /
    ) -> Magnetization[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[MagneticMomentKind, EnergyKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _MagneticMomentPerEnergyConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[MagneticMomentKind, EnergyKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _MagneticMomentPerEnergyConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: MagneticMomentPerEnergy[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[MagneticMomentKind, EnergyKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _MagneticMomentPerEnergyConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[MagneticMomentKind, EnergyKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[MagneticMomentKind, EnergyKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[MagneticMomentKind, EnergyKind]], W, T]: ...
    def _rmul_Energy_f[T: UnitSystem](
        self, other: Energy[float, T], /
    ) -> MagneticMoment[float, T]: ...
    def _rmul_Energy[W, T: UnitSystem](
        self, other: Energy[W, T], /
    ) -> MagneticMoment[W, T]: ...
    def _cmul_Energy(self, other: _EnergyConstant, /) -> _MagneticMomentConstant: ...
    def _rmul_Pressure_f[T: UnitSystem](
        self, other: Pressure[float, T], /
    ) -> Magnetization[float, T]: ...
    def _rmul_Pressure[W, T: UnitSystem](
        self, other: Pressure[W, T], /
    ) -> Magnetization[W, T]: ...
    def _cmul_Pressure(self, other: _PressureConstant, /) -> _MagnetizationConstant: ...
    def _rtruediv_MagneticMoment_f[T: UnitSystem](
        self, other: MagneticMoment[float, T], /
    ) -> Energy[float, T]: ...
    def _rtruediv_MagneticMoment[W, T: UnitSystem](
        self, other: MagneticMoment[W, T], /
    ) -> Energy[W, T]: ...
    def _ctruediv_MagneticMoment(
        self, other: _MagneticMomentConstant, /
    ) -> _EnergyConstant: ...
    def _rtruediv_Magnetization_f[T: UnitSystem](
        self, other: Magnetization[float, T], /
    ) -> EnergyDensity[float, T]: ...
    def _rtruediv_Magnetization[W, T: UnitSystem](
        self, other: Magnetization[W, T], /
    ) -> EnergyDensity[W, T]: ...
    def _ctruediv_Magnetization(
        self, other: _MagnetizationConstant, /
    ) -> _EnergyDensityConstant: ...
