# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.TemperatureDifference import _TemperatureDifferenceConstant
from quantype._generated import Dimensionless, Magnetization, TemperatureDifference
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    MagnetizationKind,
    Mul,
    TemperatureDifferenceKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class MagnetizationPerTemperatureDifference(
    Quantity[Div[MagnetizationKind, TemperatureDifferenceKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: MagnetizationPerTemperatureDifference[float, S],
        other: TemperatureDifference[W, S],
        /,
    ) -> Magnetization[W, S]: ...
    @overload
    def __mul__(
        self,
        other: TemperatureDifference[V, S]
        | TemperatureDifference[float, S]
        | _TemperatureDifferenceConstant,
        /,
    ) -> Magnetization[V, S]: ...
    @overload
    def __mul__(
        self, other: _Scalar, /
    ) -> MagnetizationPerTemperatureDifference[V, S]: ...
    @overload
    def __mul__(
        self: MagnetizationPerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> MagnetizationPerTemperatureDifference[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: MagnetizationPerTemperatureDifference[float, S], other: W, /
    ) -> MagnetizationPerTemperatureDifference[W, S]: ...
    @overload
    def __mul__(
        self, other: _Numerical, /
    ) -> MagnetizationPerTemperatureDifference[V, S]: ...
    @overload
    def __mul__[K, W](
        self: MagnetizationPerTemperatureDifference[float, S],
        other: Quantity[K, W, S],
        /,
    ) -> Quantity[Mul[Div[MagnetizationKind, TemperatureDifferenceKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[MagnetizationKind, TemperatureDifferenceKind], K], V, S]: ...
    def _rmul_TemperatureDifference_f(
        self, other: TemperatureDifference[float, S], /
    ) -> Magnetization[V, S]: ...
    @overload
    def _rmul_TemperatureDifference[W](
        self: MagnetizationPerTemperatureDifference[float, S],
        other: TemperatureDifference[W, S],
        /,
    ) -> Magnetization[W, S]: ...
    @overload
    def _rmul_TemperatureDifference(
        self, other: TemperatureDifference[V, S], /
    ) -> Magnetization[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: MagnetizationPerTemperatureDifference[float, S],
        other: MagnetizationPerTemperatureDifference[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: MagnetizationPerTemperatureDifference[V, S]
        | MagnetizationPerTemperatureDifference[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(
        self, other: _Scalar, /
    ) -> MagnetizationPerTemperatureDifference[V, S]: ...
    @overload
    def __truediv__(
        self: MagnetizationPerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> MagnetizationPerTemperatureDifference[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: MagnetizationPerTemperatureDifference[float, S], other: W, /
    ) -> MagnetizationPerTemperatureDifference[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> MagnetizationPerTemperatureDifference[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: MagnetizationPerTemperatureDifference[float, S],
        other: Quantity[K, W, S],
        /,
    ) -> Quantity[Div[Div[MagnetizationKind, TemperatureDifferenceKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[MagnetizationKind, TemperatureDifferenceKind], K], V, S]: ...
    def _rtruediv_Magnetization_f(
        self, other: Magnetization[float, S], /
    ) -> TemperatureDifference[V, S]: ...
    @overload
    def _rtruediv_Magnetization[W](
        self: MagnetizationPerTemperatureDifference[float, S],
        other: Magnetization[W, S],
        /,
    ) -> TemperatureDifference[W, S]: ...
    @overload
    def _rtruediv_Magnetization(
        self, other: Magnetization[V, S], /
    ) -> TemperatureDifference[V, S]: ...
    @overload
    @override
    def __rmul__(
        self, other: _Scalar, /
    ) -> MagnetizationPerTemperatureDifference[V, S]: ...
    @overload
    def __rmul__(
        self: MagnetizationPerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> MagnetizationPerTemperatureDifference[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: MagnetizationPerTemperatureDifference[float, S], other: W, /
    ) -> MagnetizationPerTemperatureDifference[W, S]: ...
    @overload
    def __rmul__(
        self, other: _Numerical, /
    ) -> MagnetizationPerTemperatureDifference[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[MagnetizationKind, TemperatureDifferenceKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: MagnetizationPerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[MagnetizationKind, TemperatureDifferenceKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: MagnetizationPerTemperatureDifference[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[MagnetizationKind, TemperatureDifferenceKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[MagnetizationKind, TemperatureDifferenceKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: MagnetizationPerTemperatureDifference[float, S],
        other: Quantity[Div[MagnetizationKind, TemperatureDifferenceKind], W, S],
        /,
    ) -> MagnetizationPerTemperatureDifference[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[MagnetizationKind, TemperatureDifferenceKind], V, S]
        | Quantity[Div[MagnetizationKind, TemperatureDifferenceKind], float, S],
        /,
    ) -> MagnetizationPerTemperatureDifference[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: MagnetizationPerTemperatureDifference[float, S],
        other: Quantity[Div[MagnetizationKind, TemperatureDifferenceKind], W, S],
        /,
    ) -> MagnetizationPerTemperatureDifference[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[MagnetizationKind, TemperatureDifferenceKind], V, S]
        | Quantity[Div[MagnetizationKind, TemperatureDifferenceKind], float, S],
        /,
    ) -> MagnetizationPerTemperatureDifference[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> MagnetizationPerTemperatureDifference[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> MagnetizationPerTemperatureDifference[W, S]: ...
