# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.ElectronDensity import _ElectronDensityConstant
from quantype._generated import Dimensionless, ElectronDensity, Mass
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, ElectronDensityKind, MassKind, Mul
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class MassPerElectronDensity(Quantity[Div[MassKind, ElectronDensityKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: MassPerElectronDensity[float, S], other: ElectronDensity[W, S], /
    ) -> Mass[W, S]: ...
    @overload
    def __mul__(
        self,
        other: ElectronDensity[V, S]
        | ElectronDensity[float, S]
        | _ElectronDensityConstant,
        /,
    ) -> Mass[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> MassPerElectronDensity[V, S]: ...
    @overload
    def __mul__(
        self: MassPerElectronDensity[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> MassPerElectronDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: MassPerElectronDensity[float, S], other: W, /
    ) -> MassPerElectronDensity[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> MassPerElectronDensity[V, S]: ...
    @overload
    def __mul__[K, W](
        self: MassPerElectronDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[MassKind, ElectronDensityKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[MassKind, ElectronDensityKind], K], V, S]: ...
    def _rmul_ElectronDensity_f(
        self, other: ElectronDensity[float, S], /
    ) -> Mass[V, S]: ...
    @overload
    def _rmul_ElectronDensity[W](
        self: MassPerElectronDensity[float, S], other: ElectronDensity[W, S], /
    ) -> Mass[W, S]: ...
    @overload
    def _rmul_ElectronDensity(self, other: ElectronDensity[V, S], /) -> Mass[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: MassPerElectronDensity[float, S], other: MassPerElectronDensity[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: MassPerElectronDensity[V, S] | MassPerElectronDensity[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> MassPerElectronDensity[V, S]: ...
    @overload
    def __truediv__(
        self: MassPerElectronDensity[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> MassPerElectronDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: MassPerElectronDensity[float, S], other: W, /
    ) -> MassPerElectronDensity[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> MassPerElectronDensity[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: MassPerElectronDensity[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[MassKind, ElectronDensityKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[MassKind, ElectronDensityKind], K], V, S]: ...
    def _rtruediv_Mass_f(self, other: Mass[float, S], /) -> ElectronDensity[V, S]: ...
    @overload
    def _rtruediv_Mass[W](
        self: MassPerElectronDensity[float, S], other: Mass[W, S], /
    ) -> ElectronDensity[W, S]: ...
    @overload
    def _rtruediv_Mass(self, other: Mass[V, S], /) -> ElectronDensity[V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> MassPerElectronDensity[V, S]: ...
    @overload
    def __rmul__(
        self: MassPerElectronDensity[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> MassPerElectronDensity[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: MassPerElectronDensity[float, S], other: W, /
    ) -> MassPerElectronDensity[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> MassPerElectronDensity[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[MassKind, ElectronDensityKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: MassPerElectronDensity[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[MassKind, ElectronDensityKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: MassPerElectronDensity[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[MassKind, ElectronDensityKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[MassKind, ElectronDensityKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: MassPerElectronDensity[float, S],
        other: Quantity[Div[MassKind, ElectronDensityKind], W, S],
        /,
    ) -> MassPerElectronDensity[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[MassKind, ElectronDensityKind], V, S]
        | Quantity[Div[MassKind, ElectronDensityKind], float, S],
        /,
    ) -> MassPerElectronDensity[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: MassPerElectronDensity[float, S],
        other: Quantity[Div[MassKind, ElectronDensityKind], W, S],
        /,
    ) -> MassPerElectronDensity[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[MassKind, ElectronDensityKind], V, S]
        | Quantity[Div[MassKind, ElectronDensityKind], float, S],
        /,
    ) -> MassPerElectronDensity[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> MassPerElectronDensity[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> MassPerElectronDensity[W, S]: ...
