# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, Literal, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.ElectronCount import _ElectronCountConstant
from quantype._generated import Dimensionless, ElectronCount
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, ElectronCountKind, Mul, Pow
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class PerElectronCount(Quantity[Pow[ElectronCountKind, Literal[-1]], V, S]):
    @overload
    @override
    def __mul__[W](
        self: PerElectronCount[float, S], other: ElectronCount[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __mul__(
        self,
        other: ElectronCount[V, S] | ElectronCount[float, S] | _ElectronCountConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> PerElectronCount[V, S]: ...
    @overload
    def __mul__(
        self: PerElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PerElectronCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: PerElectronCount[float, S], other: W, /
    ) -> PerElectronCount[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> PerElectronCount[V, S]: ...
    @overload
    def __mul__[K, W](
        self: PerElectronCount[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Pow[ElectronCountKind, Literal[-1]], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Pow[ElectronCountKind, Literal[-1]], K], V, S]: ...
    def _rmul_ElectronCount_f(
        self, other: ElectronCount[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def _rmul_ElectronCount[W](
        self: PerElectronCount[float, S], other: ElectronCount[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def _rmul_ElectronCount(
        self, other: ElectronCount[V, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: PerElectronCount[float, S], other: PerElectronCount[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: PerElectronCount[V, S] | PerElectronCount[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> PerElectronCount[V, S]: ...
    @overload
    def __truediv__(
        self: PerElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PerElectronCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: PerElectronCount[float, S], other: W, /
    ) -> PerElectronCount[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> PerElectronCount[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: PerElectronCount[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Pow[ElectronCountKind, Literal[-1]], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Pow[ElectronCountKind, Literal[-1]], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> PerElectronCount[V, S]: ...
    @overload
    def __rmul__(
        self: PerElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PerElectronCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: PerElectronCount[float, S], other: W, /
    ) -> PerElectronCount[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> PerElectronCount[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Pow[ElectronCountKind, Literal[-1]]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: PerElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Pow[ElectronCountKind, Literal[-1]]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: PerElectronCount[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Pow[ElectronCountKind, Literal[-1]]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Pow[ElectronCountKind, Literal[-1]]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: PerElectronCount[float, S],
        other: Quantity[Pow[ElectronCountKind, Literal[-1]], W, S],
        /,
    ) -> PerElectronCount[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Pow[ElectronCountKind, Literal[-1]], V, S]
        | Quantity[Pow[ElectronCountKind, Literal[-1]], float, S],
        /,
    ) -> PerElectronCount[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: PerElectronCount[float, S],
        other: Quantity[Pow[ElectronCountKind, Literal[-1]], W, S],
        /,
    ) -> PerElectronCount[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Pow[ElectronCountKind, Literal[-1]], V, S]
        | Quantity[Pow[ElectronCountKind, Literal[-1]], float, S],
        /,
    ) -> PerElectronCount[V, S]: ...
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> PerElectronCount[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> PerElectronCount[W, S]: ...
