# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._constants.Pressure import _PressureConstant
from quantype._constants.Time import _TimeConstant
from quantype._generated import Dimensionless, Frequency, InverseTime, Pressure, Time
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, InverseTimeKind, Mul, PressureKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class PressureInverseTime(Quantity[Mul[PressureKind, InverseTimeKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: PressureInverseTime[float, S], other: Time[W, S], /
    ) -> Pressure[W, S]: ...
    @overload
    def __mul__(
        self, other: Time[V, S] | Time[float, S] | _TimeConstant, /
    ) -> Pressure[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> PressureInverseTime[V, S]: ...
    @overload
    def __mul__(
        self: PressureInverseTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PressureInverseTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: PressureInverseTime[float, S], other: W, /
    ) -> PressureInverseTime[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> PressureInverseTime[V, S]: ...
    @overload
    def __mul__[K, W](
        self: PressureInverseTime[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[PressureKind, InverseTimeKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[PressureKind, InverseTimeKind], K], V, S]: ...
    def _rmul_Time_f(self, other: Time[float, S], /) -> Pressure[V, S]: ...
    @overload
    def _rmul_Time[W](
        self: PressureInverseTime[float, S], other: Time[W, S], /
    ) -> Pressure[W, S]: ...
    @overload
    def _rmul_Time(self, other: Time[V, S], /) -> Pressure[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: PressureInverseTime[float, S], other: Pressure[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def __truediv__(
        self, other: Pressure[V, S] | Pressure[float, S] | _PressureConstant, /
    ) -> InverseTime[V, S]: ...
    @overload
    def __truediv__[W](
        self: PressureInverseTime[float, S], other: Frequency[W, S], /
    ) -> Pressure[W, S]: ...
    @overload
    def __truediv__(
        self, other: Frequency[V, S] | Frequency[float, S] | _FrequencyConstant, /
    ) -> Pressure[V, S]: ...
    @overload
    def __truediv__[W](
        self: PressureInverseTime[float, S], other: InverseTime[W, S], /
    ) -> Pressure[W, S]: ...
    @overload
    def __truediv__(
        self, other: InverseTime[V, S] | InverseTime[float, S] | _InverseTimeConstant, /
    ) -> Pressure[V, S]: ...
    @overload
    def __truediv__[W](
        self: PressureInverseTime[float, S], other: PressureInverseTime[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: PressureInverseTime[V, S] | PressureInverseTime[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> PressureInverseTime[V, S]: ...
    @overload
    def __truediv__(
        self: PressureInverseTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PressureInverseTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: PressureInverseTime[float, S], other: W, /
    ) -> PressureInverseTime[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> PressureInverseTime[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: PressureInverseTime[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[PressureKind, InverseTimeKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[PressureKind, InverseTimeKind], K], V, S]: ...
    def _rtruediv_Pressure_f(self, other: Pressure[float, S], /) -> Time[V, S]: ...
    @overload
    def _rtruediv_Pressure[W](
        self: PressureInverseTime[float, S], other: Pressure[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def _rtruediv_Pressure(self, other: Pressure[V, S], /) -> Time[V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> PressureInverseTime[V, S]: ...
    @overload
    def __rmul__(
        self: PressureInverseTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PressureInverseTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: PressureInverseTime[float, S], other: W, /
    ) -> PressureInverseTime[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> PressureInverseTime[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Mul[PressureKind, InverseTimeKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: PressureInverseTime[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[PressureKind, InverseTimeKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: PressureInverseTime[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Mul[PressureKind, InverseTimeKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Mul[PressureKind, InverseTimeKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: PressureInverseTime[float, S],
        other: Quantity[Mul[PressureKind, InverseTimeKind], W, S],
        /,
    ) -> PressureInverseTime[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[PressureKind, InverseTimeKind], V, S]
        | Quantity[Mul[PressureKind, InverseTimeKind], float, S],
        /,
    ) -> PressureInverseTime[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: PressureInverseTime[float, S],
        other: Quantity[Mul[PressureKind, InverseTimeKind], W, S],
        /,
    ) -> PressureInverseTime[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[PressureKind, InverseTimeKind], V, S]
        | Quantity[Mul[PressureKind, InverseTimeKind], float, S],
        /,
    ) -> PressureInverseTime[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> PressureInverseTime[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> PressureInverseTime[W, S]: ...
