# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Area import _AreaConstant
from quantype._constants.Force import _ForceConstant
from quantype._constants.Volume import _VolumeConstant
from quantype._generated import Area, Dimensionless, Force, Length, Pressure, Volume
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, ForceKind, Mul, PressureKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class PressurePerForce(Quantity[Div[PressureKind, ForceKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: PressurePerForce[float, S], other: Area[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __mul__(
        self, other: Area[V, S] | Area[float, S] | _AreaConstant, /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __mul__[W](
        self: PressurePerForce[float, S], other: Volume[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def __mul__(
        self, other: Volume[V, S] | Volume[float, S] | _VolumeConstant, /
    ) -> Length[V, S]: ...
    @overload
    def __mul__[W](
        self: PressurePerForce[float, S], other: Force[W, S], /
    ) -> Pressure[W, S]: ...
    @overload
    def __mul__(
        self, other: Force[V, S] | Force[float, S] | _ForceConstant, /
    ) -> Pressure[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> PressurePerForce[V, S]: ...
    @overload
    def __mul__(
        self: PressurePerForce[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PressurePerForce[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: PressurePerForce[float, S], other: W, /
    ) -> PressurePerForce[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> PressurePerForce[V, S]: ...
    @overload
    def __mul__[K, W](
        self: PressurePerForce[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[PressureKind, ForceKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[PressureKind, ForceKind], K], V, S]: ...
    def _rmul_Area_f(self, other: Area[float, S], /) -> Dimensionless[V, S]: ...
    @overload
    def _rmul_Area[W](
        self: PressurePerForce[float, S], other: Area[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def _rmul_Area(self, other: Area[V, S], /) -> Dimensionless[V, S]: ...
    def _rmul_Volume_f(self, other: Volume[float, S], /) -> Length[V, S]: ...
    @overload
    def _rmul_Volume[W](
        self: PressurePerForce[float, S], other: Volume[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def _rmul_Volume(self, other: Volume[V, S], /) -> Length[V, S]: ...
    def _rmul_Force_f(self, other: Force[float, S], /) -> Pressure[V, S]: ...
    @overload
    def _rmul_Force[W](
        self: PressurePerForce[float, S], other: Force[W, S], /
    ) -> Pressure[W, S]: ...
    @overload
    def _rmul_Force(self, other: Force[V, S], /) -> Pressure[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: PressurePerForce[float, S], other: PressurePerForce[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: PressurePerForce[V, S] | PressurePerForce[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> PressurePerForce[V, S]: ...
    @overload
    def __truediv__(
        self: PressurePerForce[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PressurePerForce[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: PressurePerForce[float, S], other: W, /
    ) -> PressurePerForce[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> PressurePerForce[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: PressurePerForce[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[PressureKind, ForceKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[PressureKind, ForceKind], K], V, S]: ...
    def _rtruediv_Length_f(self, other: Length[float, S], /) -> Volume[V, S]: ...
    @overload
    def _rtruediv_Length[W](
        self: PressurePerForce[float, S], other: Length[W, S], /
    ) -> Volume[W, S]: ...
    @overload
    def _rtruediv_Length(self, other: Length[V, S], /) -> Volume[V, S]: ...
    def _rtruediv_Pressure_f(self, other: Pressure[float, S], /) -> Force[V, S]: ...
    @overload
    def _rtruediv_Pressure[W](
        self: PressurePerForce[float, S], other: Pressure[W, S], /
    ) -> Force[W, S]: ...
    @overload
    def _rtruediv_Pressure(self, other: Pressure[V, S], /) -> Force[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: PressurePerForce[float, S], other: Area[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __matmul__(
        self, other: Area[V, S] | Area[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __matmul__[W](
        self: PressurePerForce[float, S], other: Volume[W, S], /
    ) -> Length[W, S]: ...
    @overload
    def __matmul__(self, other: Volume[V, S] | Volume[float, S], /) -> Length[V, S]: ...
    @overload
    def __matmul__[W](
        self: PressurePerForce[float, S], other: Force[W, S], /
    ) -> Pressure[W, S]: ...
    @overload
    def __matmul__(self, other: Force[V, S] | Force[float, S], /) -> Pressure[V, S]: ...
    @overload
    def __matmul__(
        self: PressurePerForce[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PressurePerForce[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: PressurePerForce[float, S], other: W, /
    ) -> PressurePerForce[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> PressurePerForce[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: PressurePerForce[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[PressureKind, ForceKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[PressureKind, ForceKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> PressurePerForce[V, S]: ...
    @overload
    def __rmul__(
        self: PressurePerForce[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PressurePerForce[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: PressurePerForce[float, S], other: W, /
    ) -> PressurePerForce[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> PressurePerForce[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: PressurePerForce[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> PressurePerForce[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: PressurePerForce[float, S], other: W, /
    ) -> PressurePerForce[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> PressurePerForce[V, S]: ...
    @override
    def item(self) -> PressurePerForce[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[PressureKind, ForceKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: PressurePerForce[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[PressureKind, ForceKind]], npt.NDArray[np.float64], S
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: PressurePerForce[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[PressureKind, ForceKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[PressureKind, ForceKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: PressurePerForce[float, S],
        other: Quantity[Div[PressureKind, ForceKind], W, S],
        /,
    ) -> PressurePerForce[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[PressureKind, ForceKind], V, S]
        | Quantity[Div[PressureKind, ForceKind], float, S],
        /,
    ) -> PressurePerForce[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: PressurePerForce[float, S],
        other: Quantity[Div[PressureKind, ForceKind], W, S],
        /,
    ) -> PressurePerForce[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[PressureKind, ForceKind], V, S]
        | Quantity[Div[PressureKind, ForceKind], float, S],
        /,
    ) -> PressurePerForce[V, S]: ...
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> PressurePerForce[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> PressurePerForce[W, S]: ...
