# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Entropy import _EntropyConstant
from quantype._generated import (
    Dimensionless,
    Entropy,
    Temperature,
    TemperatureDifference,
)
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, EntropyKind, Mul, TemperatureKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class TemperaturePerEntropy(Quantity[Div[TemperatureKind, EntropyKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: TemperaturePerEntropy[float, S], other: Entropy[W, S], /
    ) -> Temperature[W, S]: ...
    @overload
    def __mul__(
        self, other: Entropy[V, S] | Entropy[float, S] | _EntropyConstant, /
    ) -> Temperature[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> TemperaturePerEntropy[V, S]: ...
    @overload
    def __mul__(
        self: TemperaturePerEntropy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TemperaturePerEntropy[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: TemperaturePerEntropy[float, S], other: W, /
    ) -> TemperaturePerEntropy[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> TemperaturePerEntropy[V, S]: ...
    @overload
    def __mul__[K, W](
        self: TemperaturePerEntropy[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[TemperatureKind, EntropyKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[TemperatureKind, EntropyKind], K], V, S]: ...
    def _rmul_Entropy_f(self, other: Entropy[float, S], /) -> Temperature[V, S]: ...
    @overload
    def _rmul_Entropy[W](
        self: TemperaturePerEntropy[float, S], other: Entropy[W, S], /
    ) -> Temperature[W, S]: ...
    @overload
    def _rmul_Entropy(self, other: Entropy[V, S], /) -> Temperature[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: TemperaturePerEntropy[float, S], other: TemperaturePerEntropy[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: TemperaturePerEntropy[V, S] | TemperaturePerEntropy[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> TemperaturePerEntropy[V, S]: ...
    @overload
    def __truediv__(
        self: TemperaturePerEntropy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TemperaturePerEntropy[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: TemperaturePerEntropy[float, S], other: W, /
    ) -> TemperaturePerEntropy[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> TemperaturePerEntropy[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: TemperaturePerEntropy[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[TemperatureKind, EntropyKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[TemperatureKind, EntropyKind], K], V, S]: ...
    def _rtruediv_Temperature_f(
        self, other: Temperature[float, S], /
    ) -> Entropy[V, S]: ...
    @overload
    def _rtruediv_Temperature[W](
        self: TemperaturePerEntropy[float, S], other: Temperature[W, S], /
    ) -> Entropy[W, S]: ...
    @overload
    def _rtruediv_Temperature(self, other: Temperature[V, S], /) -> Entropy[V, S]: ...
    def _rtruediv_TemperatureDifference_f(
        self, other: TemperatureDifference[float, S], /
    ) -> Entropy[V, S]: ...
    @overload
    def _rtruediv_TemperatureDifference[W](
        self: TemperaturePerEntropy[float, S], other: TemperatureDifference[W, S], /
    ) -> Entropy[W, S]: ...
    @overload
    def _rtruediv_TemperatureDifference(
        self, other: TemperatureDifference[V, S], /
    ) -> Entropy[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: TemperaturePerEntropy[float, S], other: Entropy[W, S], /
    ) -> Temperature[W, S]: ...
    @overload
    def __matmul__(
        self, other: Entropy[V, S] | Entropy[float, S], /
    ) -> Temperature[V, S]: ...
    @overload
    def __matmul__(
        self: TemperaturePerEntropy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TemperaturePerEntropy[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: TemperaturePerEntropy[float, S], other: W, /
    ) -> TemperaturePerEntropy[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> TemperaturePerEntropy[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: TemperaturePerEntropy[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[TemperatureKind, EntropyKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[TemperatureKind, EntropyKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> TemperaturePerEntropy[V, S]: ...
    @overload
    def __rmul__(
        self: TemperaturePerEntropy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TemperaturePerEntropy[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: TemperaturePerEntropy[float, S], other: W, /
    ) -> TemperaturePerEntropy[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> TemperaturePerEntropy[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: TemperaturePerEntropy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TemperaturePerEntropy[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: TemperaturePerEntropy[float, S], other: W, /
    ) -> TemperaturePerEntropy[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> TemperaturePerEntropy[V, S]: ...
    @override
    def item(self) -> TemperaturePerEntropy[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[TemperatureKind, EntropyKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: TemperaturePerEntropy[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureKind, EntropyKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: TemperaturePerEntropy[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[TemperatureKind, EntropyKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[TemperatureKind, EntropyKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: TemperaturePerEntropy[float, S],
        other: Quantity[Div[TemperatureKind, EntropyKind], W, S],
        /,
    ) -> TemperaturePerEntropy[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[TemperatureKind, EntropyKind], V, S]
        | Quantity[Div[TemperatureKind, EntropyKind], float, S],
        /,
    ) -> TemperaturePerEntropy[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: TemperaturePerEntropy[float, S],
        other: Quantity[Div[TemperatureKind, EntropyKind], W, S],
        /,
    ) -> TemperaturePerEntropy[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[TemperatureKind, EntropyKind], V, S]
        | Quantity[Div[TemperatureKind, EntropyKind], float, S],
        /,
    ) -> TemperaturePerEntropy[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> TemperaturePerEntropy[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> TemperaturePerEntropy[W, S]: ...
