# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._constants.TemperatureRate import _TemperatureRateConstant
from quantype._constants.Time import _TimeConstant
from quantype._generated import (
    Dimensionless,
    Frequency,
    InverseTime,
    TemperatureRate,
    Time,
)
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    InverseTimeKind,
    Mul,
    TemperatureRateKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class TemperatureRateInverseTime(
    Quantity[Mul[TemperatureRateKind, InverseTimeKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: TemperatureRateInverseTime[float, S], other: Time[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def __mul__(
        self, other: Time[V, S] | Time[float, S] | _TimeConstant, /
    ) -> TemperatureRate[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> TemperatureRateInverseTime[V, S]: ...
    @overload
    def __mul__(
        self: TemperatureRateInverseTime[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperatureRateInverseTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: TemperatureRateInverseTime[float, S], other: W, /
    ) -> TemperatureRateInverseTime[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> TemperatureRateInverseTime[V, S]: ...
    @overload
    def __mul__[K, W](
        self: TemperatureRateInverseTime[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[TemperatureRateKind, InverseTimeKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[TemperatureRateKind, InverseTimeKind], K], V, S]: ...
    def _rmul_Time_f(self, other: Time[float, S], /) -> TemperatureRate[V, S]: ...
    @overload
    def _rmul_Time[W](
        self: TemperatureRateInverseTime[float, S], other: Time[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def _rmul_Time(self, other: Time[V, S], /) -> TemperatureRate[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: TemperatureRateInverseTime[float, S], other: TemperatureRate[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: TemperatureRate[V, S]
        | TemperatureRate[float, S]
        | _TemperatureRateConstant,
        /,
    ) -> InverseTime[V, S]: ...
    @overload
    def __truediv__[W](
        self: TemperatureRateInverseTime[float, S], other: Frequency[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def __truediv__(
        self, other: Frequency[V, S] | Frequency[float, S] | _FrequencyConstant, /
    ) -> TemperatureRate[V, S]: ...
    @overload
    def __truediv__[W](
        self: TemperatureRateInverseTime[float, S], other: InverseTime[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def __truediv__(
        self, other: InverseTime[V, S] | InverseTime[float, S] | _InverseTimeConstant, /
    ) -> TemperatureRate[V, S]: ...
    @overload
    def __truediv__[W](
        self: TemperatureRateInverseTime[float, S],
        other: TemperatureRateInverseTime[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: TemperatureRateInverseTime[V, S] | TemperatureRateInverseTime[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> TemperatureRateInverseTime[V, S]: ...
    @overload
    def __truediv__(
        self: TemperatureRateInverseTime[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperatureRateInverseTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: TemperatureRateInverseTime[float, S], other: W, /
    ) -> TemperatureRateInverseTime[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> TemperatureRateInverseTime[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: TemperatureRateInverseTime[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[TemperatureRateKind, InverseTimeKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[TemperatureRateKind, InverseTimeKind], K], V, S]: ...
    def _rtruediv_TemperatureRate_f(
        self, other: TemperatureRate[float, S], /
    ) -> Time[V, S]: ...
    @overload
    def _rtruediv_TemperatureRate[W](
        self: TemperatureRateInverseTime[float, S], other: TemperatureRate[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def _rtruediv_TemperatureRate(
        self, other: TemperatureRate[V, S], /
    ) -> Time[V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> TemperatureRateInverseTime[V, S]: ...
    @overload
    def __rmul__(
        self: TemperatureRateInverseTime[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperatureRateInverseTime[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: TemperatureRateInverseTime[float, S], other: W, /
    ) -> TemperatureRateInverseTime[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> TemperatureRateInverseTime[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[TemperatureRateKind, InverseTimeKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: TemperatureRateInverseTime[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Mul[TemperatureRateKind, InverseTimeKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: TemperatureRateInverseTime[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[TemperatureRateKind, InverseTimeKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[TemperatureRateKind, InverseTimeKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: TemperatureRateInverseTime[float, S],
        other: Quantity[Mul[TemperatureRateKind, InverseTimeKind], W, S],
        /,
    ) -> TemperatureRateInverseTime[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[TemperatureRateKind, InverseTimeKind], V, S]
        | Quantity[Mul[TemperatureRateKind, InverseTimeKind], float, S],
        /,
    ) -> TemperatureRateInverseTime[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: TemperatureRateInverseTime[float, S],
        other: Quantity[Mul[TemperatureRateKind, InverseTimeKind], W, S],
        /,
    ) -> TemperatureRateInverseTime[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[TemperatureRateKind, InverseTimeKind], V, S]
        | Quantity[Mul[TemperatureRateKind, InverseTimeKind], float, S],
        /,
    ) -> TemperatureRateInverseTime[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> TemperatureRateInverseTime[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> TemperatureRateInverseTime[W, S]: ...
