# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Acceleration import _AccelerationConstant
from quantype._constants.Velocity import _VelocityConstant
from quantype._generated import (
    Acceleration,
    Dimensionless,
    TemperatureDifference,
    TemperatureRate,
    Velocity,
)
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import (
    AccelerationKind,
    DimensionlessKind,
    Div,
    Mul,
    TemperatureRateKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class TemperatureRatePerAcceleration(
    Quantity[Div[TemperatureRateKind, AccelerationKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: TemperatureRatePerAcceleration[float, S], other: Velocity[W, S], /
    ) -> TemperatureDifference[W, S]: ...
    @overload
    def __mul__(
        self, other: Velocity[V, S] | Velocity[float, S] | _VelocityConstant, /
    ) -> TemperatureDifference[V, S]: ...
    @overload
    def __mul__[W](
        self: TemperatureRatePerAcceleration[float, S], other: Acceleration[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def __mul__(
        self,
        other: Acceleration[V, S] | Acceleration[float, S] | _AccelerationConstant,
        /,
    ) -> TemperatureRate[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> TemperatureRatePerAcceleration[V, S]: ...
    @overload
    def __mul__(
        self: TemperatureRatePerAcceleration[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperatureRatePerAcceleration[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: TemperatureRatePerAcceleration[float, S], other: W, /
    ) -> TemperatureRatePerAcceleration[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> TemperatureRatePerAcceleration[V, S]: ...
    @overload
    def __mul__[K, W](
        self: TemperatureRatePerAcceleration[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[TemperatureRateKind, AccelerationKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[TemperatureRateKind, AccelerationKind], K], V, S]: ...
    def _rmul_Velocity_f(
        self, other: Velocity[float, S], /
    ) -> TemperatureDifference[V, S]: ...
    @overload
    def _rmul_Velocity[W](
        self: TemperatureRatePerAcceleration[float, S], other: Velocity[W, S], /
    ) -> TemperatureDifference[W, S]: ...
    @overload
    def _rmul_Velocity(
        self, other: Velocity[V, S], /
    ) -> TemperatureDifference[V, S]: ...
    def _rmul_Acceleration_f(
        self, other: Acceleration[float, S], /
    ) -> TemperatureRate[V, S]: ...
    @overload
    def _rmul_Acceleration[W](
        self: TemperatureRatePerAcceleration[float, S], other: Acceleration[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def _rmul_Acceleration(
        self, other: Acceleration[V, S], /
    ) -> TemperatureRate[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: TemperatureRatePerAcceleration[float, S],
        other: TemperatureRatePerAcceleration[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: TemperatureRatePerAcceleration[V, S]
        | TemperatureRatePerAcceleration[float, S],
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(
        self, other: _Scalar, /
    ) -> TemperatureRatePerAcceleration[V, S]: ...
    @overload
    def __truediv__(
        self: TemperatureRatePerAcceleration[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperatureRatePerAcceleration[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: TemperatureRatePerAcceleration[float, S], other: W, /
    ) -> TemperatureRatePerAcceleration[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> TemperatureRatePerAcceleration[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: TemperatureRatePerAcceleration[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[TemperatureRateKind, AccelerationKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[TemperatureRateKind, AccelerationKind], K], V, S]: ...
    def _rtruediv_TemperatureDifference_f(
        self, other: TemperatureDifference[float, S], /
    ) -> Velocity[V, S]: ...
    @overload
    def _rtruediv_TemperatureDifference[W](
        self: TemperatureRatePerAcceleration[float, S],
        other: TemperatureDifference[W, S],
        /,
    ) -> Velocity[W, S]: ...
    @overload
    def _rtruediv_TemperatureDifference(
        self, other: TemperatureDifference[V, S], /
    ) -> Velocity[V, S]: ...
    def _rtruediv_TemperatureRate_f(
        self, other: TemperatureRate[float, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    def _rtruediv_TemperatureRate[W](
        self: TemperatureRatePerAcceleration[float, S], other: TemperatureRate[W, S], /
    ) -> Acceleration[W, S]: ...
    @overload
    def _rtruediv_TemperatureRate(
        self, other: TemperatureRate[V, S], /
    ) -> Acceleration[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: TemperatureRatePerAcceleration[float, S], other: Velocity[W, S], /
    ) -> TemperatureDifference[W, S]: ...
    @overload
    def __matmul__(
        self, other: Velocity[V, S] | Velocity[float, S], /
    ) -> TemperatureDifference[V, S]: ...
    @overload
    def __matmul__[W](
        self: TemperatureRatePerAcceleration[float, S], other: Acceleration[W, S], /
    ) -> TemperatureRate[W, S]: ...
    @overload
    def __matmul__(
        self, other: Acceleration[V, S] | Acceleration[float, S], /
    ) -> TemperatureRate[V, S]: ...
    @overload
    def __matmul__(
        self: TemperatureRatePerAcceleration[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperatureRatePerAcceleration[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: TemperatureRatePerAcceleration[float, S], other: W, /
    ) -> TemperatureRatePerAcceleration[W, S]: ...
    @overload
    def __matmul__(
        self, other: _Numerical, /
    ) -> TemperatureRatePerAcceleration[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: TemperatureRatePerAcceleration[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[TemperatureRateKind, AccelerationKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[TemperatureRateKind, AccelerationKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> TemperatureRatePerAcceleration[V, S]: ...
    @overload
    def __rmul__(
        self: TemperatureRatePerAcceleration[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperatureRatePerAcceleration[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: TemperatureRatePerAcceleration[float, S], other: W, /
    ) -> TemperatureRatePerAcceleration[W, S]: ...
    @overload
    def __rmul__(
        self, other: _Numerical, /
    ) -> TemperatureRatePerAcceleration[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: TemperatureRatePerAcceleration[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperatureRatePerAcceleration[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: TemperatureRatePerAcceleration[float, S], other: W, /
    ) -> TemperatureRatePerAcceleration[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> TemperatureRatePerAcceleration[V, S]: ...
    @override
    def item(self) -> TemperatureRatePerAcceleration[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureRateKind, AccelerationKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: TemperatureRatePerAcceleration[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureRateKind, AccelerationKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: TemperatureRatePerAcceleration[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureRateKind, AccelerationKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureRateKind, AccelerationKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: TemperatureRatePerAcceleration[float, S],
        other: Quantity[Div[TemperatureRateKind, AccelerationKind], W, S],
        /,
    ) -> TemperatureRatePerAcceleration[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[TemperatureRateKind, AccelerationKind], V, S]
        | Quantity[Div[TemperatureRateKind, AccelerationKind], float, S],
        /,
    ) -> TemperatureRatePerAcceleration[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: TemperatureRatePerAcceleration[float, S],
        other: Quantity[Div[TemperatureRateKind, AccelerationKind], W, S],
        /,
    ) -> TemperatureRatePerAcceleration[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[TemperatureRateKind, AccelerationKind], V, S]
        | Quantity[Div[TemperatureRateKind, AccelerationKind], float, S],
        /,
    ) -> TemperatureRatePerAcceleration[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> TemperatureRatePerAcceleration[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> TemperatureRatePerAcceleration[W, S]: ...
