# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.Magnetization import _MagnetizationConstant
from quantype._constants.Temperature import _TemperatureConstant
from quantype._generated import Dimensionless, Magnetization, Temperature
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    MagnetizationKind,
    Mul,
    TemperatureKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class TemperaturePerMagnetization(
    Quantity[Div[TemperatureKind, MagnetizationKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: TemperaturePerMagnetization[float, S], other: Magnetization[W, S], /
    ) -> Temperature[W, S]: ...
    @overload
    def __mul__(
        self,
        other: Magnetization[V, S] | Magnetization[float, S] | _MagnetizationConstant,
        /,
    ) -> Temperature[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> TemperaturePerMagnetization[V, S]: ...
    @overload
    def __mul__(
        self: TemperaturePerMagnetization[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperaturePerMagnetization[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: TemperaturePerMagnetization[float, S], other: W, /
    ) -> TemperaturePerMagnetization[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> TemperaturePerMagnetization[V, S]: ...
    @overload
    def __mul__[K, W](
        self: TemperaturePerMagnetization[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[TemperatureKind, MagnetizationKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[TemperatureKind, MagnetizationKind], K], V, S]: ...
    def _rmul_Magnetization_f(
        self, other: Magnetization[float, S], /
    ) -> Temperature[V, S]: ...
    @overload
    def _rmul_Magnetization[W](
        self: TemperaturePerMagnetization[float, S], other: Magnetization[W, S], /
    ) -> Temperature[W, S]: ...
    @overload
    def _rmul_Magnetization(
        self, other: Magnetization[V, S], /
    ) -> Temperature[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: TemperaturePerMagnetization[float, S],
        other: TemperaturePerMagnetization[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: TemperaturePerMagnetization[V, S]
        | TemperaturePerMagnetization[float, S]
        | _TemperaturePerMagnetizationConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> TemperaturePerMagnetization[V, S]: ...
    @overload
    def __truediv__(
        self: TemperaturePerMagnetization[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperaturePerMagnetization[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: TemperaturePerMagnetization[float, S], other: W, /
    ) -> TemperaturePerMagnetization[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> TemperaturePerMagnetization[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: TemperaturePerMagnetization[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[TemperatureKind, MagnetizationKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[TemperatureKind, MagnetizationKind], K], V, S]: ...
    def _rtruediv_Temperature_f(
        self, other: Temperature[float, S], /
    ) -> Magnetization[V, S]: ...
    @overload
    def _rtruediv_Temperature[W](
        self: TemperaturePerMagnetization[float, S], other: Temperature[W, S], /
    ) -> Magnetization[W, S]: ...
    @overload
    def _rtruediv_Temperature(
        self, other: Temperature[V, S], /
    ) -> Magnetization[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: TemperaturePerMagnetization[float, S], other: Magnetization[W, S], /
    ) -> Temperature[W, S]: ...
    @overload
    def __matmul__(
        self, other: Magnetization[V, S] | Magnetization[float, S], /
    ) -> Temperature[V, S]: ...
    @overload
    def __matmul__(
        self: TemperaturePerMagnetization[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperaturePerMagnetization[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: TemperaturePerMagnetization[float, S], other: W, /
    ) -> TemperaturePerMagnetization[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> TemperaturePerMagnetization[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: TemperaturePerMagnetization[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[TemperatureKind, MagnetizationKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[TemperatureKind, MagnetizationKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> TemperaturePerMagnetization[V, S]: ...
    @overload
    def __rmul__(
        self: TemperaturePerMagnetization[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperaturePerMagnetization[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: TemperaturePerMagnetization[float, S], other: W, /
    ) -> TemperaturePerMagnetization[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> TemperaturePerMagnetization[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: TemperaturePerMagnetization[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> TemperaturePerMagnetization[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: TemperaturePerMagnetization[float, S], other: W, /
    ) -> TemperaturePerMagnetization[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> TemperaturePerMagnetization[V, S]: ...
    @override
    def item(self) -> TemperaturePerMagnetization[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureKind, MagnetizationKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: TemperaturePerMagnetization[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureKind, MagnetizationKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: TemperaturePerMagnetization[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureKind, MagnetizationKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[TemperatureKind, MagnetizationKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: TemperaturePerMagnetization[float, S],
        other: Quantity[Div[TemperatureKind, MagnetizationKind], W, S],
        /,
    ) -> TemperaturePerMagnetization[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[TemperatureKind, MagnetizationKind], V, S]
        | Quantity[Div[TemperatureKind, MagnetizationKind], float, S],
        /,
    ) -> TemperaturePerMagnetization[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: TemperaturePerMagnetization[float, S],
        other: Quantity[Div[TemperatureKind, MagnetizationKind], W, S],
        /,
    ) -> TemperaturePerMagnetization[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[TemperatureKind, MagnetizationKind], V, S]
        | Quantity[Div[TemperatureKind, MagnetizationKind], float, S],
        /,
    ) -> TemperaturePerMagnetization[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> TemperaturePerMagnetization[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> TemperaturePerMagnetization[W, S]: ...

class _TemperaturePerMagnetizationConstant(
    Constant[Div[TemperatureKind, MagnetizationKind]]
):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> TemperaturePerMagnetization[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[TemperatureKind, MagnetizationKind]]
    ) -> TemperaturePerMagnetization[float]: ...
    @overload
    @override
    def __mul__(self, other: _MagnetizationConstant, /) -> _TemperatureConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[TemperatureKind, MagnetizationKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _TemperaturePerMagnetizationConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: Magnetization[W, T], /
    ) -> Temperature[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[TemperatureKind, MagnetizationKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _TemperaturePerMagnetizationConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[TemperatureKind, MagnetizationKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _TemperaturePerMagnetizationConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: TemperaturePerMagnetization[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[TemperatureKind, MagnetizationKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _TemperaturePerMagnetizationConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[TemperatureKind, MagnetizationKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[TemperatureKind, MagnetizationKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[TemperatureKind, MagnetizationKind]], W, T]: ...
    def _rmul_Magnetization_f[T: UnitSystem](
        self, other: Magnetization[float, T], /
    ) -> Temperature[float, T]: ...
    def _rmul_Magnetization[W, T: UnitSystem](
        self, other: Magnetization[W, T], /
    ) -> Temperature[W, T]: ...
    def _cmul_Magnetization(
        self, other: _MagnetizationConstant, /
    ) -> _TemperatureConstant: ...
    def _rtruediv_Temperature_f[T: UnitSystem](
        self, other: Temperature[float, T], /
    ) -> Magnetization[float, T]: ...
    def _rtruediv_Temperature[W, T: UnitSystem](
        self, other: Temperature[W, T], /
    ) -> Magnetization[W, T]: ...
    def _ctruediv_Temperature(
        self, other: _TemperatureConstant, /
    ) -> _MagnetizationConstant: ...
