# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Area import _AreaConstant
from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.Time import _TimeConstant
from quantype._generated import Area, Dimensionless, Time
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import AreaKind, DimensionlessKind, Div, Mul, TimeKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class TimePerArea(Quantity[Div[TimeKind, AreaKind], V, S]):
    @overload
    @override
    def __mul__[W](self: TimePerArea[float, S], other: Area[W, S], /) -> Time[W, S]: ...
    @overload
    def __mul__(
        self, other: Area[V, S] | Area[float, S] | _AreaConstant, /
    ) -> Time[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> TimePerArea[V, S]: ...
    @overload
    def __mul__(
        self: TimePerArea[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimePerArea[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: TimePerArea[float, S], other: W, /
    ) -> TimePerArea[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> TimePerArea[V, S]: ...
    @overload
    def __mul__[K, W](
        self: TimePerArea[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[TimeKind, AreaKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[TimeKind, AreaKind], K], V, S]: ...
    def _rmul_Area_f(self, other: Area[float, S], /) -> Time[V, S]: ...
    @overload
    def _rmul_Area[W](
        self: TimePerArea[float, S], other: Area[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def _rmul_Area(self, other: Area[V, S], /) -> Time[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: TimePerArea[float, S], other: TimePerArea[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: TimePerArea[V, S] | TimePerArea[float, S] | _TimePerAreaConstant, /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> TimePerArea[V, S]: ...
    @overload
    def __truediv__(
        self: TimePerArea[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimePerArea[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: TimePerArea[float, S], other: W, /
    ) -> TimePerArea[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> TimePerArea[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: TimePerArea[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[TimeKind, AreaKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[TimeKind, AreaKind], K], V, S]: ...
    def _rtruediv_Time_f(self, other: Time[float, S], /) -> Area[V, S]: ...
    @overload
    def _rtruediv_Time[W](
        self: TimePerArea[float, S], other: Time[W, S], /
    ) -> Area[W, S]: ...
    @overload
    def _rtruediv_Time(self, other: Time[V, S], /) -> Area[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: TimePerArea[float, S], other: Area[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def __matmul__(self, other: Area[V, S] | Area[float, S], /) -> Time[V, S]: ...
    @overload
    def __matmul__(
        self: TimePerArea[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimePerArea[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: TimePerArea[float, S], other: W, /
    ) -> TimePerArea[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> TimePerArea[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: TimePerArea[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[TimeKind, AreaKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[TimeKind, AreaKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> TimePerArea[V, S]: ...
    @overload
    def __rmul__(
        self: TimePerArea[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimePerArea[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: TimePerArea[float, S], other: W, /
    ) -> TimePerArea[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> TimePerArea[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: TimePerArea[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimePerArea[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: TimePerArea[float, S], other: W, /
    ) -> TimePerArea[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> TimePerArea[V, S]: ...
    @override
    def item(self) -> TimePerArea[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[TimeKind, AreaKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: TimePerArea[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[TimeKind, AreaKind]], npt.NDArray[np.float64], S
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: TimePerArea[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[TimeKind, AreaKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[TimeKind, AreaKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: TimePerArea[float, S], other: Quantity[Div[TimeKind, AreaKind], W, S], /
    ) -> TimePerArea[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[TimeKind, AreaKind], V, S]
        | Quantity[Div[TimeKind, AreaKind], float, S],
        /,
    ) -> TimePerArea[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: TimePerArea[float, S], other: Quantity[Div[TimeKind, AreaKind], W, S], /
    ) -> TimePerArea[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[TimeKind, AreaKind], V, S]
        | Quantity[Div[TimeKind, AreaKind], float, S],
        /,
    ) -> TimePerArea[V, S]: ...
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> TimePerArea[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> TimePerArea[W, S]: ...

class _TimePerAreaConstant(Constant[Div[TimeKind, AreaKind]]):
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> TimePerArea[float, T]: ...
    @override
    def to(self, unit: Unit[Div[TimeKind, AreaKind]]) -> TimePerArea[float]: ...
    @overload
    @override
    def __mul__(self, other: _AreaConstant, /) -> _TimeConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[TimeKind, AreaKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _TimePerAreaConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Area[W, T], /) -> Time[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[TimeKind, AreaKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(self, other: _TimePerAreaConstant, /) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[TimeKind, AreaKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _TimePerAreaConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: TimePerArea[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[TimeKind, AreaKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _TimePerAreaConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[TimeKind, AreaKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[Div[DimensionlessKind, Div[TimeKind, AreaKind]]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[TimeKind, AreaKind]], W, T]: ...
    def _rmul_Area_f[T: UnitSystem](
        self, other: Area[float, T], /
    ) -> Time[float, T]: ...
    def _rmul_Area[W, T: UnitSystem](self, other: Area[W, T], /) -> Time[W, T]: ...
    def _cmul_Area(self, other: _AreaConstant, /) -> _TimeConstant: ...
    def _rtruediv_Time_f[T: UnitSystem](
        self, other: Time[float, T], /
    ) -> Area[float, T]: ...
    def _rtruediv_Time[W, T: UnitSystem](self, other: Time[W, T], /) -> Area[W, T]: ...
    def _ctruediv_Time(self, other: _TimeConstant, /) -> _AreaConstant: ...
