# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Angle import _AngleConstant
from quantype._constants.Frequency import _FrequencyConstant
from quantype._constants.InverseTime import _InverseTimeConstant
from quantype._constants.Time import _TimeConstant
from quantype._generated import Angle, Dimensionless, Frequency, InverseTime, Time
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import AngleKind, DimensionlessKind, Div, Mul, TimeKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class TimeAngle(Quantity[Mul[TimeKind, AngleKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: TimeAngle[float, S], other: Frequency[W, S], /
    ) -> Angle[W, S]: ...
    @overload
    def __mul__(
        self, other: Frequency[V, S] | Frequency[float, S] | _FrequencyConstant, /
    ) -> Angle[V, S]: ...
    @overload
    def __mul__[W](
        self: TimeAngle[float, S], other: InverseTime[W, S], /
    ) -> Angle[W, S]: ...
    @overload
    def __mul__(
        self, other: InverseTime[V, S] | InverseTime[float, S] | _InverseTimeConstant, /
    ) -> Angle[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> TimeAngle[V, S]: ...
    @overload
    def __mul__(
        self: TimeAngle[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimeAngle[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: TimeAngle[float, S], other: W, /
    ) -> TimeAngle[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> TimeAngle[V, S]: ...
    @overload
    def __mul__[K, W](
        self: TimeAngle[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[TimeKind, AngleKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[TimeKind, AngleKind], K], V, S]: ...
    def _rmul_Frequency_f(self, other: Frequency[float, S], /) -> Angle[V, S]: ...
    @overload
    def _rmul_Frequency[W](
        self: TimeAngle[float, S], other: Frequency[W, S], /
    ) -> Angle[W, S]: ...
    @overload
    def _rmul_Frequency(self, other: Frequency[V, S], /) -> Angle[V, S]: ...
    def _rmul_InverseTime_f(self, other: InverseTime[float, S], /) -> Angle[V, S]: ...
    @overload
    def _rmul_InverseTime[W](
        self: TimeAngle[float, S], other: InverseTime[W, S], /
    ) -> Angle[W, S]: ...
    @overload
    def _rmul_InverseTime(self, other: InverseTime[V, S], /) -> Angle[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: TimeAngle[float, S], other: Time[W, S], /
    ) -> Angle[W, S]: ...
    @overload
    def __truediv__(
        self, other: Time[V, S] | Time[float, S] | _TimeConstant, /
    ) -> Angle[V, S]: ...
    @overload
    def __truediv__[W](
        self: TimeAngle[float, S], other: Angle[W, S], /
    ) -> Time[W, S]: ...
    @overload
    def __truediv__(
        self, other: Angle[V, S] | Angle[float, S] | _AngleConstant, /
    ) -> Time[V, S]: ...
    @overload
    def __truediv__[W](
        self: TimeAngle[float, S], other: TimeAngle[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: TimeAngle[V, S] | TimeAngle[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> TimeAngle[V, S]: ...
    @overload
    def __truediv__(
        self: TimeAngle[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimeAngle[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: TimeAngle[float, S], other: W, /
    ) -> TimeAngle[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> TimeAngle[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: TimeAngle[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[TimeKind, AngleKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[TimeKind, AngleKind], K], V, S]: ...
    def _rtruediv_Angle_f(self, other: Angle[float, S], /) -> InverseTime[V, S]: ...
    @overload
    def _rtruediv_Angle[W](
        self: TimeAngle[float, S], other: Angle[W, S], /
    ) -> InverseTime[W, S]: ...
    @overload
    def _rtruediv_Angle(self, other: Angle[V, S], /) -> InverseTime[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: TimeAngle[float, S], other: Frequency[W, S], /
    ) -> Angle[W, S]: ...
    @overload
    def __matmul__(
        self, other: Frequency[V, S] | Frequency[float, S], /
    ) -> Angle[V, S]: ...
    @overload
    def __matmul__[W](
        self: TimeAngle[float, S], other: InverseTime[W, S], /
    ) -> Angle[W, S]: ...
    @overload
    def __matmul__(
        self, other: InverseTime[V, S] | InverseTime[float, S], /
    ) -> Angle[V, S]: ...
    @overload
    def __matmul__(
        self: TimeAngle[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimeAngle[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: TimeAngle[float, S], other: W, /
    ) -> TimeAngle[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> TimeAngle[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: TimeAngle[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[TimeKind, AngleKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[TimeKind, AngleKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> TimeAngle[V, S]: ...
    @overload
    def __rmul__(
        self: TimeAngle[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimeAngle[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: TimeAngle[float, S], other: W, /
    ) -> TimeAngle[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> TimeAngle[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: TimeAngle[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> TimeAngle[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: TimeAngle[float, S], other: W, /
    ) -> TimeAngle[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> TimeAngle[V, S]: ...
    @override
    def item(self) -> TimeAngle[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Mul[TimeKind, AngleKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: TimeAngle[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[TimeKind, AngleKind]], npt.NDArray[np.float64], S
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: TimeAngle[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Mul[TimeKind, AngleKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Mul[TimeKind, AngleKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: TimeAngle[float, S], other: Quantity[Mul[TimeKind, AngleKind], W, S], /
    ) -> TimeAngle[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[TimeKind, AngleKind], V, S]
        | Quantity[Mul[TimeKind, AngleKind], float, S],
        /,
    ) -> TimeAngle[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: TimeAngle[float, S], other: Quantity[Mul[TimeKind, AngleKind], W, S], /
    ) -> TimeAngle[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[TimeKind, AngleKind], V, S]
        | Quantity[Mul[TimeKind, AngleKind], float, S],
        /,
    ) -> TimeAngle[V, S]: ...
    @override
    def to_system[T: UnitSystem](self, system: type[T]) -> TimeAngle[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> TimeAngle[W, S]: ...
