# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.ElectronCount import _ElectronCountConstant
from quantype._constants.Velocity import _VelocityConstant
from quantype._generated import Dimensionless, ElectronCount, Velocity
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, ElectronCountKind, Mul, VelocityKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class VelocityElectronCount(Quantity[Mul[VelocityKind, ElectronCountKind], V, S]):
    @overload
    @override
    def __mul__(self, other: _Scalar, /) -> VelocityElectronCount[V, S]: ...
    @overload
    def __mul__(
        self: VelocityElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> VelocityElectronCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: VelocityElectronCount[float, S], other: W, /
    ) -> VelocityElectronCount[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> VelocityElectronCount[V, S]: ...
    @overload
    def __mul__[K, W](
        self: VelocityElectronCount[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[VelocityKind, ElectronCountKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[VelocityKind, ElectronCountKind], K], V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: VelocityElectronCount[float, S], other: Velocity[W, S], /
    ) -> ElectronCount[W, S]: ...
    @overload
    def __truediv__(
        self, other: Velocity[V, S] | Velocity[float, S] | _VelocityConstant, /
    ) -> ElectronCount[V, S]: ...
    @overload
    def __truediv__[W](
        self: VelocityElectronCount[float, S], other: ElectronCount[W, S], /
    ) -> Velocity[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: ElectronCount[V, S] | ElectronCount[float, S] | _ElectronCountConstant,
        /,
    ) -> Velocity[V, S]: ...
    @overload
    def __truediv__[W](
        self: VelocityElectronCount[float, S], other: VelocityElectronCount[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: VelocityElectronCount[V, S] | VelocityElectronCount[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> VelocityElectronCount[V, S]: ...
    @overload
    def __truediv__(
        self: VelocityElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> VelocityElectronCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: VelocityElectronCount[float, S], other: W, /
    ) -> VelocityElectronCount[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> VelocityElectronCount[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: VelocityElectronCount[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Mul[VelocityKind, ElectronCountKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Mul[VelocityKind, ElectronCountKind], K], V, S]: ...
    @overload
    @override
    def __matmul__(
        self: VelocityElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> VelocityElectronCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: VelocityElectronCount[float, S], other: W, /
    ) -> VelocityElectronCount[W, S]: ...
    @overload
    def __matmul__(self, other: _Numerical, /) -> VelocityElectronCount[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: VelocityElectronCount[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Mul[VelocityKind, ElectronCountKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Mul[VelocityKind, ElectronCountKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> VelocityElectronCount[V, S]: ...
    @overload
    def __rmul__(
        self: VelocityElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> VelocityElectronCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: VelocityElectronCount[float, S], other: W, /
    ) -> VelocityElectronCount[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> VelocityElectronCount[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: VelocityElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> VelocityElectronCount[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: VelocityElectronCount[float, S], other: W, /
    ) -> VelocityElectronCount[W, S]: ...
    @overload
    def __rmatmul__(self, other: _Numerical, /) -> VelocityElectronCount[V, S]: ...
    @override
    def item(self) -> VelocityElectronCount[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[VelocityKind, ElectronCountKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: VelocityElectronCount[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[VelocityKind, ElectronCountKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: VelocityElectronCount[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[VelocityKind, ElectronCountKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Mul[VelocityKind, ElectronCountKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: VelocityElectronCount[float, S],
        other: Quantity[Mul[VelocityKind, ElectronCountKind], W, S],
        /,
    ) -> VelocityElectronCount[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Mul[VelocityKind, ElectronCountKind], V, S]
        | Quantity[Mul[VelocityKind, ElectronCountKind], float, S],
        /,
    ) -> VelocityElectronCount[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: VelocityElectronCount[float, S],
        other: Quantity[Mul[VelocityKind, ElectronCountKind], W, S],
        /,
    ) -> VelocityElectronCount[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Mul[VelocityKind, ElectronCountKind], V, S]
        | Quantity[Mul[VelocityKind, ElectronCountKind], float, S],
        /,
    ) -> VelocityElectronCount[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> VelocityElectronCount[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> VelocityElectronCount[W, S]: ...
