# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Momentum import _MomentumConstant
from quantype._constants.Pressure import _PressureConstant
from quantype._generated import Dimensionless, Momentum, Pressure, Velocity, Volume
from quantype.core import Quantity, _Numerical, _Scalar
from quantype.kinds import DimensionlessKind, Div, Mul, PressureKind, VelocityKind
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class VelocityPerPressure(Quantity[Div[VelocityKind, PressureKind], V, S]):
    @overload
    @override
    def __mul__[W](
        self: VelocityPerPressure[float, S], other: Pressure[W, S], /
    ) -> Velocity[W, S]: ...
    @overload
    def __mul__(
        self, other: Pressure[V, S] | Pressure[float, S] | _PressureConstant, /
    ) -> Velocity[V, S]: ...
    @overload
    def __mul__[W](
        self: VelocityPerPressure[float, S], other: Momentum[W, S], /
    ) -> Volume[W, S]: ...
    @overload
    def __mul__(
        self, other: Momentum[V, S] | Momentum[float, S] | _MomentumConstant, /
    ) -> Volume[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> VelocityPerPressure[V, S]: ...
    @overload
    def __mul__(
        self: VelocityPerPressure[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> VelocityPerPressure[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: VelocityPerPressure[float, S], other: W, /
    ) -> VelocityPerPressure[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> VelocityPerPressure[V, S]: ...
    @overload
    def __mul__[K, W](
        self: VelocityPerPressure[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[VelocityKind, PressureKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[VelocityKind, PressureKind], K], V, S]: ...
    def _rmul_Pressure_f(self, other: Pressure[float, S], /) -> Velocity[V, S]: ...
    @overload
    def _rmul_Pressure[W](
        self: VelocityPerPressure[float, S], other: Pressure[W, S], /
    ) -> Velocity[W, S]: ...
    @overload
    def _rmul_Pressure(self, other: Pressure[V, S], /) -> Velocity[V, S]: ...
    def _rmul_Momentum_f(self, other: Momentum[float, S], /) -> Volume[V, S]: ...
    @overload
    def _rmul_Momentum[W](
        self: VelocityPerPressure[float, S], other: Momentum[W, S], /
    ) -> Volume[W, S]: ...
    @overload
    def _rmul_Momentum(self, other: Momentum[V, S], /) -> Volume[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: VelocityPerPressure[float, S], other: VelocityPerPressure[W, S], /
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self, other: VelocityPerPressure[V, S] | VelocityPerPressure[float, S], /
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> VelocityPerPressure[V, S]: ...
    @overload
    def __truediv__(
        self: VelocityPerPressure[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> VelocityPerPressure[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: VelocityPerPressure[float, S], other: W, /
    ) -> VelocityPerPressure[W, S]: ...
    @overload
    def __truediv__(self, other: _Numerical, /) -> VelocityPerPressure[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: VelocityPerPressure[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[VelocityKind, PressureKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[VelocityKind, PressureKind], K], V, S]: ...
    def _rtruediv_Volume_f(self, other: Volume[float, S], /) -> Momentum[V, S]: ...
    @overload
    def _rtruediv_Volume[W](
        self: VelocityPerPressure[float, S], other: Volume[W, S], /
    ) -> Momentum[W, S]: ...
    @overload
    def _rtruediv_Volume(self, other: Volume[V, S], /) -> Momentum[V, S]: ...
    def _rtruediv_Velocity_f(self, other: Velocity[float, S], /) -> Pressure[V, S]: ...
    @overload
    def _rtruediv_Velocity[W](
        self: VelocityPerPressure[float, S], other: Velocity[W, S], /
    ) -> Pressure[W, S]: ...
    @overload
    def _rtruediv_Velocity(self, other: Velocity[V, S], /) -> Pressure[V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> VelocityPerPressure[V, S]: ...
    @overload
    def __rmul__(
        self: VelocityPerPressure[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> VelocityPerPressure[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: VelocityPerPressure[float, S], other: W, /
    ) -> VelocityPerPressure[W, S]: ...
    @overload
    def __rmul__(self, other: _Numerical, /) -> VelocityPerPressure[V, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, Div[VelocityKind, PressureKind]], V, S]: ...
    @overload
    def __rtruediv__(
        self: VelocityPerPressure[float, S], other: npt.NDArray[np.integer[Any]], /
    ) -> Quantity[
        Div[DimensionlessKind, Div[VelocityKind, PressureKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: VelocityPerPressure[float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, Div[VelocityKind, PressureKind]], W, S]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, Div[VelocityKind, PressureKind]], V, S]: ...
    @overload
    @override
    def __add__[W](
        self: VelocityPerPressure[float, S],
        other: Quantity[Div[VelocityKind, PressureKind], W, S],
        /,
    ) -> VelocityPerPressure[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[VelocityKind, PressureKind], V, S]
        | Quantity[Div[VelocityKind, PressureKind], float, S],
        /,
    ) -> VelocityPerPressure[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: VelocityPerPressure[float, S],
        other: Quantity[Div[VelocityKind, PressureKind], W, S],
        /,
    ) -> VelocityPerPressure[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[VelocityKind, PressureKind], V, S]
        | Quantity[Div[VelocityKind, PressureKind], float, S],
        /,
    ) -> VelocityPerPressure[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> VelocityPerPressure[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> VelocityPerPressure[W, S]: ...
