# Generated by quantype.codegen; do not edit.
# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
# Named operators and structural-only base operators have disjoint self types.
# mypy: disable-error-code=override
# pyright: reportIncompatibleMethodOverride=false
# pyright: reportPrivateUsage=false
# ruff: noqa: N802
from typing import Any, overload, override

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._constants.Dimensionless import _DimensionlessConstant
from quantype._constants.EnergyDensity import _EnergyDensityConstant
from quantype._constants.Entropy import _EntropyConstant
from quantype._constants.Pressure import _PressureConstant
from quantype._constants.TemperatureDifference import _TemperatureDifferenceConstant
from quantype._constants.Volume import _VolumeConstant
from quantype._generated import (
    Dimensionless,
    EnergyDensity,
    Entropy,
    Pressure,
    TemperatureDifference,
    Volume,
)
from quantype.core import Constant, Quantity, Unit, _Numerical, _Operand, _Scalar
from quantype.kinds import (
    DimensionlessKind,
    Div,
    Mul,
    TemperatureDifferenceKind,
    VolumeKind,
)
from quantype.systems import Atomistic, UnitSystem

# Public parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

class VolumePerTemperatureDifference(
    Quantity[Div[VolumeKind, TemperatureDifferenceKind], V, S]
):
    @overload
    @override
    def __mul__[W](
        self: VolumePerTemperatureDifference[float, S], other: Pressure[W, S], /
    ) -> Entropy[W, S]: ...
    @overload
    def __mul__(
        self, other: Pressure[V, S] | Pressure[float, S] | _PressureConstant, /
    ) -> Entropy[V, S]: ...
    @overload
    def __mul__[W](
        self: VolumePerTemperatureDifference[float, S],
        other: TemperatureDifference[W, S],
        /,
    ) -> Volume[W, S]: ...
    @overload
    def __mul__(
        self,
        other: TemperatureDifference[V, S]
        | TemperatureDifference[float, S]
        | _TemperatureDifferenceConstant,
        /,
    ) -> Volume[V, S]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> VolumePerTemperatureDifference[V, S]: ...
    @overload
    def __mul__(
        self: VolumePerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> VolumePerTemperatureDifference[npt.NDArray[np.float64], S]: ...
    @overload
    def __mul__[W: _Numerical](
        self: VolumePerTemperatureDifference[float, S], other: W, /
    ) -> VolumePerTemperatureDifference[W, S]: ...
    @overload
    def __mul__(self, other: _Numerical, /) -> VolumePerTemperatureDifference[V, S]: ...
    @overload
    def __mul__[K, W](
        self: VolumePerTemperatureDifference[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[VolumeKind, TemperatureDifferenceKind], K], W, S]: ...
    @overload
    def __mul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[VolumeKind, TemperatureDifferenceKind], K], V, S]: ...
    def _rmul_Pressure_f(self, other: Pressure[float, S], /) -> Entropy[V, S]: ...
    @overload
    def _rmul_Pressure[W](
        self: VolumePerTemperatureDifference[float, S], other: Pressure[W, S], /
    ) -> Entropy[W, S]: ...
    @overload
    def _rmul_Pressure(self, other: Pressure[V, S], /) -> Entropy[V, S]: ...
    def _rmul_TemperatureDifference_f(
        self, other: TemperatureDifference[float, S], /
    ) -> Volume[V, S]: ...
    @overload
    def _rmul_TemperatureDifference[W](
        self: VolumePerTemperatureDifference[float, S],
        other: TemperatureDifference[W, S],
        /,
    ) -> Volume[W, S]: ...
    @overload
    def _rmul_TemperatureDifference(
        self, other: TemperatureDifference[V, S], /
    ) -> Volume[V, S]: ...
    @overload
    @override
    def __truediv__[W](
        self: VolumePerTemperatureDifference[float, S],
        other: VolumePerTemperatureDifference[W, S],
        /,
    ) -> Dimensionless[W, S]: ...
    @overload
    def __truediv__(
        self,
        other: VolumePerTemperatureDifference[V, S]
        | VolumePerTemperatureDifference[float, S]
        | _VolumePerTemperatureDifferenceConstant,
        /,
    ) -> Dimensionless[V, S]: ...
    @overload
    def __truediv__(
        self, other: _Scalar, /
    ) -> VolumePerTemperatureDifference[V, S]: ...
    @overload
    def __truediv__(
        self: VolumePerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> VolumePerTemperatureDifference[npt.NDArray[np.float64], S]: ...
    @overload
    def __truediv__[W: _Numerical](
        self: VolumePerTemperatureDifference[float, S], other: W, /
    ) -> VolumePerTemperatureDifference[W, S]: ...
    @overload
    def __truediv__(
        self, other: _Numerical, /
    ) -> VolumePerTemperatureDifference[V, S]: ...
    @overload
    def __truediv__[K, W](
        self: VolumePerTemperatureDifference[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Div[Div[VolumeKind, TemperatureDifferenceKind], K], W, S]: ...
    @overload
    def __truediv__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Div[Div[VolumeKind, TemperatureDifferenceKind], K], V, S]: ...
    def _rtruediv_Volume_f(
        self, other: Volume[float, S], /
    ) -> TemperatureDifference[V, S]: ...
    @overload
    def _rtruediv_Volume[W](
        self: VolumePerTemperatureDifference[float, S], other: Volume[W, S], /
    ) -> TemperatureDifference[W, S]: ...
    @overload
    def _rtruediv_Volume(
        self, other: Volume[V, S], /
    ) -> TemperatureDifference[V, S]: ...
    def _rtruediv_Entropy_f(
        self, other: Entropy[float, S], /
    ) -> EnergyDensity[V, S]: ...
    @overload
    def _rtruediv_Entropy[W](
        self: VolumePerTemperatureDifference[float, S], other: Entropy[W, S], /
    ) -> EnergyDensity[W, S]: ...
    @overload
    def _rtruediv_Entropy(self, other: Entropy[V, S], /) -> EnergyDensity[V, S]: ...
    @overload
    @override
    def __matmul__[W](
        self: VolumePerTemperatureDifference[float, S], other: Pressure[W, S], /
    ) -> Entropy[W, S]: ...
    @overload
    def __matmul__(
        self, other: Pressure[V, S] | Pressure[float, S], /
    ) -> Entropy[V, S]: ...
    @overload
    def __matmul__[W](
        self: VolumePerTemperatureDifference[float, S],
        other: TemperatureDifference[W, S],
        /,
    ) -> Volume[W, S]: ...
    @overload
    def __matmul__(
        self, other: TemperatureDifference[V, S] | TemperatureDifference[float, S], /
    ) -> Volume[V, S]: ...
    @overload
    def __matmul__(
        self: VolumePerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> VolumePerTemperatureDifference[npt.NDArray[np.float64], S]: ...
    @overload
    def __matmul__[W: _Numerical](
        self: VolumePerTemperatureDifference[float, S], other: W, /
    ) -> VolumePerTemperatureDifference[W, S]: ...
    @overload
    def __matmul__(
        self, other: _Numerical, /
    ) -> VolumePerTemperatureDifference[V, S]: ...
    @overload
    def __matmul__[K, W](
        self: VolumePerTemperatureDifference[float, S], other: Quantity[K, W, S], /
    ) -> Quantity[Mul[Div[VolumeKind, TemperatureDifferenceKind], K], W, S]: ...
    @overload
    def __matmul__[K](
        self, other: Quantity[K, V, S] | Quantity[K, float, S], /
    ) -> Quantity[Mul[Div[VolumeKind, TemperatureDifferenceKind], K], V, S]: ...
    @overload
    @override
    def __rmul__(self, other: _Scalar, /) -> VolumePerTemperatureDifference[V, S]: ...
    @overload
    def __rmul__(
        self: VolumePerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> VolumePerTemperatureDifference[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmul__[W: _Numerical](
        self: VolumePerTemperatureDifference[float, S], other: W, /
    ) -> VolumePerTemperatureDifference[W, S]: ...
    @overload
    def __rmul__(
        self, other: _Numerical, /
    ) -> VolumePerTemperatureDifference[V, S]: ...
    @overload
    @override
    def __rmatmul__(
        self: VolumePerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> VolumePerTemperatureDifference[npt.NDArray[np.float64], S]: ...
    @overload
    def __rmatmul__[W: _Numerical](
        self: VolumePerTemperatureDifference[float, S], other: W, /
    ) -> VolumePerTemperatureDifference[W, S]: ...
    @overload
    def __rmatmul__(
        self, other: _Numerical, /
    ) -> VolumePerTemperatureDifference[V, S]: ...
    @override
    def item(self) -> VolumePerTemperatureDifference[float, S]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[VolumeKind, TemperatureDifferenceKind]], V, S
    ]: ...
    @overload
    def __rtruediv__(
        self: VolumePerTemperatureDifference[float, S],
        other: npt.NDArray[np.integer[Any]],
        /,
    ) -> Quantity[
        Div[DimensionlessKind, Div[VolumeKind, TemperatureDifferenceKind]],
        npt.NDArray[np.float64],
        S,
    ]: ...
    @overload
    def __rtruediv__[W: _Numerical](
        self: VolumePerTemperatureDifference[float, S], other: W, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[VolumeKind, TemperatureDifferenceKind]], W, S
    ]: ...
    @overload
    def __rtruediv__(
        self, other: _Numerical, /
    ) -> Quantity[
        Div[DimensionlessKind, Div[VolumeKind, TemperatureDifferenceKind]], V, S
    ]: ...
    @overload
    @override
    def __add__[W](
        self: VolumePerTemperatureDifference[float, S],
        other: Quantity[Div[VolumeKind, TemperatureDifferenceKind], W, S],
        /,
    ) -> VolumePerTemperatureDifference[W, S]: ...
    @overload
    def __add__(
        self,
        other: Quantity[Div[VolumeKind, TemperatureDifferenceKind], V, S]
        | Quantity[Div[VolumeKind, TemperatureDifferenceKind], float, S],
        /,
    ) -> VolumePerTemperatureDifference[V, S]: ...
    @overload
    @override
    def __sub__[W](
        self: VolumePerTemperatureDifference[float, S],
        other: Quantity[Div[VolumeKind, TemperatureDifferenceKind], W, S],
        /,
    ) -> VolumePerTemperatureDifference[W, S]: ...
    @overload
    def __sub__(
        self,
        other: Quantity[Div[VolumeKind, TemperatureDifferenceKind], V, S]
        | Quantity[Div[VolumeKind, TemperatureDifferenceKind], float, S],
        /,
    ) -> VolumePerTemperatureDifference[V, S]: ...
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> VolumePerTemperatureDifference[V, T]: ...
    @classmethod
    @override
    def from_value[W](cls, value: W) -> VolumePerTemperatureDifference[W, S]: ...

class _VolumePerTemperatureDifferenceConstant(
    Constant[Div[VolumeKind, TemperatureDifferenceKind]]
):
    @override
    def to_system[T: UnitSystem](
        self, system: type[T]
    ) -> VolumePerTemperatureDifference[float, T]: ...
    @override
    def to(
        self, unit: Unit[Div[VolumeKind, TemperatureDifferenceKind]]
    ) -> VolumePerTemperatureDifference[float]: ...
    @overload
    @override
    def __mul__(self, other: _PressureConstant, /) -> _EntropyConstant: ...
    @overload
    def __mul__(self, other: _TemperatureDifferenceConstant, /) -> _VolumeConstant: ...
    @overload
    def __mul__[L](
        self, other: Constant[L], /
    ) -> Constant[Mul[Div[VolumeKind, TemperatureDifferenceKind], L]]: ...
    @overload
    def __mul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _VolumePerTemperatureDifferenceConstant: ...
    @overload
    def __mul__[W, T: UnitSystem](self, other: Pressure[W, T], /) -> Entropy[W, T]: ...
    @overload
    def __mul__[W, T: UnitSystem](
        self, other: TemperatureDifference[W, T], /
    ) -> Volume[W, T]: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[Div[VolumeKind, TemperatureDifferenceKind], L], W, T]: ...
    @overload
    @override
    def __truediv__(
        self, other: _VolumePerTemperatureDifferenceConstant, /
    ) -> _DimensionlessConstant: ...
    @overload
    def __truediv__[L](
        self, other: Constant[L], /
    ) -> Constant[Div[Div[VolumeKind, TemperatureDifferenceKind], L]]: ...
    @overload
    def __truediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _VolumePerTemperatureDifferenceConstant: ...
    @overload
    def __truediv__[W, T: UnitSystem](
        self, other: VolumePerTemperatureDifference[W, T], /
    ) -> Dimensionless[W, T]: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[Div[VolumeKind, TemperatureDifferenceKind], L], W, T]: ...
    @overload
    @override
    def __rmul__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> _VolumePerTemperatureDifferenceConstant: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, Div[VolumeKind, TemperatureDifferenceKind]], W, T]: ...
    @overload
    @override
    def __rtruediv__(
        self, other: float | np.floating[Any] | np.integer[Any], /
    ) -> Constant[
        Div[DimensionlessKind, Div[VolumeKind, TemperatureDifferenceKind]]
    ]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, Div[VolumeKind, TemperatureDifferenceKind]], W, T]: ...
    def _rmul_Pressure_f[T: UnitSystem](
        self, other: Pressure[float, T], /
    ) -> Entropy[float, T]: ...
    def _rmul_Pressure[W, T: UnitSystem](
        self, other: Pressure[W, T], /
    ) -> Entropy[W, T]: ...
    def _cmul_Pressure(self, other: _PressureConstant, /) -> _EntropyConstant: ...
    def _rmul_TemperatureDifference_f[T: UnitSystem](
        self, other: TemperatureDifference[float, T], /
    ) -> Volume[float, T]: ...
    def _rmul_TemperatureDifference[W, T: UnitSystem](
        self, other: TemperatureDifference[W, T], /
    ) -> Volume[W, T]: ...
    def _cmul_TemperatureDifference(
        self, other: _TemperatureDifferenceConstant, /
    ) -> _VolumeConstant: ...
    def _rtruediv_Volume_f[T: UnitSystem](
        self, other: Volume[float, T], /
    ) -> TemperatureDifference[float, T]: ...
    def _rtruediv_Volume[W, T: UnitSystem](
        self, other: Volume[W, T], /
    ) -> TemperatureDifference[W, T]: ...
    def _ctruediv_Volume(
        self, other: _VolumeConstant, /
    ) -> _TemperatureDifferenceConstant: ...
    def _rtruediv_Entropy_f[T: UnitSystem](
        self, other: Entropy[float, T], /
    ) -> EnergyDensity[float, T]: ...
    def _rtruediv_Entropy[W, T: UnitSystem](
        self, other: Entropy[W, T], /
    ) -> EnergyDensity[W, T]: ...
    def _ctruediv_Entropy(
        self, other: _EntropyConstant, /
    ) -> _EnergyDensityConstant: ...
