[project]
name = "quantype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Theo Keane", email = "20931519+theochemtheo@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
quantype = "quantype:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
