"""Pure renderers for nominal quantities, unit namespaces, and autodiff stubs.

Quantity stubs are generic over storage ``V`` and unit system ``S``. ``S`` is a
defaulted ``typing_extensions.TypeVar`` (PEP 696), so ``Length[float]`` means
``Length[float, Atomistic]``. It passes through every overload unchanged, and is
invariant, so operands from different systems match no overload.
"""

from __future__ import annotations

import keyword
from typing import TYPE_CHECKING

from quantype.catalogue import (
    _namespace_name as namespace_name,  # pyright: ignore[reportPrivateUsage]
)

if TYPE_CHECKING:
    from collections.abc import Callable

    from quantype.catalogue import Catalogue

# Source templates keep individual generated signatures on one line.
# ruff: noqa: E501

HEADER = "# Generated by quantype.codegen; do not edit.\n"
OVERLAPS = "# mypy: disable-error-code=overload-overlap\n# pyright: reportOverlappingOverload=false\n"
# Named operators and structural-only base operators have disjoint self types.
# Checkers still compare their return types as ordinary subclass overrides.
# Class-level parameters. Method-level parameters use PEP 695 syntax.
TYPE_VARIABLES = (
    "# Public parameter names read better in diagnostics than private ones.\n"
    "# ruff: noqa: PYI001\n"
    "from typing_extensions import TypeVar\n"
    "from quantype.systems import Atomistic, UnitSystem\n"
    "V = TypeVar('V')\n"
    "S = TypeVar('S', bound=UnitSystem, default=Atomistic)\n"
)
QUANTITY_OVERRIDES = (
    "# Named operators and structural-only base operators have disjoint self types.\n"
    "# mypy: disable-error-code=override\n"
    "# pyright: reportIncompatibleMethodOverride=false\n"
)


def overloads(
    signatures: list[str], indent: str = "    ", *, overrides: bool = False
) -> str:
    decorator = indent + "@override\n" if overrides else ""
    if len(signatures) == 1:
        return decorator + indent + signatures[0] + "\n"
    return "".join(
        indent
        + "@overload\n"
        + (decorator if index == 0 else "")
        + indent
        + signature
        + "\n"
        for index, signature in enumerate(signatures)
    )


def binary(method: str, name: str, right: str, result: str) -> list[str]:
    return [
        f"def {method}(self: {name}[float, S], other: {right}[W, S], /) -> {result}[W, S]: ...",
        f"def {method}(self, other: {right}[float, S], /) -> {result}[V, S]: ...",
        f"def {method}(self, other: {right}[V, S], /) -> {result}[V, S]: ...",
    ]


def scaling(method: str, name: str, result: Callable[[str], str]) -> list[str]:
    """Plain numbers and numerical arrays scale a quantity, keeping its kind.

    A real scalar keeps the storage. Float storage scaled by an array becomes
    that array (integer NumPy arrays promote to float64); array storage stays.
    """
    return [
        f"def {method}(self, other: _Scalar, /) -> {result('V')}: ...",
        f"def {method}(self: {name}[float, S], other: npt.NDArray[np.integer[Any]], /) -> {result('npt.NDArray[np.float64]')}: ...",
        f"def {method}[W: _Numerical](self: {name}[float, S], other: W, /) -> {result('W')}: ...",
        f"def {method}(self, other: _Numerical, /) -> {result('V')}: ...",
    ]


def suppressed_override(block: str) -> str:
    """Suppress an overloaded override that refines a base return type.

    pyrefly reports it at the first signature, which a wrapped signature leaves
    no room to annotate, so it goes on the line above; ty at the last.
    """
    first = block.index("    def ")
    text = block[:first] + "    # pyrefly: ignore[bad-override]\n" + block[first:]
    last = text.rindex(": ...")
    return (
        text[:last]
        + ": ...  # ty: ignore[invalid-method-override]"
        + text[last + len(": ...") :]
    )


def method_overloads(method: str, signatures: list[str]) -> str:
    return overloads(
        [
            signature.replace(f"def {method}(", f"def {method}[W](")
            if "[W, S]" in signature and "[K" not in signature
            else signature
            for signature in signatures
        ],
        overrides=True,
    )


def additive_stubs(name: str) -> str:
    text = ""
    for method in ("__add__", "__sub__"):
        if name == "Temperature":
            signatures = binary(method, name, "TemperatureDifference", name)
            if method == "__sub__":
                signatures += binary(method, name, name, "TemperatureDifference")
        else:
            signatures = binary(method, name, name, name)
            if name == "TemperatureDifference" and method == "__add__":
                signatures += binary(method, name, "Temperature", "Temperature")
        if name == "Dimensionless":
            signatures += scaling(method, name, lambda storage: f"{name}[{storage}, S]")
        text += method_overloads(method, signatures)
    # Zero means the same in every unit, so builtin sum() works. Dimensionless
    # values take any plain number; a point subtracted from zero is meaningless.
    for method in ("__radd__", "__rsub__"):
        if name == "Dimensionless":
            signatures = scaling(method, name, lambda storage: f"{name}[{storage}, S]")
            text += overloads(signatures, overrides=True)
        elif name != "Temperature":
            # sum() requires any int here; only zero is accepted at runtime.
            text += f"    @override\n    def {method}(self, other: int, /) -> {name}[V, S]: ...\n"
    return text


def dimensionless_stubs(name: str) -> str:
    """Dimensionless values compare with plain numbers and convert to float."""
    text = "    def __float__(self) -> float: ...\n"
    for method in ("__lt__", "__le__", "__gt__", "__ge__"):
        text += overloads(
            [
                f"def {method}(self: {name}[float, S], other: Quantity[{name}Kind, float, S] | _Scalar, /) -> bool: ...",
                f"def {method}(self, other: Quantity[{name}Kind, Any, S] | _Scalar | _Numerical, /) -> Any: ...",
            ],
            overrides=True,
        )
    return text


def multiplicative_stubs(name: str, catalogue: Catalogue) -> str:
    relations = catalogue.algebra
    text = ""
    for op, method, expression in (
        ("mul", "__mul__", "Mul"),
        ("div", "__truediv__", "Div"),
    ):
        signatures: list[str] = []
        for (operation, left, right), result in relations.items():
            if operation == op and left == name:
                signatures += binary(method, name, right, result)
        signatures += scaling(method, name, lambda storage: f"{name}[{storage}, S]")
        signatures += [
            f"def {method}[K, W](self: {name}[float, S], other: Quantity[K, W, S], /) -> Quantity[{expression}[{name}Kind, K], W, S]: ...",
            f"def {method}[K](self, other: Quantity[K, float, S], /) -> Quantity[{expression}[{name}Kind, K], V, S]: ...",
            f"def {method}[K](self, other: Quantity[K, V, S], /) -> Quantity[{expression}[{name}Kind, K], V, S]: ...",
        ]
        text += method_overloads(method, signatures)
    return text


def quantity_methods(name: str, catalogue: Catalogue) -> str:
    text = f"    @classmethod\n    @override\n    def define_unit(cls, name: str, *, reference: Unit[{name}Kind], scale: float = 1.0, offset: float = 0.0, symbol: str | None = None) -> _units._{name}Unit: ...\n"
    text += f"    @classmethod\n    @override\n    def from_value[W](cls, value: W) -> {name}[W, S]: ...\n"
    text += f"    @classmethod\n    @override\n    def reinterpret[W, T: UnitSystem](cls, quantity: Quantity[Any, W, T]) -> {name}[W, T]: ...\n"
    # A string holds one number; other inputs may hold arrays.
    text += f"    @overload\n    @classmethod\n    @override\n    def parse(cls, data: str, *, units: tuple[Unit[Any], ...] = ()) -> {name}[float, S]: ...\n"
    text += f"    @overload\n    @classmethod\n    def parse(cls, data: object, *, units: tuple[Unit[Any], ...] = ()) -> {name}[float | npt.NDArray[np.float64], S]: ...\n"
    text += (
        f"    @property\n    @override\n    def unit(self) -> _units._{name}Unit: ...\n"
    )
    text += f"    @override\n    def to_system[T: UnitSystem](self, system: type[T]) -> {name}[V, T]: ...\n"
    text += additive_stubs(name)
    for method in ("__neg__", "__abs__"):
        text += f"    @override\n    def {method}(self) -> {name}[V, S]: ...\n"
    # A spread of absolute temperatures is a temperature difference.
    spread = "TemperatureDifference" if name == "Temperature" else name
    text += f"    @override\n    def std(self, axis: int | None = None, *, ddof: int = 0, keepdims: bool = False) -> {spread}[V, S]: ...\n"
    # Absolute temperatures scale and multiply, but a sum of them is meaningless.
    if name != "Temperature":
        text += f"    @override\n    def sum(self, axis: int | tuple[int, ...] | None = None, *, keepdims: bool = False) -> {name}[V, S]: ...\n"
    text += multiplicative_stubs(name, catalogue)
    if name == "Dimensionless":
        text += dimensionless_stubs(name)
    text += overloads(
        scaling("__rmul__", name, lambda storage: f"{name}[{storage}, S]"),
        overrides=True,
    )
    reciprocal = catalogue.algebra.get(("div", "Dimensionless", name))

    def inverse(storage: str) -> str:
        if reciprocal is not None:
            return f"{reciprocal}[{storage}, S]"
        return f"Quantity[Div[DimensionlessKind, {name}Kind], {storage}, S]"

    text += overloads(scaling("__rtruediv__", name, inverse), overrides=True)
    powers = [
        f"def __pow__(self, exponent: Literal[{power}], /) -> {result}[V, S]: ..."
        for (kind, power), result in catalogue.powers.items()
        if kind == name
    ]
    powers += [
        f"def __pow__[N: int](self, exponent: N, /) -> Quantity[Pow[{name}Kind, N], V, S]: ..."
    ]
    return text + overloads(powers, overrides=True)


def constant_stub(name: str, catalogue: Catalogue) -> str:
    """A kind's constant: system-free, adopting each quantity operand's system.

    A reflected operand is typed structurally (see ``_Operand`` in core.pyi), and
    a constant on the left handles products of constants.
    """
    own = f"_{name}Constant"
    scalar_types = "float | np.floating[Any] | np.integer[Any]"
    text = f"\nclass {own}(Constant[{name}Kind]):\n"
    text += f"    @override\n    def to_system[T: UnitSystem](self, system: type[T]) -> {name}[float, T]: ...\n"
    text += f"    @override\n    def to(self, unit: Unit[{name}Kind]) -> {name}[float]: ...\n"
    algebra = catalogue.algebra
    for method, op, expression, reflected in (
        ("__mul__", "mul", "Mul", False),
        ("__rmul__", "mul", "Mul", True),
        ("__truediv__", "div", "Div", False),
        ("__rtruediv__", "div", "Div", True),
    ):
        signatures = [
            f"def {method}[W, T: UnitSystem](self, other: {other}[W, T], /) -> {result}[W, T]: ..."
            for (operation, left, right), result in algebra.items()
            if operation == op
            for other in [left if reflected else right]
            if (right if reflected else left) == name
        ]
        # A named reciprocal refines the base's structural return type, which
        # checkers compare as an override.
        reciprocal = None
        if method == "__rtruediv__":
            reciprocal = algebra.get(("div", "Dimensionless", name))
            scalar = (
                f"_{reciprocal}Constant"
                if reciprocal is not None
                else f"Constant[Div[DimensionlessKind, {name}Kind]]"
            )
        else:
            scalar = own
        pair = f"L, {name}Kind" if reflected else f"{name}Kind, L"
        signatures += [
            f"def {method}(self, other: {scalar_types}, /) -> {scalar}: ...",
            f"def {method}[L, W, T: UnitSystem](self, other: _Operand[L, W, T], /) -> Quantity[{expression}[{pair}], W, T]: ...",
        ]
        if not reflected:
            signatures.append(
                f"def {method}[L](self, other: Constant[L], /) -> Constant[{expression}[{pair}]]: ..."
            )
        block = overloads(signatures, overrides=True)
        text += block if reciprocal is None else suppressed_override(block)
    return text


def structural_scaling(method: str, result: str) -> list[str]:
    """``scaling`` for structural quantities; ``result`` formats the storage."""
    return [
        f"def {method}[A, B](self: _StructuralQuantity[A, B, V, S], other: _Scalar, /) -> {result.format('V')}: ...",
        f"def {method}[A, B, W: _Numerical](self: _StructuralQuantity[A, B, float, S], other: W, /) -> {result.format('W')}: ...",
        f"def {method}[A, B](self: _StructuralQuantity[A, B, V, S], other: _Numerical, /) -> {result.format('V')}: ...",
    ]


def structural_quantity_stub() -> str:
    """A generated base carries its own dimensionless marker through trees."""
    text = "K = TypeVar('K')\n"
    text += "type _StructuralQuantity[A, B, X, Y: UnitSystem] = Quantity[Mul[A, B], X, Y] | Quantity[Div[A, B], X, Y] | Quantity[Pow[A, B], X, Y]\n"
    text += "class Quantity(_BaseQuantity[K, V, S]):\n"
    for method in ("__add__", "__sub__"):
        text += overloads(
            [
                f"def {method}[A, B, W](self: _StructuralQuantity[A, B, float, S], other: Quantity[K, W, S], /) -> Quantity[K, W, S]: ...",
                f"def {method}[A, B](self: _StructuralQuantity[A, B, V, S], other: Quantity[K, float, S], /) -> Quantity[K, V, S]: ...",
                f"def {method}[A, B](self: _StructuralQuantity[A, B, V, S], other: Quantity[K, V, S], /) -> Quantity[K, V, S]: ...",
            ],
            overrides=True,
        )
    text += "    @override\n    def __radd__[A, B](self: _StructuralQuantity[A, B, V, S], other: int, /) -> Quantity[K, V, S]: ...\n"
    text += "    @override\n    def __rsub__[A, B](self: _StructuralQuantity[A, B, V, S], other: int, /) -> Quantity[K, V, S]: ...\n"
    for method, expression in (("__mul__", "Mul"), ("__truediv__", "Div")):
        text += overloads(
            [
                *structural_scaling(method, "Quantity[K, {}, S]"),
                f"def {method}[A, B, L, W](self: _StructuralQuantity[A, B, float, S], other: Quantity[L, W, S], /) -> Quantity[{expression}[K, L], W, S]: ...",
                f"def {method}[A, B, L](self: _StructuralQuantity[A, B, V, S], other: Quantity[L, float, S], /) -> Quantity[{expression}[K, L], V, S]: ...",
                f"def {method}[A, B, L](self: _StructuralQuantity[A, B, V, S], other: Quantity[L, V, S], /) -> Quantity[{expression}[K, L], V, S]: ...",
            ],
            overrides=True,
        )
    text += overloads(
        structural_scaling("__rmul__", "Quantity[K, {}, S]"), overrides=True
    )
    # The shared base necessarily uses the builtin marker. This refinement is
    # nominal, not a widening; each catalogue has its own structural base.
    text += overloads(
        structural_scaling(
            "__rtruediv__", "Quantity[Div[DimensionlessKind, K], {}, S]"
        ),
        overrides=True,
    )
    text += "    @override\n    def __pow__[A, B, N: int](self: _StructuralQuantity[A, B, V, S], exponent: N, /) -> Quantity[Pow[K, N], V, S]: ...\n"
    for method in ("__neg__", "__abs__"):
        text += f"    @override\n    def {method}[A, B](self: _StructuralQuantity[A, B, V, S]) -> Quantity[K, V, S]: ...\n"
    text += "    @override\n    def sum[A, B](self: _StructuralQuantity[A, B, V, S], axis: int | tuple[int, ...] | None = None, *, keepdims: bool = False) -> Quantity[K, V, S]: ...\n"
    return text


def quantity_outputs(catalogue: Catalogue, package: str) -> dict[str, str]:
    kinds = HEADER + '"""Nominal and structural semantic markers."""\n\n'
    kinds += "from quantype._internal._kind_types import Div, Mul, Pow\n\n"
    exports = ["Div", "Mul", "Pow"]
    exports += [f"{name}Kind" for name in catalogue.quantities]
    kinds += f"__all__ = {sorted(exports)!r}\n\n"
    for name in catalogue.quantities:
        kinds += f"class {name}Kind:\n    pass\n\n"
    markers = (
        f"from {package}.kinds import ("
        + ", ".join(f"{name}Kind" for name in catalogue.quantities)
        + ")\n"
    )
    # Constant classes register themselves by kind; nothing names them here.
    runtime = HEADER + "# pyright: reportUnusedClass=false\n" + markers
    runtime += (
        "from quantype.systems import UnitSystem\nfrom quantype.core import Constant\n"
    )
    if package == "quantype":
        runtime += "from quantype.core import Quantity\n"
    else:
        runtime += "from quantype.core import Quantity as _BaseQuantity\n"
        runtime += f"from {package}._catalogue import runtime\n"
        runtime += "class Quantity[K, V, S: UnitSystem](_BaseQuantity[K, V, S]):\n    _catalogue_dimensionless = runtime.kinds['Dimensionless']\n"
    stub = (
        HEADER + OVERLAPS + QUANTITY_OVERRIDES + "# pyright: reportPrivateUsage=false\n"
    )
    stub += "from typing import Any, Literal, overload, override\nimport numpy as np\nimport numpy.typing as npt\nfrom quantype.core import Constant, Unit, _Numerical, _Operand, _Scalar\n"
    stub += (
        "from quantype.core import Quantity\n"
        if package == "quantype"
        else "from quantype.core import Quantity as _BaseQuantity\n"
    )
    stub += (
        markers
        + f"from {package}.kinds import Div, Mul, Pow\nfrom {package} import units as _units\n"
        + TYPE_VARIABLES
    )
    if package != "quantype":
        stub += structural_quantity_stub()
    for name in catalogue.quantities:
        runtime += f"\nclass {name}[V, S: UnitSystem](Quantity[{name}Kind, V, S]):\n    _kind = {name!r}\n"
        if package != "quantype":
            runtime += f"    _semantic = runtime.kinds[{name!r}]\n"
        stub += f"\nclass {name}(Quantity[{name}Kind, V, S]):\n" + quantity_methods(
            name, catalogue
        )
    for name in catalogue.quantities:
        runtime += f"\nclass _{name}Constant(Constant[{name}Kind]):\n    _constant_kind = {name!r}\n"
        if package != "quantype":
            runtime += f"    _constant_semantic = runtime.kinds[{name!r}]\n"
        stub += constant_stub(name, catalogue)
    return {"kinds.py": kinds, "_generated.py": runtime, "_generated.pyi": stub}


def unit_names(catalogue: Catalogue) -> dict[str, str]:
    return {
        identifier: name
        for name, spec in catalogue.units.items()
        for identifier in (name, *spec.aliases)
        if identifier.isidentifier()
        and identifier.isascii()
        and not keyword.iskeyword(identifier)
    }


def namespace_outputs(catalogue: Catalogue) -> tuple[str, str, list[str]]:
    runtime, stub = "", ""
    exports: list[str] = []
    for kind in catalogue.quantities:
        namespace = namespace_name(kind)
        runtime += f"\nclass _{kind}Namespace:\n"
        stub += f"\nclass _{kind}Namespace:\n"
        for name, spec in catalogue.units.items():
            if spec.kind == kind:
                runtime += f"    @property\n    def {name}(self) -> 'Unit[{kind}Kind]':\n        return _typing.cast('Unit[{kind}Kind]', _get_unit({name!r}))\n"
                stub += f"    @property\n    def {name}(self) -> _{kind}Unit: ...\n"
        runtime += f"\n{namespace} = _{kind}Namespace()\n"
        stub += f"\n{namespace}: _{kind}Namespace\n"
        exports.append(namespace)
    return runtime, stub, exports


def unit_outputs(catalogue: Catalogue, package: str) -> dict[str, str]:
    namespaces = {namespace_name(kind) for kind in catalogue.quantities}
    names = {
        name: unit
        for name, unit in unit_names(catalogue).items()
        if name not in namespaces
    }
    markers = (
        f"from {package}.kinds import ("
        + ", ".join(f"{name}Kind" for name in catalogue.quantities)
        + ")\n"
    )
    # Runtime helpers are private, so dir(u) lists only units and namespaces.
    runtime = (
        HEADER
        + "# Scientific unit names preserve conventional case; flat names load lazily.\n# ruff: noqa: N802, F822, E501\n# pyright: reportUnsupportedDunderAll=false\n"
    )
    runtime += "import typing as _typing\n"
    runtime += (
        "if _typing.TYPE_CHECKING:\n    from typing import Any\n    from quantype.core import Unit\n    "
        + markers
    )
    runtime += (
        "from quantype.core import get_unit as _get_unit\n"
        if package == "quantype"
        else f"from {package}._catalogue import runtime as _runtime\n_get_unit = _runtime.get_unit\n"
    )
    stub = (
        HEADER
        + OVERLAPS
        + "# ruff: noqa: N816, N802\nfrom typing import Any, overload\nimport numpy as np\nfrom quantype.core import Unit\n"
        + markers
    )
    stub += (
        f"from {package}._generated import (" + ", ".join(catalogue.quantities) + ")\n"
    )
    for name in catalogue.quantities:
        stub += f"\nclass _{name}Unit(Unit[{name}Kind]):\n"
        for method in ("__call__", "__mul__", "__rmul__"):
            stub += overloads(
                [
                    f"def {method}[S: np.floating[Any]](self, value: S, /) -> {name}[S]: ...",
                    f"def {method}(self, value: float, /) -> {name}[float]: ...",
                    f"def {method}[V](self, value: V, /) -> {name}[V]: ...",
                ]
            )
    for identifier, name in names.items():
        stub += f"{identifier}: _{catalogue.units[name].kind}Unit\n"
    runtime += f"\n_NAMES = {names!r}\n"
    runtime += "\ndef __getattr__(name: str) -> 'Unit[Any]':\n    if name not in _NAMES:\n        raise AttributeError(name)\n    unit = _get_unit(_NAMES[name])\n    globals()[name] = unit\n    return unit\n"
    namespace_runtime, namespace_stub, namespace_names = namespace_outputs(catalogue)
    exports = sorted([*names, *namespace_names])
    return {
        "units.py": runtime + namespace_runtime + f"\n__all__ = {exports!r}\n",
        "units.pyi": stub + namespace_stub + f"\n__all__ = {exports!r}\n",
    }


def _derivatives(catalogue: Catalogue) -> list[tuple[str, str, str]]:
    """(output, input, derivative) for each declared or derived division."""
    return [
        (output, input_, result)
        for (operation, output, input_), result in catalogue.algebra.items()
        if operation == "div"
    ]


def jax_signatures(catalogue: Catalogue, name: str) -> list[str]:
    """``grad``/``value_and_grad``: the first argument's derivative is typed.

    Further arguments pass through a ParamSpec; other ``argnums`` are untyped.
    """

    def returned(output: str, result: str) -> str:
        return f"tuple[{output}, {result}]" if name == "value_and_grad" else result

    signatures = [
        f"def {name}[S: UnitSystem, **P](function: Callable[Concatenate[{input_}[Array, S], P], {output}[Array, S]], argnums: Literal[0] = 0) -> Callable[Concatenate[{input_}[Array, S], P], {returned(f'{output}[Array, S]', f'{result}[Array, S]')}]: ..."
        for output, input_, result in _derivatives(catalogue)
    ]
    signatures += [
        f"def {name}[I, O, S: UnitSystem, **P](function: Callable[Concatenate[Quantity[I, Array, S], P], Quantity[O, Array, S]], argnums: Literal[0] = 0) -> Callable[Concatenate[Quantity[I, Array, S], P], {returned('Quantity[O, Array, S]', 'Quantity[Div[O, I], Array, S]')}]: ...",
        f"def {name}(function: Callable[..., Quantity[Any, Array, Any]], argnums: int | tuple[int, ...]) -> Callable[..., Any]: ...",
    ]
    return signatures


def torch_signatures(catalogue: Catalogue) -> list[str]:
    options = "*, create_graph: bool = False, retain_graph: bool | None = None"
    signatures = [
        f"def grad[S: UnitSystem](output: {output}[Tensor, S], inputs: {input_}[Tensor, S], {options}) -> {result}[Tensor, S]: ..."
        for output, input_, result in _derivatives(catalogue)
    ]
    signatures += [
        f"def grad[I, O, S: UnitSystem](output: Quantity[O, Tensor, S], inputs: Quantity[I, Tensor, S], {options}) -> Quantity[Div[O, I], Tensor, S]: ...",
        f"def grad[S: UnitSystem](output: Quantity[Any, Tensor, S], inputs: Sequence[Quantity[Any, Tensor, S]], {options}) -> tuple[Quantity[Any, Tensor, S], ...]: ...",
    ]
    return signatures


def hessian_signatures(catalogue: Catalogue) -> list[str]:
    signatures: list[str] = []
    for output, input_, result in _derivatives(catalogue):
        second = catalogue.algebra.get(("div", result, input_))
        if second is not None:
            signatures.append(
                f"def hessian[S: UnitSystem, **P](function: Callable[Concatenate[{input_}[Array, S], P], {output}[Array, S]], argnums: Literal[0] = 0) -> Callable[Concatenate[{input_}[Array, S], P], {second}[Array, S]]: ..."
            )
    signatures += [
        "def hessian[I, O, S: UnitSystem, **P](function: Callable[Concatenate[Quantity[I, Array, S], P], Quantity[O, Array, S]], argnums: Literal[0] = 0) -> Callable[Concatenate[Quantity[I, Array, S], P], Quantity[Div[Div[O, I], I], Array, S]]: ...",
        "def hessian(function: Callable[..., Quantity[Any, Array, Any]], argnums: int) -> Callable[..., Any]: ...",
    ]
    return signatures


def adapter_outputs(catalogue: Catalogue, package: str) -> dict[str, str]:
    outputs: dict[str, str] = {}
    for backend, source, array in (
        ("ujax", "jax", "Array"),
        ("utorch", "torch", "Tensor"),
    ):
        text = (
            HEADER
            + OVERLAPS
            + f"from {source} import {array}\n"
            + (
                "from typing import Any, Concatenate, Literal, overload\nfrom collections.abc import Callable\n"
                if backend == "ujax"
                else "from typing import Any, overload\nfrom collections.abc import Sequence\n"
            )
            + "from quantype.systems import UnitSystem\n"
        )
        derivative_kinds = {
            kind
            for (op, left, right), result in catalogue.algebra.items()
            if op == "div"
            for kind in (left, right, result)
        }
        if derivative_kinds:
            text += (
                f"from {package}._generated import ("
                + ", ".join(
                    name for name in catalogue.quantities if name in derivative_kinds
                )
                + ")\n"
            )
        quantity_module = "quantype.core" if package == "quantype" else package
        text += (
            f"from {quantity_module} import Quantity\nfrom {package}.kinds import Div\n"
        )
        if backend == "ujax":
            text += (
                f"__all__ = {['grad', 'hessian', 'jit', 'value_and_grad', 'vmap']!r}\n"
            )
            text += overloads(jax_signatures(catalogue, "grad"), indent="")
            text += overloads(jax_signatures(catalogue, "value_and_grad"), indent="")
            text += overloads(hessian_signatures(catalogue), indent="")
            text += "def jit[**P, T](fun: Callable[P, T]) -> Callable[P, T]: ...\n"
            text += "def vmap[**P, T](fun: Callable[P, T], in_axes: int | None = 0, out_axes: int = 0) -> Callable[P, T]: ...\n"
        else:
            text += "__all__ = ['grad']\n"
            text += overloads(torch_signatures(catalogue), indent="")
        if package == "quantype" and backend == "ujax":
            text += "def _register_quantity(cls: type[Quantity[Any, Any, Any]]) -> None: ...\n"
        outputs[f"{backend}.pyi"] = text
    return outputs


NUMPY_FUNCTIONS = (
    "abs", "absolute", "allclose", "arccos", "arcsin", "arctan", "arctan2", "clip",
    "concatenate", "cos", "cosh", "cross", "cumsum", "diff", "dot", "exp",
    "expand_dims", "expm1", "isclose", "isfinite", "isinf", "isnan", "linalg", "log",
    "log1p", "log2", "log10", "max", "maximum", "mean", "min", "minimum", "reshape",
    "sin", "sinh", "sqrt", "squeeze", "stack", "std", "sum", "tan", "tanh",
    "transpose", "where", "zeros_like",
)  # fmt: skip
# Unary functions with unit rules: names, argument kind, result kind.
NUMPY_UNARY = (
    *((name, "Angle", "Dimensionless") for name in ("sin", "cos", "tan")),
    *((name, "Dimensionless", "Angle") for name in ("arcsin", "arccos", "arctan")),
    *(
        (name, "Dimensionless", "Dimensionless")
        for name in (
            "exp",
            "expm1",
            "log",
            "log1p",
            "log2",
            "log10",
            "sinh",
            "cosh",
            "tanh",
        )
    ),
)
# Plain numbers and arrays go to their own backend.
RAW_UNARY = (
    "def {0}(x: float, /) -> float: ...",
    "def {0}[F: np.floating[Any]](x: F, /) -> F: ...",
    "def {0}[A: _Numerical](x: A, /) -> A: ...",
)


def numpy_stub(catalogue: Catalogue, package: str) -> str:
    """``qnp``: NumPy's names with unit rules, typed with the catalogue's classes."""
    text = (
        HEADER
        + OVERLAPS
        + "# NumPy's names, including builtin ones.\n# ruff: noqa: A001\n"
        + "# pyright: reportPrivateUsage=false\n"
    )
    text += "from collections.abc import Sequence\nfrom typing import Any, Literal, overload\n"
    text += "import numpy as np\nfrom quantype.core import Quantity as _BaseQuantity, _Numerical\n"
    text += "from quantype.systems import UnitSystem\n"
    text += (
        f"from {package}._generated import (" + ", ".join(catalogue.quantities) + ")\n"
    )
    text += (
        f"from {package}._generated import Quantity\n"
        if package != "quantype"
        else "from quantype.core import Quantity\n"
    )
    text += f"from {package}.kinds import Mul\n"
    text += f"__all__ = {sorted(NUMPY_FUNCTIONS)!r}\n\n"
    quantity = "_BaseQuantity[Any, Any, Any]"
    for name, source, target in NUMPY_UNARY:
        text += overloads(
            [
                f"def {name}[V, S: UnitSystem](x: {source}[V, S], /) -> {target}[V, S]: ...",
                *(raw.format(name) for raw in RAW_UNARY),
            ],
            indent="",
        )
    roots = [
        f"def sqrt[V, S: UnitSystem](x: {result}[V, S], /) -> {base}[V, S]: ..."
        for (base, exponent), result in catalogue.powers.items()
        if exponent == 2  # noqa: PLR2004 -- square roots undo squares
    ]
    roots.append(
        "def sqrt[V, S: UnitSystem](x: Dimensionless[V, S], /) -> Dimensionless[V, S]: ..."
    )
    text += overloads([*roots, *(raw.format("sqrt") for raw in RAW_UNARY)], indent="")
    for name in ("absolute", "abs"):
        text += overloads(
            [
                f"def {name}[Q: {quantity}](x: Q, /) -> Q: ...",
                *(raw.format(name) for raw in RAW_UNARY),
            ],
            indent="",
        )
    text += overloads(
        [
            "def arctan2[K, V, S: UnitSystem](y: _BaseQuantity[K, V, S], x: _BaseQuantity[K, V, S], /) -> Angle[V, S]: ...",
            "def arctan2[A: _Numerical](y: A, x: A, /) -> A: ...",
            "def arctan2(y: float, x: float, /) -> float: ...",
        ],
        indent="",
    )
    for name in ("maximum", "minimum"):
        text += overloads(
            [
                f"def {name}[Q: {quantity}](a: Q, b: Q, /) -> Q: ...",
                f"def {name}[A: _Numerical](a: A, b: A, /) -> A: ...",
            ],
            indent="",
        )
    text += overloads(
        [
            f"def clip[Q: {quantity}](x: Q, a_min: Q | None, a_max: Q | None, /) -> Q: ...",
            "def clip[A: _Numerical](x: A, a_min: Any, a_max: Any, /) -> A: ...",
        ],
        indent="",
    )
    text += overloads(
        [
            f"def where[Q: {quantity}](condition: Any, x: Q, y: Q, /) -> Q: ...",
            "def where[A: _Numerical](condition: Any, x: A, y: A, /) -> A: ...",
        ],
        indent="",
    )
    for name in ("isnan", "isfinite", "isinf"):
        text += f"def {name}(x: Any, /) -> Any: ...\n"
    for name, returned in (("isclose", "Any"), ("allclose", "bool")):
        text += overloads(
            [
                f"def {name}[Q: {quantity}](a: Q, b: Q, *, rtol: float = ..., atol: Q | Literal[0] = ..., equal_nan: bool = ...) -> {returned}: ...",
                f"def {name}[A: _Numerical](a: A, b: A, *, rtol: float = ..., atol: float = ..., equal_nan: bool = ...) -> {returned}: ...",
            ],
            indent="",
        )
    products = [
        f"def dot[V, S: UnitSystem](a: {left}[V, S], b: {right}[V, S], /) -> {result}[V, S]: ..."
        for (operation, left, right), result in catalogue.algebra.items()
        if operation == "mul"
    ]
    text += overloads(
        [
            *products,
            "def dot[K, L, V, S: UnitSystem](a: _BaseQuantity[K, V, S], b: _BaseQuantity[L, V, S], /) -> Quantity[Mul[K, L], V, S]: ...",
            "def dot[A: _Numerical](a: A, b: A, /) -> Any: ...",
        ],
        indent="",
    )
    text += overloads(
        [
            "def cross[K, L, V, S: UnitSystem](a: _BaseQuantity[K, V, S], b: _BaseQuantity[L, V, S], /, axis: int = ...) -> Quantity[Mul[K, L], V, S]: ...",
            "def cross[A: _Numerical](a: A, b: A, /, axis: int = ...) -> A: ...",
        ],
        indent="",
    )
    for name in ("stack", "concatenate"):
        text += overloads(
            [
                f"def {name}[Q: {quantity}](arrays: Sequence[Q], axis: int = ...) -> Q: ...",
                f"def {name}[A: _Numerical](arrays: Sequence[A], axis: int = ...) -> A: ...",
            ],
            indent="",
        )
    for name, parameters in (
        ("reshape", "shape: int | tuple[int, ...]"),
        ("transpose", "axes: Sequence[int] | None = ..."),
        ("squeeze", "axis: int | None = ..."),
        ("expand_dims", "axis: int"),
        ("cumsum", "axis: int | None = ..."),
    ):
        text += overloads(
            [
                f"def {name}[Q: {quantity}](x: Q, {parameters}) -> Q: ...",
                f"def {name}[A: _Numerical](x: A, {parameters}) -> A: ...",
            ],
            indent="",
        )
    text += overloads(
        [
            f"def zeros_like[Q: {quantity}](x: Q) -> Q: ...",
            "def zeros_like[A: _Numerical](x: A) -> A: ...",
        ],
        indent="",
    )
    for name in ("sum", "mean", "max", "min"):
        text += overloads(
            [
                f"def {name}[Q: {quantity}](x: Q, axis: int | None = ..., *, keepdims: bool = ...) -> Q: ...",
                f"def {name}(x: _Numerical, axis: int | None = ..., *, keepdims: bool = ...) -> Any: ...",
            ],
            indent="",
        )
    # A spread or difference of absolute temperatures is a temperature difference.
    text += overloads(
        [
            "def std[V, S: UnitSystem](x: Temperature[V, S], axis: int | None = ..., *, ddof: int = ..., keepdims: bool = ...) -> TemperatureDifference[V, S]: ...",
            f"def std[Q: {quantity}](x: Q, axis: int | None = ..., *, ddof: int = ..., keepdims: bool = ...) -> Q: ...",
            "def std(x: _Numerical, axis: int | None = ..., *, ddof: int = ..., keepdims: bool = ...) -> Any: ...",
        ],
        indent="",
    )
    text += overloads(
        [
            "def diff[V, S: UnitSystem](x: Temperature[V, S], n: int = ..., axis: int = ...) -> TemperatureDifference[V, S]: ...",
            f"def diff[Q: {quantity}](x: Q, n: int = ..., axis: int = ...) -> Q: ...",
            "def diff[A: _Numerical](x: A, n: int = ..., axis: int = ...) -> A: ...",
        ],
        indent="",
    )
    text += "\nclass _Linalg:\n"
    text += "    @overload\n    @staticmethod\n"
    text += f"    def norm[Q: {quantity}](x: Q, axis: int | None = ..., *, keepdims: bool = ...) -> Q: ...\n"
    text += "    @overload\n    @staticmethod\n"
    text += "    def norm[A: _Numerical](x: A, axis: int | None = ..., *, keepdims: bool = ...) -> A: ...\n"
    text += "\nlinalg: _Linalg\n"
    return text


def numpy_outputs(catalogue: Catalogue, package: str) -> dict[str, str]:
    runtime = HEADER + (
        '"""Unit-aware NumPy functions for NumPy, JAX and Torch arrays: ``qnp``.\n\n'
        "Quantities follow their physical rules; plain numbers and arrays go\n"
        'straight to their own backend.\n"""\n\n'
    )
    runtime += "# ruff: noqa: A004\n"
    runtime += (
        "from quantype._internal._numpy import (" + ", ".join(NUMPY_FUNCTIONS) + ")\n"
    )

    runtime += f"__all__ = {sorted(NUMPY_FUNCTIONS)!r}\n"
    return {"numpy.py": runtime, "numpy.pyi": numpy_stub(catalogue, package)}


def outputs(catalogue: Catalogue, package: str) -> dict[str, str]:
    return {
        **quantity_outputs(catalogue, package),
        **unit_outputs(catalogue, package),
        **adapter_outputs(catalogue, package),
        **numpy_outputs(catalogue, package),
    }
