from quantype._generated import Angle, Area, Dimensionless, Length
from quantype.systems import UnitSystem

def sqrt[V, S: UnitSystem](quantity: Area[V, S]) -> Length[V, S]: ...
def sin[V, S: UnitSystem](quantity: Angle[V, S]) -> Dimensionless[V, S]: ...
def exp[V, S: UnitSystem](quantity: Dimensionless[V, S]) -> Dimensionless[V, S]: ...
