# Generated by quantype.codegen; do not edit.
# pyright: reportUnusedClass=false
import importlib as _importlib

from quantype._internal._semantics import defer_table as _defer_table
from quantype.core import Constant, Quantity
from quantype.kinds import (
    AccelerationKind,
    ActionKind,
    AngleKind,
    AreaKind,
    AtomCountKind,
    ChargeKind,
    DimensionlessKind,
    DipoleMomentKind,
    ElectricFieldKind,
    ElectricPotentialKind,
    ElectronCountKind,
    ElectronDensityKind,
    EnergyDensityKind,
    EnergyKind,
    EnergyPerAtomKind,
    EnergyPerVolumeKind,
    EntropyKind,
    ForceConstantKind,
    ForceKind,
    FrequencyKind,
    InverseTimeKind,
    LengthKind,
    MagneticMomentKind,
    MagnetizationKind,
    MassDensityKind,
    MassKind,
    MomentumKind,
    ParticleDensityKind,
    PressureKind,
    TemperatureDifferenceKind,
    TemperatureKind,
    TemperatureRateKind,
    TimeKind,
    VelocityKind,
    VolumeKind,
)
from quantype.systems import UnitSystem

_defer_table(lambda: _importlib.import_module("quantype.products"))


class Dimensionless[V, S: UnitSystem](Quantity[DimensionlessKind, V, S]):
    """A dimensionless, stored in 1 in the default Atomistic system.

    Build one with ``Dimensionless[float](2, u.one)``.
    Its units are in ``u.dimensionless``.
    """

    _kind = "Dimensionless"


class Length[V, S: UnitSystem](Quantity[LengthKind, V, S]):
    """A length, stored in Å in the default Atomistic system.

    Build one with ``Length[float](2, u.angstrom)``.
    Its units are in ``u.length``.
    """

    _kind = "Length"


class Area[V, S: UnitSystem](Quantity[AreaKind, V, S]):
    """An area, stored in Å^2 in the default Atomistic system.

    Build one with ``Area[float](2, u.angstrom_squared)``.
    Its units are in ``u.area``.
    """

    _kind = "Area"


class Volume[V, S: UnitSystem](Quantity[VolumeKind, V, S]):
    """A volume, stored in Å^3 in the default Atomistic system.

    Build one with ``Volume[float](2, u.angstrom_cubed)``.
    Its units are in ``u.volume``.
    """

    _kind = "Volume"


class Time[V, S: UnitSystem](Quantity[TimeKind, V, S]):
    """A time, stored in fs in the default Atomistic system.

    Build one with ``Time[float](2, u.femtosecond)``.
    Its units are in ``u.time``.
    """

    _kind = "Time"


class Velocity[V, S: UnitSystem](Quantity[VelocityKind, V, S]):
    """A velocity, stored in Å/fs in the default Atomistic system.

    Build one with ``Velocity[float](2, u.angstrom_per_fs)``.
    Its units are in ``u.velocity``.
    """

    _kind = "Velocity"


class Energy[V, S: UnitSystem](Quantity[EnergyKind, V, S]):
    """An energy, stored in eV in the default Atomistic system.

    Build one with ``Energy[float](2, u.electron_volt)``.
    Its units are in ``u.energy``.
    """

    _kind = "Energy"


class EnergyPerAtom[V, S: UnitSystem](Quantity[EnergyPerAtomKind, V, S]):
    """An energy per atom, stored in eV/atom in the default Atomistic system.

    Build one with ``EnergyPerAtom[float](2, u.eV_per_atom)``.
    Its units are in ``u.energy_per_atom``.
    """

    _kind = "EnergyPerAtom"


class Force[V, S: UnitSystem](Quantity[ForceKind, V, S]):
    """A force, stored in eV/Å in the default Atomistic system.

    Build one with ``Force[float](2, u.eV_per_angstrom)``.
    Its units are in ``u.force``.
    """

    _kind = "Force"


class ForceConstant[V, S: UnitSystem](Quantity[ForceConstantKind, V, S]):
    """A force constant, stored in eV/Å^2 in the default Atomistic system.

    Build one with ``ForceConstant[float](2, u.eV_per_angstrom_squared)``.
    Its units are in ``u.force_constant``.
    """

    _kind = "ForceConstant"


class Pressure[V, S: UnitSystem](Quantity[PressureKind, V, S]):
    """A pressure, stored in eV/Å^3 in the default Atomistic system.

    Build one with ``Pressure[float](2, u.eV_per_angstrom_cubed)``.
    Its units are in ``u.pressure``.
    """

    _kind = "Pressure"


class EnergyDensity[V, S: UnitSystem](Quantity[EnergyDensityKind, V, S]):
    """An energy density, stored in eV/Å^3 in the default Atomistic system.

    Build one with ``EnergyDensity[float](2, u.energy_density.energy_density)``.
    Its units are in ``u.energy_density``.
    """

    _kind = "EnergyDensity"


class EnergyPerVolume[V, S: UnitSystem](Quantity[EnergyPerVolumeKind, V, S]):
    """An energy per volume, stored in eV/Å^3 in the default Atomistic system.

    Build one with ``EnergyPerVolume[float](2, u.energy_per_volume.energy_per_volume)``.
    Its units are in ``u.energy_per_volume``.
    """

    _kind = "EnergyPerVolume"


class Temperature[V, S: UnitSystem](Quantity[TemperatureKind, V, S]):
    """A temperature, stored in K in the default Atomistic system.

    Build one with ``Temperature[float](2, u.kelvin)``.
    Its units are in ``u.temperature``.
    """

    _kind = "Temperature"


class TemperatureDifference[V, S: UnitSystem](
    Quantity[TemperatureDifferenceKind, V, S]
):
    """A temperature difference, stored in ΔK in the default Atomistic system.

    Build one with ``TemperatureDifference[float](2, u.delta_kelvin)``.
    Its units are in ``u.temperature_difference``.
    """

    _kind = "TemperatureDifference"


class TemperatureRate[V, S: UnitSystem](Quantity[TemperatureRateKind, V, S]):
    """A temperature rate, stored in K/fs in the default Atomistic system.

    Build one with ``TemperatureRate[float](2, u.kelvin_per_fs)``.
    Its units are in ``u.temperature_rate``.
    """

    _kind = "TemperatureRate"


class MagneticMoment[V, S: UnitSystem](Quantity[MagneticMomentKind, V, S]):
    """A magnetic moment, stored in μB in the default Atomistic system.

    Build one with ``MagneticMoment[float](2, u.bohr_magneton)``.
    Its units are in ``u.magnetic_moment``.
    """

    _kind = "MagneticMoment"


class Magnetization[V, S: UnitSystem](Quantity[MagnetizationKind, V, S]):
    """A magnetization, stored in μB/Å^3 in the default Atomistic system.

    Build one with ``Magnetization[float](2, u.bohr_magneton_per_angstrom_cubed)``.
    Its units are in ``u.magnetization``.
    """

    _kind = "Magnetization"


class ParticleDensity[V, S: UnitSystem](Quantity[ParticleDensityKind, V, S]):
    """A particle density, stored in atom/Å^3 in the default Atomistic system.

    Build one with ``ParticleDensity[float](2, u.atom_per_angstrom_cubed)``.
    Its units are in ``u.particle_density``.
    """

    _kind = "ParticleDensity"


class ElectronDensity[V, S: UnitSystem](Quantity[ElectronDensityKind, V, S]):
    """An electron density, stored in electron/Å^3 in the default Atomistic system.

    Build one with ``ElectronDensity[float](2, u.electron_per_angstrom_cubed)``.
    Its units are in ``u.electron_density``.
    """

    _kind = "ElectronDensity"


class Angle[V, S: UnitSystem](Quantity[AngleKind, V, S]):
    """An angle, stored in rad in the default Atomistic system.

    Build one with ``Angle[float](2, u.radian)``.
    Its units are in ``u.angle``.
    """

    _kind = "Angle"


class Frequency[V, S: UnitSystem](Quantity[FrequencyKind, V, S]):
    """A frequency, stored in fs^-1 in the default Atomistic system.

    Build one with ``Frequency[float](2, u.frequency_per_fs)``.
    Its units are in ``u.frequency``.
    """

    _kind = "Frequency"


class InverseTime[V, S: UnitSystem](Quantity[InverseTimeKind, V, S]):
    """An inverse time, stored in fs^-1 in the default Atomistic system.

    Build one with ``InverseTime[float](2, u.per_fs)``.
    Its units are in ``u.inverse_time``.
    """

    _kind = "InverseTime"


class AtomCount[V, S: UnitSystem](Quantity[AtomCountKind, V, S]):
    """An atom count, stored in atom in the default Atomistic system.

    Build one with ``AtomCount[float](2, u.atom)``.
    Its units are in ``u.atom_count``.
    """

    _kind = "AtomCount"


class ElectronCount[V, S: UnitSystem](Quantity[ElectronCountKind, V, S]):
    """An electron count, stored in electron in the default Atomistic system.

    Build one with ``ElectronCount[float](2, u.electron)``.
    Its units are in ``u.electron_count``.
    """

    _kind = "ElectronCount"


class Mass[V, S: UnitSystem](Quantity[MassKind, V, S]):
    """A mass, stored in eV fs^2/Å^2 in the default Atomistic system.

    Build one with ``Mass[float](2, u.eV_fs2_per_angstrom2)``.
    Its units are in ``u.mass``.
    """

    _kind = "Mass"


class MassDensity[V, S: UnitSystem](Quantity[MassDensityKind, V, S]):
    """A mass density, stored in eV fs^2/Å^5 in the default Atomistic system.

    Build one with ``MassDensity[float](2, u.eV_fs2_per_angstrom5)``.
    Its units are in ``u.mass_density``.
    """

    _kind = "MassDensity"


class Momentum[V, S: UnitSystem](Quantity[MomentumKind, V, S]):
    """A momentum, stored in eV fs/Å in the default Atomistic system.

    Build one with ``Momentum[float](2, u.eV_fs_per_angstrom)``.
    Its units are in ``u.momentum``.
    """

    _kind = "Momentum"


class Acceleration[V, S: UnitSystem](Quantity[AccelerationKind, V, S]):
    """An acceleration, stored in Å/fs^2 in the default Atomistic system.

    Build one with ``Acceleration[float](2, u.angstrom_per_fs2)``.
    Its units are in ``u.acceleration``.
    """

    _kind = "Acceleration"


class Charge[V, S: UnitSystem](Quantity[ChargeKind, V, S]):
    """A charge, stored in e in the default Atomistic system.

    Build one with ``Charge[float](2, u.elementary_charge)``.
    Its units are in ``u.charge``.
    """

    _kind = "Charge"


class ElectricPotential[V, S: UnitSystem](Quantity[ElectricPotentialKind, V, S]):
    """An electric potential, stored in V in the default Atomistic system.

    Build one with ``ElectricPotential[float](2, u.volt)``.
    Its units are in ``u.electric_potential``.
    """

    _kind = "ElectricPotential"


class ElectricField[V, S: UnitSystem](Quantity[ElectricFieldKind, V, S]):
    """An electric field, stored in V/Å in the default Atomistic system.

    Build one with ``ElectricField[float](2, u.volt_per_angstrom)``.
    Its units are in ``u.electric_field``.
    """

    _kind = "ElectricField"


class DipoleMoment[V, S: UnitSystem](Quantity[DipoleMomentKind, V, S]):
    """A dipole moment, stored in e Å in the default Atomistic system.

    Build one with ``DipoleMoment[float](2, u.e_angstrom)``.
    Its units are in ``u.dipole_moment``.
    """

    _kind = "DipoleMoment"


class Entropy[V, S: UnitSystem](Quantity[EntropyKind, V, S]):
    """An entropy, stored in eV/K in the default Atomistic system.

    Build one with ``Entropy[float](2, u.eV_per_kelvin)``.
    Its units are in ``u.entropy``.
    """

    _kind = "Entropy"


class Action[V, S: UnitSystem](Quantity[ActionKind, V, S]):
    """An action, stored in eV fs in the default Atomistic system.

    Build one with ``Action[float](2, u.eV_fs)``.
    Its units are in ``u.action``.
    """

    _kind = "Action"


class _DimensionlessConstant(Constant[DimensionlessKind]):
    _constant_kind = "Dimensionless"


class _LengthConstant(Constant[LengthKind]):
    _constant_kind = "Length"


class _AreaConstant(Constant[AreaKind]):
    _constant_kind = "Area"


class _VolumeConstant(Constant[VolumeKind]):
    _constant_kind = "Volume"


class _TimeConstant(Constant[TimeKind]):
    _constant_kind = "Time"


class _VelocityConstant(Constant[VelocityKind]):
    _constant_kind = "Velocity"


class _EnergyConstant(Constant[EnergyKind]):
    _constant_kind = "Energy"


class _EnergyPerAtomConstant(Constant[EnergyPerAtomKind]):
    _constant_kind = "EnergyPerAtom"


class _ForceConstant(Constant[ForceKind]):
    _constant_kind = "Force"


class _ForceConstantConstant(Constant[ForceConstantKind]):
    _constant_kind = "ForceConstant"


class _PressureConstant(Constant[PressureKind]):
    _constant_kind = "Pressure"


class _EnergyDensityConstant(Constant[EnergyDensityKind]):
    _constant_kind = "EnergyDensity"


class _EnergyPerVolumeConstant(Constant[EnergyPerVolumeKind]):
    _constant_kind = "EnergyPerVolume"


class _TemperatureConstant(Constant[TemperatureKind]):
    _constant_kind = "Temperature"


class _TemperatureDifferenceConstant(Constant[TemperatureDifferenceKind]):
    _constant_kind = "TemperatureDifference"


class _TemperatureRateConstant(Constant[TemperatureRateKind]):
    _constant_kind = "TemperatureRate"


class _MagneticMomentConstant(Constant[MagneticMomentKind]):
    _constant_kind = "MagneticMoment"


class _MagnetizationConstant(Constant[MagnetizationKind]):
    _constant_kind = "Magnetization"


class _ParticleDensityConstant(Constant[ParticleDensityKind]):
    _constant_kind = "ParticleDensity"


class _ElectronDensityConstant(Constant[ElectronDensityKind]):
    _constant_kind = "ElectronDensity"


class _AngleConstant(Constant[AngleKind]):
    _constant_kind = "Angle"


class _FrequencyConstant(Constant[FrequencyKind]):
    _constant_kind = "Frequency"


class _InverseTimeConstant(Constant[InverseTimeKind]):
    _constant_kind = "InverseTime"


class _AtomCountConstant(Constant[AtomCountKind]):
    _constant_kind = "AtomCount"


class _ElectronCountConstant(Constant[ElectronCountKind]):
    _constant_kind = "ElectronCount"


class _MassConstant(Constant[MassKind]):
    _constant_kind = "Mass"


class _MassDensityConstant(Constant[MassDensityKind]):
    _constant_kind = "MassDensity"


class _MomentumConstant(Constant[MomentumKind]):
    _constant_kind = "Momentum"


class _AccelerationConstant(Constant[AccelerationKind]):
    _constant_kind = "Acceleration"


class _ChargeConstant(Constant[ChargeKind]):
    _constant_kind = "Charge"


class _ElectricPotentialConstant(Constant[ElectricPotentialKind]):
    _constant_kind = "ElectricPotential"


class _ElectricFieldConstant(Constant[ElectricFieldKind]):
    _constant_kind = "ElectricField"


class _DipoleMomentConstant(Constant[DipoleMomentKind]):
    _constant_kind = "DipoleMoment"


class _EntropyConstant(Constant[EntropyKind]):
    _constant_kind = "Entropy"


class _ActionConstant(Constant[ActionKind]):
    _constant_kind = "Action"
