from quantype._generated import Angle, Area, Dimensionless, Length

def sqrt[V](quantity: Area[V]) -> Length[V]: ...
def sin[V](quantity: Angle[V]) -> Dimensionless[V]: ...
def exp[V](quantity: Dimensionless[V]) -> Dimensionless[V]: ...
