from typing import Any, Self

import numpy as np
import numpy.typing as npt

class Unit[K]:
    name: str
    kind: str
    scale: float
    offset: float
    symbol: str
    def __init__(
        self,
        name: str,
        kind: str,
        scale: float = ...,
        offset: float = ...,
        symbol: str | None = ...,
    ) -> None: ...

class Quantity[K, V]:
    _kind: str
    _display: str | None
    def __init__(self, value: V) -> None: ...
    @property
    def value(self) -> V: ...
    @property
    def kind(self) -> str: ...
    @property
    def dimensions(self) -> tuple[int, ...]: ...
    @classmethod
    def from_canonical[W](cls, value: W) -> Quantity[K, W]: ...
    @classmethod
    def parse(cls, data: object) -> Quantity[K, float | npt.NDArray[np.float64]]: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, source_type: Any, handler: Any) -> Any: ...
    def magnitude(self, unit: Unit[K] | None = ...) -> V: ...
    def to(self, unit: Unit[K]) -> Self: ...
    def to_dict(self, unit: Unit[K] | None = ...) -> dict[str, object]: ...

def result_kind(op: str, left: str, right: str) -> str: ...
def dimensions(kind: str) -> tuple[int, ...]: ...
def _wrap(kind: str, value: Any) -> Quantity[Any, Any]: ...
def get_unit(name: str) -> Unit[Any]: ...
