# mypy: disable-error-code=overload-overlap
# pyright: reportOverlappingOverload=false
from collections.abc import Iterator, Sequence
from typing import (
    Any,
    ClassVar,
    Generic,
    Literal,
    Protocol,
    Self,
    overload,
    override,
)

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeVar

from quantype._internal._kind_types import Div, Mul, Pow
from quantype._internal._semantics import Semantic
from quantype._internal._systems import Atomistic, UnitSystem
from quantype._internal._unit import Unit as Unit
from quantype._internal._unit import get_unit as get_unit
from quantype.kinds import DimensionlessKind

__all__ = [
    "Constant",
    "Quantity",
    "Unit",
    "dimensions",
    "get_unit",
    "result_kind",
]

# PEP 695 cannot express the system default before Python 3.13. Public
# parameter names read better in diagnostics than private ones.
# ruff: noqa: PYI001
K = TypeVar("K")
V = TypeVar("V")
S = TypeVar("S", bound=UnitSystem, default=Atomistic)

type _StructuralQuantity[A, B, X, Y: UnitSystem] = (
    Quantity[Mul[A, B], X, Y] | Quantity[Div[A, B], X, Y] | Quantity[Pow[A, B], X, Y]
)

class Quantity(Generic[K, V, S]):
    _kind: str
    _semantic: Semantic
    _system: type[UnitSystem]
    _display: Unit[K] | None
    _echo: float | None
    # Without a storage parameter, a float, NumPy float, or array is the
    # storage. Calling the unit converts integers and lists to float storage,
    # which an __init__ can't express in every checker, so they leave V open.
    @overload
    def __init__(
        self, value: int | np.integer[Any] | Sequence[Any], unit: Unit[K]
    ) -> None: ...
    @overload
    def __init__(self, value: V, unit: Unit[K]) -> None: ...
    @overload
    def __init__(
        self, value: object, unit: Unit[K], *, dtype: object = ...
    ) -> None: ...
    @classmethod
    def define_unit(
        cls,
        name: str,
        *,
        reference: Unit[K],
        scale: float = ...,
        offset: float = ...,
        symbol: str | None = ...,
    ) -> Unit[K]: ...
    @classmethod
    def unit_named(
        cls, name: str, *, units: tuple[Unit[Any], ...] = ...
    ) -> Unit[K]: ...
    @property
    def value(self) -> V: ...
    @property
    def kind(self) -> str: ...
    @property
    def dimensions(self) -> tuple[int, ...]: ...
    @property
    def system(self) -> type[S]: ...
    @property
    def unit(self) -> Unit[K] | None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @classmethod
    def from_value[W](cls, value: W) -> Quantity[K, W, S]: ...
    @classmethod
    def reinterpret[W, T: UnitSystem](
        cls, quantity: Quantity[Any, W, T]
    ) -> Quantity[K, W, T]: ...
    @overload
    @classmethod
    def parse(
        cls, data: str, *, units: tuple[Unit[Any], ...] = ...
    ) -> Quantity[K, float, S]: ...
    @overload
    @classmethod
    def parse(
        cls, data: object, *, units: tuple[Unit[Any], ...] = ...
    ) -> Quantity[K, float | npt.NDArray[np.float64], S]: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, source_type: Any, handler: Any) -> Any: ...
    def _check_unit(self, unit: Unit[K], hint: str = ...) -> None: ...
    def _same_system(self, other: Quantity[Any, Any, Any]) -> None: ...
    def _with(self, raw: Any, *, display: bool = ...) -> Self: ...
    def magnitude(self, unit: Unit[K] | None = ...) -> V: ...
    def to(self, unit: Unit[K]) -> Self: ...
    def with_value(self, value: V, /) -> Self: ...
    def to_system[T: UnitSystem](self, system: type[T]) -> Quantity[K, V, T]: ...
    def to_dict(self, unit: Unit[K] | None = ...) -> dict[str, object]: ...
    def __pos__(self) -> Self: ...
    def mean(
        self, axis: int | tuple[int, ...] | None = ..., *, keepdims: bool = ...
    ) -> Self: ...
    def max(
        self, axis: int | tuple[int, ...] | None = ..., *, keepdims: bool = ...
    ) -> Self: ...
    def min(
        self, axis: int | tuple[int, ...] | None = ..., *, keepdims: bool = ...
    ) -> Self: ...
    def __getitem__(self, key: Any, /) -> Self: ...
    @property
    def dtype(self) -> Any: ...
    def reshape(self, *shape: int | tuple[int, ...]) -> Self: ...
    def transpose(self, *axes: int) -> Self: ...
    @property
    def T(self) -> Self: ...  # noqa: N802 -- NumPy's name
    def squeeze(self, axis: int | None = ...) -> Self: ...
    def cumsum(self, axis: int | None = ...) -> Self: ...
    # Named kinds refine this; a spread of temperatures is a difference.
    @overload
    def std[Q: _StructuralQuantity[Any, Any, Any, Any]](
        self: Q, axis: int | None = ..., *, ddof: int = ..., keepdims: bool = ...
    ) -> Q: ...
    @overload
    def std(
        self, axis: int | None = ..., *, ddof: int = ..., keepdims: bool = ...
    ) -> Quantity[Any, V, S]: ...
    # Named kinds refine var and item; unnamed products square structurally.
    @overload
    def var[A, B](
        self: _StructuralQuantity[A, B, V, S],
        axis: int | None = ...,
        *,
        ddof: int = ...,
        keepdims: bool = ...,
    ) -> Quantity[Pow[K, Literal[2]], V, S]: ...
    @overload
    def var(
        self, axis: int | None = ..., *, ddof: int = ..., keepdims: bool = ...
    ) -> Quantity[Any, V, S]: ...
    def item(self) -> Quantity[K, float, S]: ...
    def copy(self) -> Self: ...
    @property
    def size(self) -> int: ...
    def ravel(self) -> Self: ...
    def flatten(self) -> Self: ...
    def argmin(self, axis: int | None = ...) -> Any: ...
    def argmax(self, axis: int | None = ...) -> Any: ...
    def argsort(self, axis: int = ...) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Self]: ...
    # Value equality: bool for scalar storage, element-wise for arrays.
    @override
    def __eq__(self, other: object, /) -> Any: ...
    @override
    def __ne__(self, other: object, /) -> Any: ...
    # Scalar storage hashes by value; array storage raises TypeError.
    @override
    def __hash__(self) -> int: ...
    # Ordering requires the same kind and system; K and S anchor to the class.
    @overload
    def __lt__(
        self: Quantity[K, float, S], other: Quantity[K, float, S], /
    ) -> bool: ...
    @overload
    def __lt__(self, other: Quantity[K, Any, S], /) -> Any: ...
    @overload
    def __le__(
        self: Quantity[K, float, S], other: Quantity[K, float, S], /
    ) -> bool: ...
    @overload
    def __le__(self, other: Quantity[K, Any, S], /) -> Any: ...
    @overload
    def __gt__(
        self: Quantity[K, float, S], other: Quantity[K, float, S], /
    ) -> bool: ...
    @overload
    def __gt__(self, other: Quantity[K, Any, S], /) -> Any: ...
    @overload
    def __ge__(
        self: Quantity[K, float, S], other: Quantity[K, float, S], /
    ) -> bool: ...
    @overload
    def __ge__(self, other: Quantity[K, Any, S], /) -> Any: ...
    # Named quantities have catalogue-generated operators. Restrict base
    # arithmetic to structural trees, so each named kind's own operators apply.
    # K remains anchored to the class, preserving nominal tree equality.
    @overload
    def __add__[A, B, W](
        self: _StructuralQuantity[A, B, float, S], other: Quantity[K, W, S], /
    ) -> Quantity[K, W, S]: ...
    @overload
    def __add__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: Quantity[K, float, S], /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __add__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: Quantity[K, V, S], /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __sub__[A, B, W](
        self: _StructuralQuantity[A, B, float, S], other: Quantity[K, W, S], /
    ) -> Quantity[K, W, S]: ...
    @overload
    def __sub__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: Quantity[K, float, S], /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __sub__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: Quantity[K, V, S], /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __mul__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Scalar, /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __mul__[A, B, W: _Numerical](
        self: _StructuralQuantity[A, B, float, S], other: W, /
    ) -> Quantity[K, W, S]: ...
    @overload
    def __mul__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Numerical, /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __mul__[A, B, L, W](
        self: _StructuralQuantity[A, B, float, S], other: Quantity[L, W, S], /
    ) -> Quantity[Mul[K, L], W, S]: ...
    @overload
    def __mul__[A, B, L](
        self: _StructuralQuantity[A, B, V, S], other: Quantity[L, float, S], /
    ) -> Quantity[Mul[K, L], V, S]: ...
    @overload
    def __mul__[A, B, L](
        self: _StructuralQuantity[A, B, V, S], other: Quantity[L, V, S], /
    ) -> Quantity[Mul[K, L], V, S]: ...
    @overload
    def __truediv__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Scalar, /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __truediv__[A, B, W: _Numerical](
        self: _StructuralQuantity[A, B, float, S], other: W, /
    ) -> Quantity[K, W, S]: ...
    @overload
    def __truediv__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Numerical, /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __truediv__[A, B, L, W](
        self: _StructuralQuantity[A, B, float, S], other: Quantity[L, W, S], /
    ) -> Quantity[Div[K, L], W, S]: ...
    @overload
    def __truediv__[A, B, L](
        self: _StructuralQuantity[A, B, V, S], other: Quantity[L, float, S], /
    ) -> Quantity[Div[K, L], V, S]: ...
    @overload
    def __truediv__[A, B, L](
        self: _StructuralQuantity[A, B, V, S], other: Quantity[L, V, S], /
    ) -> Quantity[Div[K, L], V, S]: ...
    @overload
    def __rmul__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Scalar, /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __rmul__[A, B, W: _Numerical](
        self: _StructuralQuantity[A, B, float, S], other: W, /
    ) -> Quantity[K, W, S]: ...
    @overload
    def __rmul__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Numerical, /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __matmul__[A, B, W: _Numerical](
        self: _StructuralQuantity[A, B, float, S], other: W, /
    ) -> Quantity[K, W, S]: ...
    @overload
    def __matmul__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Numerical, /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __matmul__[A, B, L, W](
        self: _StructuralQuantity[A, B, float, S], other: Quantity[L, W, S], /
    ) -> Quantity[Mul[K, L], W, S]: ...
    @overload
    def __matmul__[A, B, L](
        self: _StructuralQuantity[A, B, V, S],
        other: Quantity[L, V, S] | Quantity[L, float, S],
        /,
    ) -> Quantity[Mul[K, L], V, S]: ...
    @overload
    def __rmatmul__[A, B, W: _Numerical](
        self: _StructuralQuantity[A, B, float, S], other: W, /
    ) -> Quantity[K, W, S]: ...
    @overload
    def __rmatmul__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Numerical, /
    ) -> Quantity[K, V, S]: ...
    @overload
    def __rtruediv__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Scalar, /
    ) -> Quantity[Div[DimensionlessKind, K], V, S]: ...
    @overload
    def __rtruediv__[A, B, W: _Numerical](
        self: _StructuralQuantity[A, B, float, S], other: W, /
    ) -> Quantity[Div[DimensionlessKind, K], W, S]: ...
    @overload
    def __rtruediv__[A, B](
        self: _StructuralQuantity[A, B, V, S], other: _Numerical, /
    ) -> Quantity[Div[DimensionlessKind, K], V, S]: ...
    # Zero means the same in every unit, so builtin sum() works. sum() requires
    # any int here; only zero is accepted at runtime. These and the methods
    # below keep an unnamed product's own class, such as a product class from
    # quantype.products; named kinds declare their own.
    def __radd__[Q: _StructuralQuantity[Any, Any, Any, Any]](
        self: Q, other: int, /
    ) -> Q: ...
    def __rsub__[Q: _StructuralQuantity[Any, Any, Any, Any]](
        self: Q, other: int, /
    ) -> Q: ...
    # A literal square keeps its exponent in every checker, so qnp.sqrt undoes it.
    @overload
    def __pow__[A, B](
        self: _StructuralQuantity[A, B, V, S], exponent: Literal[2], /
    ) -> Quantity[Pow[K, Literal[2]], V, S]: ...
    @overload
    def __pow__[A, B, N: int](
        self: _StructuralQuantity[A, B, V, S], exponent: N, /
    ) -> Quantity[Pow[K, N], V, S]: ...
    def __neg__[Q: _StructuralQuantity[Any, Any, Any, Any]](self: Q) -> Q: ...
    def __abs__[Q: _StructuralQuantity[Any, Any, Any, Any]](self: Q) -> Q: ...
    def sum[Q: _StructuralQuantity[Any, Any, Any, Any]](
        self: Q, axis: int | tuple[int, ...] | None = ..., *, keepdims: bool = ...
    ) -> Q: ...

def require_unit(unit: object, kind: str, hint: str = ...) -> None: ...

type _Scalar = float | np.floating[Any] | np.integer[Any]

# An operand the generated stubs repeat in thousands of signatures. Pyright
# prints an alias's name in diagnostics, so aliases stand only for parameters.
type _IntArray = npt.NDArray[np.integer[Any]]  # noqa: PYI047

# A NumPy, JAX or Torch array scaling a quantity: each exports through DLPack,
# which quantities do not, so a quantity never matches it.
class _Numerical(Protocol):
    def __dlpack__(self) -> object: ...

# A quantity as an operand of a constant. Typing it structurally, not as
# Quantity, spares checkers from binding Quantity's structural-only __mul__,
# and keeps it from competing with the named relations' overloads.
class _Operand[K, V, S: UnitSystem](Protocol):
    @property
    def value(self) -> V: ...
    @property
    def system(self) -> type[S]: ...
    def magnitude(self, unit: Unit[K] | None = ..., /) -> V: ...

# System-free: arithmetic with a quantity adopts that quantity's unit system.
# Generated per-kind subclasses add the catalogue's named relations.
class Constant[K]:
    name: str
    __array_ufunc__: None
    _constant_kind: ClassVar[str]
    def __init__(self, name: str, semantic: Semantic, reference: float) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def dimensions(self) -> tuple[int, ...]: ...
    def to_system[T: UnitSystem](self, system: type[T]) -> Quantity[K, float, T]: ...
    def magnitude(self, unit: Unit[K]) -> float: ...
    def to(self, unit: Unit[K]) -> Quantity[K, float, Atomistic]: ...
    @overload
    def __mul__(self, other: _Scalar, /) -> Self: ...
    @overload
    def __mul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[K, L], W, T]: ...
    @overload
    def __mul__[L](self, other: Constant[L], /) -> Constant[Mul[K, L]]: ...
    @overload
    def __rmul__(self, other: _Scalar, /) -> Self: ...
    @overload
    def __rmul__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Mul[L, K], W, T]: ...
    @overload
    def __truediv__(self, other: _Scalar, /) -> Self: ...
    @overload
    def __truediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[K, L], W, T]: ...
    @overload
    def __truediv__[L](self, other: Constant[L], /) -> Constant[Div[K, L]]: ...
    @overload
    def __rtruediv__(
        self, other: _Scalar, /
    ) -> Constant[Div[DimensionlessKind, K]]: ...
    @overload
    def __rtruediv__[L, W, T: UnitSystem](
        self, other: _Operand[L, W, T], /
    ) -> Quantity[Div[L, K], W, T]: ...
    def __pow__[N: int](self, exponent: N, /) -> Constant[Pow[K, N]]: ...
    def __neg__(self) -> Self: ...

def result_kind(op: str, left: Semantic, right: Semantic) -> Semantic: ...
def dimensions(kind: str | Semantic) -> tuple[int, ...]: ...
def _rescaled(raw: Any, scale: float) -> Any: ...
def _constant(name: str, semantic: Semantic, reference: float) -> Constant[Any]: ...
def _wrap(
    kind: str | Semantic,
    value: Any,
    system: type[UnitSystem] | None,
    *,
    display: Unit[Any] | None = ...,
    echo: float | None = ...,
) -> Quantity[Any, Any, Any]: ...
def _unit_named(
    cls: type[Quantity[Any, Any, Any]],
    name: str,
    units: tuple[Unit[Any], ...],
    system: type[UnitSystem],
) -> Unit[Any]: ...
def _parse(
    cls: type[Quantity[Any, Any, Any]],
    data: object,
    units: tuple[Unit[Any], ...],
    system: type[UnitSystem],
) -> Quantity[Any, Any, Any]: ...
