name: Checks

on:
  push:
  pull_request:

jobs:
  prototype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync --locked
      - run: uv run just check-generated
      - run: uv run just lint
      - run: uv run just typecheck
      - run: uv run just test
      - run: uv build
